project:
  render:
     - index.qmd
     - Chapter_1/Theory.qmd
     - Chapter_1/Practicals/no_solution.qmd
     - Chapter_1/Practicals/solution.qmd
     - Chapter_1/Practicals/material.qmd
     - Chapter_2/Theory.qmd
     - Chapter_2/Practicals/no_solution.qmd
     - Chapter_2/Practicals/solution.qmd
     - Chapter_3/Theory.qmd
     - Chapter_3/Practicals/no_solution.qmd
     - Chapter_3/Practicals/solution.qmd
     - Supplements/distributions.qmd
     - Supplements/glossary.qmd
  output-dir: _site-prod
website:
  sidebar:
    contents:
      - section: "Theory"
        contents:
              - href: Chapter_1/Theory.qmd
                text: "Chapter 1"
              - href: Chapter_2/Theory.qmd
                text: "Chapter 2"
              - href: Chapter_3/Theory.qmd
                text: "Chapter 3"
      - section: "Practicals"
        contents:
              - href: Chapter_1/Practicals/no_solution.qmd
                text: "Chapter 1"
              - href: Chapter_2/Practicals/no_solution.qmd
                text: "Chapter 2"
              - href: Chapter_3/Practicals/no_solution.qmd
                text: "Chapter 3"
      - section: "Solutions"
        contents:
               - href: Chapter_1/Practicals/solution.qmd
                 text: "Chapter 1"
               - href: Chapter_2/Practicals/solution.qmd
                 text: "Chapter 2"
               - href: Chapter_3/Practicals/solution.qmd
                 text: "Chapter 3"
      - section: "Supplements"
        contents:
               - href: Supplements/distributions.qmd
                 text: "Distributions"
               - href: Supplements/glossary.qmd
                 text: "Glossary"
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
execute:
  eval: true
  freeze: auto
  warning: false
  message: false
