project:
  render:
     - index.qmd
     - Chapter_1/Theory.qmd
     - Chapter_1/Practicals/no_solution.qmd
     - Chapter_1/Practicals/solution.qmd
     - Chapter_1/Practicals/material.qmd
  output-dir: _site-prod
website:
  sidebar:
    contents:
      - section: "Theory"
        contents:
              - href: Chapter_1/Theory.qmd
                text: "Chapter 1"
      - section: "Practicals"
        contents:
              - href: Chapter_1/Practicals/no_solution.qmd
                text: "Chapter 1"
      - section: "Solutions"
        contents:
               - href: Chapter_1/Practicals/solution.qmd
                 text: "Chapter 1 (solutions)"
format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
execute:
  eval: true
  freeze: auto
  warning: false
  message: false
