project:
  type: website
  render:
     - "**/*.qmd"
website:
  reader-mode: true
  title: "Ecological Models and Data Analysis"
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "Theory"
        contents:
              - href: Chapter_1/Theory.qmd
                text: "Chapter 1"
              - href: Chapter_2/Theory.qmd
                text: "Chapter 2"
              - href: Chapter_3/Theory.qmd
                text: "Chapter 3"
              - href: Chapter_4/Theory.qmd
                text: "Chapter 4"
              - href: Chapter_5/Theory.qmd
                text: "Chapter 5"
              - href: Chapter_6/Theory.qmd
                text: "Chapter 6"
              - href: Chapter_7/Theory.qmd
                text: "Chapter 7"
              - href: Chapter_8/Theory.qmd
                text: "Chapter 8"
              - href: Chapter_9/Theory.qmd
                text: "Chapter 9"
      - section: "Practicals"
        contents:
              - href: Chapter_1/Practicals/no_solution.qmd
                text: "Chapter 1"
              - href: Chapter_2/Practicals/no_solution.qmd
                text: "Chapter 2"
              - href: Chapter_3/Practicals/no_solution.qmd
                text: "Chapter 3"
              - href: Chapter_4/Practicals/no_solution.qmd
                text: "Chapter 4"
              - href: Chapter_5/Practicals/no_solution.qmd
                text: "Chapter 5"
              - href: Chapter_6/Practicals/no_solution.qmd
                text: "Chapter 6"
              - href: Chapter_7/Practicals/no_solution.qmd
                text: "Chapter 7"
              - href: Chapter_8/Practicals/no_solution.qmd
                text: "Chapter 8"
              - href: Chapter_9/Practicals/no_solution.qmd
                text: "Chapter 9"
      - section: "Solutions"
        contents:
              - href: Chapter_1/Practicals/Solution.qmd
                text: "Chapter 1 (solutions)"
              - href: Chapter_2/Practicals/solution.qmd
                text: "Chapter 2 (solutions)"
              - href: Chapter_3/Practicals/solution.qmd
                text: "Chapter 3 (solutions)"
              - href: Chapter_4/Practicals/solution.qmd
                text: "Chapter 4 (solutions)"
              - href: Chapter_5/Practicals/solution.qmd
                text: "Chapter 5 (solutions)"
              - href: Chapter_6/Practicals/solution.qmd
                text: "Chapter 6 (solutions)"
              - href: Chapter_7/Practicals/solution.qmd
                text: "Chapter 7 (solutions)"
              - href: Chapter_8/Practicals/solution.qmd
                text: "Chapter 8 (solutions)"
              - href: Chapter_9/Practicals/solution.qmd
                text: "Chapter 9 (solutions)"
      - href: Supplements/canned.qmd
        text: "Supplement: Formula-based methods"
      - href: Supplements/distributions.qmd
        text: "Supplement: Distributions"
      - href: Supplements/deterministic-functions.qmd
        text: "Supplement: Deterministic functions"
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
