project:
  render:
     - index.qmd
     - Chapter_1/Theory.qmd
     - Chapter_1/Practicals/no_solution.qmd
     - Chapter_1/Practicals/solution.qmd
     - Chapter_1/Practicals/material.qmd
     - Chapter_2/Theory.qmd
     - Chapter_2/Practicals/no_solution.qmd
     - Chapter_2/Practicals/solution.qmd
     - Chapter_3/Theory.qmd
     - Chapter_3/Practicals/no_solution.qmd
     - Chapter_3/Practicals/solution.qmd
     - Chapter_4/Theory.qmd
     - Chapter_4/Practicals/no_solution.qmd
     - Chapter_4/Practicals/solution.qmd
     - Chapter_5/Theory.qmd
     - Chapter_5/Practicals/no_solution.qmd
     - Chapter_5/Practicals/solution.qmd
     - Supplements/distributions.qmd
     - Supplements/deterministic-functions.qmd
     - Supplements/calculus.qmd
     - Supplements/glossary.qmd
     - Supplements/canned.qmd
  output-dir: _site-prod
website:
  sidebar:
    contents:
      - section: "Theory"
        contents:
              - href: Chapter_1/Theory.qmd
                text: "Chapter 1"
              - href: Chapter_2/Theory.qmd
                text: "Chapter 2"
              - href: Chapter_3/Theory.qmd
                text: "Chapter 3"
              - href: Chapter_4/Theory.qmd
                text: "Chapter 4"
              - href: Chapter_5/Theory.qmd
                text: "Chapter 5"
      - section: "Practicals"
        contents:
              - href: Chapter_1/Practicals/no_solution.qmd
                text: "Chapter 1"
              - href: Chapter_2/Practicals/no_solution.qmd
                text: "Chapter 2"
              - href: Chapter_3/Practicals/no_solution.qmd
                text: "Chapter 3"
              - href: Chapter_4/Practicals/no_solution.qmd
                text: "Chapter 4"
              - href: Chapter_5/Practicals/no_solution.qmd
                text: "Chapter 5"
      - section: "Solutions"
        contents:
               - href: Chapter_1/Practicals/solution.qmd
                 text: "Chapter 1"
               - href: Chapter_2/Practicals/solution.qmd
                 text: "Chapter 2"
               - href: Chapter_3/Practicals/solution.qmd
                 text: "Chapter 3"
               - href: Chapter_4/Practicals/solution.qmd
                 text: "Chapter 4"
               - href: Chapter_5/Practicals/solution.qmd
                 text: "Chapter 5"
      - section: "Supplements"
        contents:
               - href: Supplements/distributions.qmd
                 text: "Distributions"
               - href: Supplements/deterministic-functions.qmd
                 text: "Deterministic functions"
               - href: Supplements/calculus.qmd
                 text: "Calculus refresher"
               - href: Supplements/glossary.qmd
                 text: "Glossary"
               - href: Supplements/canned.qmd
                 text: "Formula-based methods"
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
execute:
  eval: true
  freeze: auto
  warning: false
  message: false
