project:
  type: website
profile:
  default: dev
  group:
    - [dev, prod]
website:
  reader-mode: true
  title: "Ecological Models and Data Analysis"
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
