---
title: "Ecological Models and Data Analysis"
author: "Alejandro Morales"
date: today
---

This is an online book used primarily for the course [CSA-33706 Ecological Modelling and Data Analysis](https://studyhandbook.wur.nl/modules/CSA33706?type=Cursory) at Wageningen University. It is
also designed for self-study so it may also be useful for people not attending the course.

This book is very much inspired and based on Benjamin Bolker's book [Ecological Models and Data in R](https://math.mcmaster.ca/~bolker/emdbook/index.html). I have mostly switched to more modern R code,
drop entirely the Bayesian component and extended hiearchical/multileve models. Note that
the style and tone of this book (and all the language errors I have committed) are
entirely my own as well as any mistakes and factual errors. The original book has mostly
served as guidance for which topics to focus on as we have been teaching our course with
Bolker's book for 15 years. If you really like this topic please consider checking the
original book, there are many gems in there that are worth discovering. When I read it as
a student it completely changed my mind about statistics, its relationship with modeling
(which is my true passion) and has had a big influence on my career so far.

This book is licensed under a [Creative Commons Attribution-NonCommercial 4.0 International License](https://creativecommons.org). Please feel free to use it in your own teaching and modify it as
needed, you do not need my permission for that.

**AI disclaimer** - This textbook has been written in collaboration with OpenAI's Codex
(specifically the GPT-5.6 series) but all the text and code presented was (re)written
by me, as I dislike the style in which AI writes prose and code and structures the text (and
this may reflect might limitation in constraining the AI properly). I guess it is also a
matter of pride and honesty that I want to actually write the words and code you read.

I used AI to come up with exercises and examples (especially the ones that are not plant
related), double check some of my facts, correct my faulty English and brainstorm
the content in early drafts. It was particularly useful to generate equations (I can do
Latex but it is very cumbersome) and make complex plots (I had to edit them a bit at the end).

# How to use this book

Use the sidebar to navigate through the the different parts. The book is structured
into Theory, Practicals, Solutions and Supplements. I give some guidance and tips below
on how to work through each type of material.


## Theory

This explains the different concepts that the book is set out to explain, organized in
chapters. The book is fairly linear: a chapter assumes the content of previous chapters
so they should be studied in order. The theory is always supported by examples that include
R code and mathematical calculations. I recommend that you type any R code that you see and
do the calculations yourself, as switching your brain to "active mode" rather than just
reading can help with this type of learning.

There are some short exercises embedded within the text as well as a short
quiz. These are meant to be done by yourself the moment they appear. The solutions and (possible)
answers are always provided in a collapse box, so that you can check your own answers against
them. If the answer does not make sense, or you got really stuck, I would suggest to read
the section again, or check the concepts online or with AI, since these exercises and quizzes
are meant to be doable if the concepts are understood.

Some definitions, important concepts and potential pitfalls are highlighted in colored
boxes. This does not mean that other ideas or concepts in the text are not important, I
just want to highlight specific things that I feel are particularly important.

## Practicals and Solutions

For each chapter there are 4 - 8 exercises provided, implementing the skills
that were taught in that chapter (plus anything that was already covered in the previous)
chapter. The solution to the first exercise is provided for you in detail and it is meant to
help further learn the programming component of the course. The solutions for the rest of the
exercises are given in the "Solutions" section. As with the exercises within the Theory
chapters, please make sure to try the exercise first by yourself before looking at the
solution and if you could not do it or do not understand the solution, make sure to go back
to the theory or use other sources to understand it.

Chapter 1 is specially since the theory is just a general introduction and overview of the
course, so there is no real practice to do. Instead, I provide a thorough crash course to
programming in R with most of the skills relevant to the rest of the book (specific
methods for modelling and visualization are provided as needed in posterior chapters). I
expect three possible starting points for the reader:

- If you are already fluent in R you can safely skip this practical.

- If you have some programming in experience with other programming languages (e.g. Python
or Matlab) I recommend to go through this practical to make sure that you understadn how to
translate the skills you already have to R (which is a rather peculiar language).

- If you have never programmed, I definetely recommend doing the entire practical but I also
suspect you need extra practice and support beyond what this book offers, as some
programming literacy is assumed. There are many sources online that teach the level of R
required for this course and AI can always be used as a personalised tutor.

## Supplements

Two of the supplements contain reference material containing a long list of distributions
and deterministic functions with their properties. These are meant to be supplements to
Chapters 2 and 5.

The third supplement contains a detailed description of different R packages for statistical
modelling where one does not have to write their own likelihood function but rather specify
the deterministic component with a formula and (in some cases) select a distribution. These
are the packages that most statistical books based on R would teach and what many ecologists
use. I explain the different modelling functions from a wide selection of R packages by
describing the type of likelihood functions that are (implicitly) allowed by each function.
My hope is that this comparison allows you to understand better the different types of
statistical models that are commonly used, in case you need to use them or you read a paper
that uses them.
