<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-10-06">

<title>Chapter 5: Deterministic functions in ecology – Ecological Models and Data Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-24c09a13944ec7e1f31d2917b1251fc2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../Chapter_1/Practicals/no_solution.html">Practicals</a></li><li class="breadcrumb-item"><a href="../../Chapter_5/Practicals/no_solution.html">Chapter 5</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Ecological Models and Data Analysis</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Theory</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_1/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_2/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_3/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_4/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_5/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Practicals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_1/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_2/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_3/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_4/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_5/Practicals/no_solution.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Chapter 5</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Solutions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_1/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_2/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_3/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_4/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_5/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplements</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/deterministic-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deterministic functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculus refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercise-1-virus-titre-in-infected-rabbits" id="toc-exercise-1-virus-titre-in-infected-rabbits" class="nav-link active" data-scroll-target="#exercise-1-virus-titre-in-infected-rabbits"><span class="header-section-number">1</span> Exercise 1: Virus titre in infected rabbits</a>
  <ul class="collapse">
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution"><span class="header-section-number">1.1</span> Solution</a>
  <ul class="collapse">
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1"><span class="header-section-number">1.1.1</span> Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2"><span class="header-section-number">1.1.2</span> Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3"><span class="header-section-number">1.1.3</span> Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4"><span class="header-section-number">1.1.4</span> Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5"><span class="header-section-number">1.1.5</span> Question 5</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercise-2-limits-and-end-behaviour" id="toc-exercise-2-limits-and-end-behaviour" class="nav-link" data-scroll-target="#exercise-2-limits-and-end-behaviour"><span class="header-section-number">2</span> Exercise 2: Limits and end behaviour</a></li>
  <li><a href="#exercise-3-derivatives-and-slopes" id="toc-exercise-3-derivatives-and-slopes" class="nav-link" data-scroll-target="#exercise-3-derivatives-and-slopes"><span class="header-section-number">3</span> Exercise 3: Derivatives and slopes</a></li>
  <li><a href="#exercise-4-special-points" id="toc-exercise-4-special-points" class="nav-link" data-scroll-target="#exercise-4-special-points"><span class="header-section-number">4</span> Exercise 4: Special points</a></li>
  <li><a href="#exercise-5-parameters" id="toc-exercise-5-parameters" class="nav-link" data-scroll-target="#exercise-5-parameters"><span class="header-section-number">5</span> Exercise 5: Parameters</a></li>
  <li><a href="#exercise-6-enzyme-kinetics" id="toc-exercise-6-enzyme-kinetics" class="nav-link" data-scroll-target="#exercise-6-enzyme-kinetics"><span class="header-section-number">6</span> Exercise 6: Enzyme kinetics</a></li>
  <li><a href="#exercise-7-choosing-functions-for-fecundity-and-for-recruitment" id="toc-exercise-7-choosing-functions-for-fecundity-and-for-recruitment" class="nav-link" data-scroll-target="#exercise-7-choosing-functions-for-fecundity-and-for-recruitment"><span class="header-section-number">7</span> Exercise 7: Choosing functions for fecundity and for recruitment</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../Chapter_1/Practicals/no_solution.html">Practicals</a></li><li class="breadcrumb-item"><a href="../../Chapter_5/Practicals/no_solution.html">Chapter 5</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Chapter 5: Deterministic functions in ecology</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 6, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Exercise 1 analyses one function from end to end, with data on the amount of virus in the blood of infected rabbits. Exercises 2 to 5 are drills without data, one for each skill of the chapter: limits, derivatives, special points and parameters. Exercises 6 and 7 are cases with real data: the rate of an enzymatic reaction (the data set <code>Puromycin</code>, which comes with R), the fecundity of fir trees and the recruitment of a reef fish. The data of Exercises 1 and 7 are in the package <code>emdbook</code>, which you need to install once with <code>install.packages("emdbook")</code>. As in the theory, the curves are placed over the data by eye and nothing is fitted, which is the topic of <a href="../../Chapter_6/Theory.qmd">Chapter 6</a>.</p>
<p>Before you start, read the entries of the <a href="../../Supplements/deterministic-functions.html">function supplement</a> that the exercises name. If derivatives are no longer familiar, work through the <a href="../../Supplements/calculus.html">calculus refresher</a> first. Questions that start with “On paper” and the drills of Exercises 2 to 5 are meant to be done with pen and paper before you open R (a calculator is fine for logarithms and exponentials). Work through the first exercise before trying the remaining ones. The ideas and notation are introduced in the <a href="../../Chapter_5/Theory.html">Chapter 5 theory</a>.</p>
<section id="exercise-1-virus-titre-in-infected-rabbits" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Exercise 1: Virus titre in infected rabbits</h1>
<p>The data set <code>MyxoTiter_sum</code> in the package <code>emdbook</code> contains the titre of the myxoma virus in the blood of European rabbits on different days after infection, for viruses of four grades (Fenner and McIntyre 1956; the values were read from a figure in Dwyer et al. 1990). The titre measures the concentration of virus and is expressed as the logarithm in base 10 of the number of rabbit infectious doses. We keep the 27 observations of grade 1, which were taken between 2 and 9 days after infection:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the myxomatosis data from the emdbook package without attaching the package.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(MyxoTiter_sum, <span class="at">package =</span> <span class="st">"emdbook"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep the observations of virus grade 1: their number and the days that they cover.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>grade_1 <span class="ot">=</span> MyxoTiter_sum[MyxoTiter_sum<span class="sc">$</span>grade <span class="sc">==</span> <span class="dv">1</span>, ]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(grade_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(grade_1<span class="sc">$</span>day)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2 9</code></pre>
</div>
</div>
<p>A virus multiplies in its host until the immune response of the host catches up with it, so the titre rises from a low value, reaches a maximum and then declines. We describe this shape with the <a href="../../Supplements/deterministic-functions.html#sec-fn-ricker">Ricker</a> function,</p>
<p><span class="math display">\[
f(x)=a\,x\,e^{-bx},
\]</span></p>
<p>where <span class="math inline">\(x\)</span> is the time since infection in days, <span class="math inline">\(f(x)\)</span> is the titre, and <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are positive parameters. In this exercise we find out everything that the formula can tell us about the curve, and then we use it to place the curve over the data by eye.</p>
<ol type="1">
<li>On paper, find the units of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, the value of the function at <span class="math inline">\(x=0\)</span> and its limit as <span class="math inline">\(x\to\infty\)</span>.</li>
<li>On paper, derive <span class="math inline">\(f'(x)\)</span>. What is the slope of the function at <span class="math inline">\(x=0\)</span> and as <span class="math inline">\(x\to\infty\)</span>? Find the location and the height of the peak.</li>
<li>On paper, derive <span class="math inline">\(f''(x)\)</span> and find the inflection point. Where is the function concave and where is it convex?</li>
<li>Plot the titre against the day. Read the location and the height of the peak from the plot and calculate <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> from them, with their units.</li>
<li>Write the function in R and draw it over the data, marking the peak and the inflection point. Check the peak with <code>which.max()</code> and the derivative at day 2 with <code>D()</code>.</li>
</ol>
<section id="solution" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="solution"><span class="header-section-number">1.1</span> Solution</h2>
<section id="question-1" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="question-1"><span class="header-section-number">1.1.1</span> Question 1</h3>
<p>The units follow from the two rules of the <a href="../../Chapter_5/Theory.html#sec-deterministic-functions">theory</a>. The argument of an exponential has no units, so in <span class="math inline">\(e^{-bx}\)</span> the parameter <span class="math inline">\(b\)</span> must have the inverse units of <span class="math inline">\(x\)</span>: 1/day. The factor <span class="math inline">\(e^{-bx}\)</span> then has no units either, so the product <span class="math inline">\(ax\)</span> must have the units of <span class="math inline">\(f(x)\)</span>. As <span class="math inline">\(x\)</span> is in days, <span class="math inline">\(a\)</span> is in units of titre/day.</p>
<p>At <span class="math inline">\(x=0\)</span> the function is <span class="math inline">\(f(0)=a\times0\times e^{0}=0\)</span>. As <span class="math inline">\(x\to\infty\)</span> the factor <span class="math inline">\(x\)</span> grows without bound while <span class="math inline">\(e^{-bx}\)</span> goes to zero, so we have to find out which of the two wins. An exponential dominates any power of <span class="math inline">\(x\)</span> (see <a href="../../Chapter_5/Theory.html#sec-function-limits">Limits and asymptotes</a>), so</p>
<p><span class="math display">\[
\lim_{x\to\infty}a\,x\,e^{-bx}=\lim_{x\to\infty}\frac{a\,x}{e^{bx}}=0.
\]</span></p>
<p>The same result follows from L’Hôpital’s rule: the derivative of the numerator is <span class="math inline">\(a\)</span> and that of the denominator is <span class="math inline">\(b\,e^{bx}\)</span>, and <span class="math inline">\(a/(b\,e^{bx})\to0\)</span>. So the function starts at zero and returns to zero, which is what a hump-shaped function has to do.</p>
</section>
<section id="question-2" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="question-2"><span class="header-section-number">1.1.2</span> Question 2</h3>
<p>The function is the product of <span class="math inline">\(g(x)=ax\)</span> and <span class="math inline">\(h(x)=e^{-bx}\)</span>, with <span class="math inline">\(g'(x)=a\)</span> and, by the rule for the exponential, <span class="math inline">\(h'(x)=-b\,e^{-bx}\)</span>. The product rule gives</p>
<p><span class="math display">\[
\begin{aligned}
f'(x) &amp;= g'(x)\,h(x)+g(x)\,h'(x)\\
&amp;= a\,e^{-bx}-ab\,x\,e^{-bx}\\
&amp;= a\,(1-bx)\,e^{-bx}.
\end{aligned}
\]</span></p>
<p>At <span class="math inline">\(x=0\)</span> the slope is <span class="math inline">\(f'(0)=a\)</span>. So <span class="math inline">\(a\)</span> is the initial slope of the function, which agrees with its units (titre/day). As <span class="math inline">\(x\to\infty\)</span> the slope goes to zero, by the same argument as in question 1, because the exponential dominates the factor <span class="math inline">\(1-bx\)</span>.</p>
<p>At the peak the slope is zero. Since <span class="math inline">\(a\)</span> and <span class="math inline">\(e^{-bx}\)</span> are positive, <span class="math inline">\(f'(x)=0\)</span> only where <span class="math inline">\(1-bx=0\)</span>:</p>
<p><span class="math display">\[
x_{\max}=\frac{1}{b}, \qquad
f(x_{\max})=a\,\frac{1}{b}\,e^{-1}=\frac{a}{b\,e}.
\]</span></p>
<p>The slope is positive for <span class="math inline">\(x&lt;1/b\)</span> and negative for <span class="math inline">\(x&gt;1/b\)</span>, so this critical point is a maximum. The location of the peak, <span class="math inline">\(1/b\)</span>, is in days, and its height is in units of titre, as it should be.</p>
</section>
<section id="question-3" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="question-3"><span class="header-section-number">1.1.3</span> Question 3</h3>
<p>We differentiate <span class="math inline">\(f'(x)=a(1-bx)e^{-bx}\)</span>, again with the product rule. The derivative of <span class="math inline">\(a(1-bx)\)</span> is <span class="math inline">\(-ab\)</span> and that of <span class="math inline">\(e^{-bx}\)</span> is <span class="math inline">\(-b\,e^{-bx}\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
f''(x) &amp;= -ab\,e^{-bx}-ab\,(1-bx)\,e^{-bx}\\
&amp;= -ab\,(2-bx)\,e^{-bx}.
\end{aligned}
\]</span></p>
<p>The second derivative is zero where <span class="math inline">\(2-bx=0\)</span>, that is, at <span class="math inline">\(x=2/b\)</span>, which is twice the location of the peak. For <span class="math inline">\(x&lt;2/b\)</span> it is negative, so the function is concave (it bends downwards), and for <span class="math inline">\(x&gt;2/b\)</span> it is positive, so the function is convex (it bends upwards). The sign changes at <span class="math inline">\(x=2/b\)</span>, which makes it an inflection point. The value of the function and its slope at that point are</p>
<p><span class="math display">\[
f\!\left(\frac{2}{b}\right)=\frac{2a}{b\,e^{2}}, \qquad
f'\!\left(\frac{2}{b}\right)=a\,(1-2)\,e^{-2}=-\frac{a}{e^{2}}.
\]</span></p>
<p>This is the steepest decline of the function. Note that the value at the inflection point is <span class="math inline">\(2/e\approx0.74\)</span> times the height of the peak.</p>
</section>
<section id="question-4" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="question-4"><span class="header-section-number">1.1.4</span> Question 4</h3>
<p>We plot the 27 observations (<a href="#fig-titre_data" class="quarto-xref">Figure&nbsp;1</a>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Titre against the day of the observation.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(titer <span class="sc">~</span> day, <span class="at">data =</span> grade_1,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Time since infection (days)"</span>, <span class="at">ylab =</span> <span class="st">"Virus titre (log10 infectious doses)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-titre_data" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-titre_data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="no_solution_files/figure-html/fig-titre_data-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-titre_data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Titre of the myxoma virus of grade 1 in the blood of rabbits against the time since infection.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The titre increases from about 5.5 on day 2 and levels off between 7 and 8 from day 6 onwards. The observations do not show a clear decline, so the location of the peak can only be read roughly. We take a peak on day 6 with a titre of 7.6. With the two results of question 2 we can go from the peak to the parameters. From <span class="math inline">\(x_{\max}=1/b\)</span>,</p>
<p><span class="math display">\[
b=\frac{1}{x_{\max}}=\frac{1}{6}\approx0.167 \text{/day},
\]</span></p>
<p>and from <span class="math inline">\(f(x_{\max})=a/(be)\)</span>,</p>
<p><span class="math display">\[
a=f(x_{\max})\,b\,e=\frac{7.6\times2.718}{6}\approx3.44 \text{ units of titre/day}.
\]</span></p>
<p>That is, a curve with this peak starts with a slope of 3.44 units of titre/day. Its inflection point is at <span class="math inline">\(2/b=12\)</span> days, where the titre is <span class="math inline">\(2\times7.6/e\approx5.59\)</span> and the slope is <span class="math inline">\(-3.44/e^2\approx-0.47\)</span> units of titre/day. The observations end on day 9, so the inflection point lies outside the data.</p>
</section>
<section id="question-5" class="level3" data-number="1.1.5">
<h3 data-number="1.1.5" class="anchored" data-anchor-id="question-5"><span class="header-section-number">1.1.5</span> Question 5</h3>
<p>We write the function with the input first and the parameters after it, and draw it with the values of question 4 (<a href="#fig-titre_curve" class="quarto-xref">Figure&nbsp;2</a>). The dashed lines mark the peak and the triangle marks the inflection point:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ricker function: initial slope a and rate b.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ricker <span class="ot">=</span> <span class="cf">function</span>(x, <span class="at">a =</span> <span class="dv">1</span>, <span class="at">b =</span> <span class="dv">1</span>) {</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  a <span class="sc">*</span> x <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>b <span class="sc">*</span> x)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters calculated from a peak on day 6 with a titre of 7.6.</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>b_titre <span class="ot">=</span> <span class="dv">1</span> <span class="sc">/</span> <span class="dv">6</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>a_titre <span class="ot">=</span> <span class="fl">7.6</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="dv">1</span>) <span class="sc">/</span> <span class="dv">6</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># The observations, with axes that start at zero and include the inflection point.</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(titer <span class="sc">~</span> day, <span class="at">data =</span> grade_1, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">14</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Time since infection (days)"</span>, <span class="at">ylab =</span> <span class="st">"Virus titre (log10 infectious doses)"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># The curve, and dashed lines at the location and at the height of the peak.</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">ricker</span>(x, <span class="at">a =</span> a_titre, <span class="at">b =</span> b_titre), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"#D55E00"</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">1</span> <span class="sc">/</span> b_titre, <span class="at">h =</span> <span class="fl">7.6</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co"># The inflection point: twice the location of the peak.</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> <span class="dv">2</span> <span class="sc">/</span> b_titre, <span class="at">y =</span> <span class="fu">ricker</span>(<span class="dv">2</span> <span class="sc">/</span> b_titre, <span class="at">a =</span> a_titre, <span class="at">b =</span> b_titre),</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">17</span>, <span class="at">col =</span> <span class="st">"#D55E00"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-titre_curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-titre_curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="no_solution_files/figure-html/fig-titre_curve-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-titre_curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The same observations with a Ricker function whose parameters were calculated from a peak read by eye (a = 3.44, b = 1/6). Dashed lines mark the peak and the triangle marks the inflection point.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We can verify our math with R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Peak of the function on a fine grid of days: location and height.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>day_grid <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">14</span>, <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>titre_values <span class="ot">=</span> <span class="fu">ricker</span>(day_grid, <span class="at">a =</span> a_titre, <span class="at">b =</span> b_titre)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>day_grid[<span class="fu">which.max</span>(titre_values)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(titre_values)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Derivative with D() and with the formula of question 2, on day 2.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ricker_derivative <span class="ot">=</span> <span class="fu">D</span>(<span class="fu">expression</span>(a <span class="sc">*</span> x <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>b <span class="sc">*</span> x)), <span class="st">"x"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>ricker_derivative</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>a * exp(-b * x) - a * x * (exp(-b * x) * b)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eval</span>(ricker_derivative, <span class="fu">list</span>(<span class="at">a =</span> a_titre, <span class="at">b =</span> b_titre, <span class="at">x =</span> <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.644753</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>a_titre <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> b_titre <span class="sc">*</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>b_titre <span class="sc">*</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.644753</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Value of the function on days 2, 9 and 12 (the inflection point).</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ricker</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">9</span>, <span class="dv">12</span>), <span class="at">a =</span> a_titre, <span class="at">b =</span> b_titre)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.934260 6.914450 5.591768</code></pre>
</div>
</div>
<p>The highest value on the grid is 7.6 on day 6, as intended. <code>D()</code> does not simplify its result, but it returns the same slope as our formula: on day 2 the titre increases by 1.64 units of titre/day, about half of the initial slope. The value on day 12 is 5.59, as calculated on paper.</p>
<p>The curve passes through the middle of the observations between days 3 and 7. It gives a titre of 4.9 on day 2, a little below most of the observations of that day, and of 6.9 on day 9, where the observed titre is 7.7. The reason is the one that we met in the theory for the size of the tadpoles: in the Ricker function the parameter <span class="math inline">\(b\)</span> sets both the location of the peak and the rate of the decline after it, so with a peak on day 6 the curve has to decline at a given rate, whether the observations do or not. A function with a third parameter, such as the <a href="../../Supplements/deterministic-functions.html#sec-fn-generalised-ricker">generalised Ricker</a> function, could separate the two. Whether the extra parameter is supported by the data is a question for <a href="../../Chapter_6/Theory.qmd">Chapter 6</a>, where the curves are fitted.</p>
</section>
</section>
</section>
<section id="exercise-2-limits-and-end-behaviour" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Exercise 2: Limits and end behaviour</h1>
<p>The first thing to find out about a function is where it starts and where it ends. For each of the five functions below:</p>
<ul>
<li>on paper, calculate the value of the function at the lower end of its domain and its limit as <span class="math inline">\(x\to\infty\)</span>, with their units;</li>
<li>on paper, find the simpler function that it resembles close to the lower end of its domain;</li>
<li>sketch the function by hand, and only then draw it with <code>curve()</code> to check your sketch.</li>
</ul>
<p>The first three questions are the core of this exercise and the last two are extra practice. The entries of the supplement that you need are the <a href="../../Supplements/deterministic-functions.html#sec-fn-hyperbolic">hyperbolic</a>, <a href="../../Supplements/deterministic-functions.html#sec-fn-monomolecular">saturating exponential</a>, <a href="../../Supplements/deterministic-functions.html#sec-fn-holling3">Holling type III</a> and <a href="../../Supplements/deterministic-functions.html#sec-fn-michaelis-menten">Michaelis–Menten</a> functions.</p>
<ol type="1">
<li>The mean mass of a seedling (mg) as a function of the number of seedlings in a pot, <span class="math inline">\(x\)</span>: <span class="math inline">\(f(x)=\dfrac{480}{12+x}\)</span>.</li>
<li>The amount of nitrogen released from a crop residue (kg/ha) as a function of the time since it was ploughed in, <span class="math inline">\(x\)</span> (weeks): <span class="math inline">\(f(x)=90\left(1-e^{-0.2x}\right)\)</span>.</li>
<li>The number of seeds removed by rodents in one night as a function of the density of seeds, <span class="math inline">\(x\)</span> (seeds/m²): <span class="math inline">\(f(x)=\dfrac{30x^2}{100+x^2}\)</span>.</li>
<li>The number of eggs in the clutch of an insect as a function of the body mass of the female, <span class="math inline">\(x\)</span> (mg), for <span class="math inline">\(x\ge5\)</span>: <span class="math inline">\(f(x)=2+\dfrac{10\,(x-5)}{15+(x-5)}\)</span>.</li>
<li>A function in which a power and an exponential compete, for <span class="math inline">\(x\ge0\)</span>: <span class="math inline">\(f(x)=0.5\,x^2e^{-0.4x}\)</span>. Compare its behaviour close to zero with that of a Ricker function.</li>
</ol>
</section>
<section id="exercise-3-derivatives-and-slopes" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Exercise 3: Derivatives and slopes</h1>
<p>A derivative is the slope of a function, and it has the units of <span class="math inline">\(y\)</span> divided by the units of <span class="math inline">\(x\)</span>. Do all the questions on paper, name the rule that you use at each step (the rules are in the <a href="../../Supplements/calculus.html#sec-calc-rules">calculus refresher</a>), and give the units of every slope. The first three questions are the core of this exercise and the last two are extra practice. Questions 2 and 3 continue with functions of Exercise 2.</p>
<ol type="1">
<li>The body mass of a fish (g) as a function of its length <span class="math inline">\(x\)</span> (cm) follows the <a href="../../Supplements/deterministic-functions.html#sec-fn-power">power law</a> <span class="math inline">\(f(x)=0.01\,x^3\)</span>. Derive <span class="math inline">\(f'(x)\)</span> and calculate the mass and the slope for a fish of 20 cm. What are the units of the parameter 0.01?</li>
<li>For the saturating exponential function <span class="math inline">\(f(x)=a\left(1-e^{-bx}\right)\)</span>, derive <span class="math inline">\(f'(x)\)</span> and show that it can be written as <span class="math inline">\(f'(x)=b\,(a-f(x))\)</span>. What does this say about how the function approaches its asymptote? For the nitrogen released from a crop residue (<span class="math inline">\(a=90\)</span> kg/ha, <span class="math inline">\(b=0.2\)</span>/week), calculate the slope at the start and at the time when half of the nitrogen has been released.</li>
<li>For the Holling type III function <span class="math inline">\(f(x)=\dfrac{ax^2}{b^2+x^2}\)</span>, derive <span class="math inline">\(f'(x)\)</span>. What is the slope at <span class="math inline">\(x=0\)</span>? For the seeds removed by rodents (<span class="math inline">\(a=30\)</span> seeds/night, <span class="math inline">\(b=10\)</span> seeds/m²), calculate the slope at <span class="math inline">\(x=10\)</span> seeds/m².</li>
<li>The shell length of a snail (mm) as a function of its age <span class="math inline">\(x\)</span> (months) follows the <a href="../../Supplements/deterministic-functions.html#sec-fn-gompertz">Gompertz</a> function <span class="math inline">\(f(x)=a\exp\left(-e^{-b(x-c)}\right)\)</span> with <span class="math inline">\(a=24\)</span> mm, <span class="math inline">\(b=0.3\)</span>/month and <span class="math inline">\(c=4\)</span> months. Derive <span class="math inline">\(f'(x)\)</span> and write it in terms of <span class="math inline">\(f(x)\)</span>. Calculate the length and the growth rate of the snail at 4 months.</li>
<li>Derive the partial derivatives of the Ricker function <span class="math inline">\(f(x;a,b)=a\,x\,e^{-bx}\)</span> with respect to <span class="math inline">\(a\)</span> and with respect to <span class="math inline">\(b\)</span>, and calculate both for <span class="math inline">\(a=2\)</span>, <span class="math inline">\(b=0.5\)</span> and <span class="math inline">\(x=2\)</span>. At which value of <span class="math inline">\(x\)</span> does a small change in <span class="math inline">\(b\)</span> move the curve most?</li>
</ol>
<p>When you have finished, check your answers to questions 3 and 5 with <code>D()</code>.</p>
</section>
<section id="exercise-4-special-points" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Exercise 4: Special points</h1>
<p>The special points of a function (a peak, an inflection point, a half-maximum) are what we can read from a plot, so we need them as expressions of the parameters. Do all the questions on paper and give the units of every result. The first three questions are the core of this exercise and the last two are extra practice.</p>
<ol type="1">
<li>For the saturating exponential function <span class="math inline">\(f(x)=a\left(1-e^{-bx}\right)\)</span>, derive the half-maximum <span class="math inline">\(x_{1/2}\)</span>. Then show that the function reaches three quarters of its asymptote at <span class="math inline">\(2x_{1/2}\)</span>. Calculate both times for the nitrogen released from a crop residue in Exercise 2 (<span class="math inline">\(b=0.2\)</span>/week).</li>
<li>The concentration of a pesticide in a soil falls from 8 to 2 mg/kg in 30 days. Assuming an <a href="../../Supplements/deterministic-functions.html#sec-fn-exponential">exponential</a> decay, <span class="math inline">\(f(x)=a\,e^{-bx}\)</span>, find its half-life, the rate <span class="math inline">\(b\)</span> and the characteristic scale <span class="math inline">\(1/b\)</span>, with their units. What is the concentration after one characteristic scale?</li>
<li>The number of adult parasitoids that emerge from a caterpillar as a function of the number of eggs laid in it, <span class="math inline">\(x\)</span>, follows the <a href="../../Supplements/deterministic-functions.html#sec-fn-hassell">Hassell</a> function with an exponent of 2, <span class="math inline">\(f(x)=\dfrac{ax}{(b+x)^2}\)</span>. Derive <span class="math inline">\(f'(x)\)</span> and find the location and the height of the peak as expressions of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. Calculate them for <span class="math inline">\(a=1280\)</span> and <span class="math inline">\(b=40\)</span> eggs. What is the initial slope?</li>
<li>For the Holling type III function <span class="math inline">\(f(x)=\dfrac{ax^2}{b^2+x^2}\)</span>, start from the derivative that you found in Exercise 3 and derive <span class="math inline">\(f''(x)\)</span>. Find the inflection point, and the value and the slope of the function there. Calculate them for the seeds removed by rodents (<span class="math inline">\(a=30\)</span> seeds/night, <span class="math inline">\(b=10\)</span> seeds/m²).</li>
<li>The intake of a herbivore (g/min) as a function of the biomass of the vegetation, <span class="math inline">\(x\)</span> (g/m²), follows the <a href="../../Supplements/deterministic-functions.html#sec-fn-holling4">Holling type IV</a> function <span class="math inline">\(f(x)=\dfrac{ax^2}{b+cx+x^2}\)</span> with <span class="math inline">\(a=12\)</span>, <span class="math inline">\(b=100\)</span> and <span class="math inline">\(c=-10\)</span>. Find the location and the height of the peak, using the fact that a quotient is zero where its numerator is zero. Compare the height of the peak with the limit of the function as <span class="math inline">\(x\to\infty\)</span>.</li>
</ol>
<p>When you have finished, check the peaks of questions 3 and 5 with <code>which.max()</code> on a fine grid of values of <span class="math inline">\(x\)</span>.</p>
</section>
<section id="exercise-5-parameters" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Exercise 5: Parameters</h1>
<p>The same curve can be written with different parameters, and a curve can be moved, stretched and bounded by changing its formula (see <a href="../../Chapter_5/Theory.html#sec-function-parameters">Parameters</a> and <a href="../../Chapter_5/Theory.html#sec-function-building">Building new functions</a> in the theory). Do all the questions on paper and give the units of every parameter. The first three questions are the core of this exercise and the last two are extra practice.</p>
<ol type="1">
<li>A wolf spider searches an area of <span class="math inline">\(\alpha=2\)</span> m²/day for prey and needs <span class="math inline">\(H=0.05\)</span> days to handle each prey. Write its functional response in the Holling type II form, <span class="math inline">\(f(x)=\dfrac{\alpha x}{1+\alpha Hx}\)</span>, where <span class="math inline">\(x\)</span> is the density of prey (prey/m²), and convert it to the Michaelis–Menten form, <span class="math inline">\(f(x)=\dfrac{ax}{b+x}\)</span>. What are <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, and what do they mean? A second species has <span class="math inline">\(a=50\)</span> prey/day and <span class="math inline">\(b=25\)</span> prey/m². What are its <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(H\)</span>?</li>
<li>Rewrite the Ricker function <span class="math inline">\(f(x)=a\,x\,e^{-bx}\)</span> so that its two parameters are the location of the peak, <span class="math inline">\(x_{\max}\)</span>, and the height of the peak, <span class="math inline">\(y_{\max}\)</span>. What are <span class="math inline">\(x_{\max}\)</span> and <span class="math inline">\(y_{\max}\)</span> for <span class="math inline">\(f(x)=8\,x\,e^{-0.25x}\)</span>?</li>
<li>A plant does not flower until it has a mass of 2 g, at which it carries 3 flowers. The number of flowers then increases with the mass of the plant, <span class="math inline">\(x\)</span> (g), and approaches 27 for the heaviest plants. It is halfway between 3 and 27 at a mass of 10 g. Write the formula of a shifted and scaled Michaelis–Menten function with these properties, for <span class="math inline">\(x\ge2\)</span>.</li>
<li>The probability that a plant species occurs at a site as a function of the pH of the soil, <span class="math inline">\(x\)</span>, is described with the composition <span class="math inline">\(f(x)=\operatorname{logit}^{-1}\left[d-b\,(x-c)^2\right]\)</span> with <span class="math inline">\(d=2\)</span>, <span class="math inline">\(b=0.5\)</span> and <span class="math inline">\(c=6\)</span>. What is the range of the function? Where is its peak and how high is it? At which values of the pH is the probability 0.5?</li>
<li>Show that the <a href="../../Supplements/deterministic-functions.html#sec-fn-shepherd">Shepherd</a> function <span class="math inline">\(f(x)=\dfrac{ax}{b+x^c}\)</span> contains the Michaelis–Menten function, and that the <a href="../../Supplements/deterministic-functions.html#sec-fn-richards">Richards</a> function <span class="math inline">\(f(x)=\dfrac{a}{\left[1+d\,e^{-b(x-c)}\right]^{1/d}}\)</span> contains the logistic function. Which function does the Richards function become for <span class="math inline">\(d=-1\)</span>?</li>
</ol>
<p>When you have finished, check your answers to questions 1 and 2 in R by evaluating both forms of each function at a few values of <span class="math inline">\(x\)</span>.</p>
</section>
<section id="exercise-6-enzyme-kinetics" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Exercise 6: Enzyme kinetics</h1>
<p>The data set <code>Puromycin</code> of base R contains the rate of an enzymatic reaction (<code>rate</code>, in counts/min/min) at six concentrations of the substrate (<code>conc</code>, in parts per million, ppm), measured in cells that were treated with the antibiotic puromycin (12 observations) and in untreated cells (11 observations) (Treloar 1974, in Bates and Watts 1988). The column <code>state</code> says to which of the two groups an observation belongs. Load the data with <code>data(Puromycin, package = "datasets")</code>.</p>
<p>This is the kind of experiment for which Michaelis and Menten proposed their function, <span class="math inline">\(f(x)=\dfrac{ax}{b+x}\)</span>, where <span class="math inline">\(x\)</span> is the concentration of the substrate and <span class="math inline">\(f(x)\)</span> is the rate of the reaction (see the <a href="../../Supplements/deterministic-functions.html#sec-fn-michaelis-menten">Michaelis–Menten</a> entry of the supplement). In this exercise you place the curve by eye and compare it with an alternative function.</p>
<ol type="1">
<li>Plot the rate against the concentration, with a different symbol for each state. Read <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> from the plot for each state, with their units, and draw the two curves over the data. Which of the two parameters differs between the states?</li>
<li>On paper, calculate the initial slope of the curve of the treated cells, with its units. The saturating exponential function <span class="math inline">\(g(x)=a\left(1-e^{-b_gx}\right)\)</span> has the same shape as the Michaelis–Menten function. Find the rate <span class="math inline">\(b_g\)</span> for which it has the same asymptote and the same initial slope as the curve of the treated cells. Which fraction of the asymptote does each function reach at <span class="math inline">\(x=b\)</span>? In R, draw both curves and find the concentration at which they differ most.</li>
</ol>
</section>
<section id="exercise-7-choosing-functions-for-fecundity-and-for-recruitment" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Exercise 7: Choosing functions for fecundity and for recruitment</h1>
<p>This exercise uses two data sets of the package <code>emdbook</code>, with a different shape each.</p>
<p><strong>Part A.</strong> The data set <code>FirDBHFec_sum</code> contains the diameter at breast height (<code>DBH</code>, in cm) and the fecundity (<code>fecundity</code>) of 333 balsam fir trees (<em>Abies balsamea</em>) on Whiteface Mountain, New York (Silvertown and Dodd 1999; Dodd and Silvertown 2000). Fecundity was measured as the number of cone rachises on a tree: the rachis is the axis of a cone, which stays on the branch after the cone has fallen apart. Load the data with <code>data(FirDBHFec_sum, package = "emdbook")</code>.</p>
<ol type="1">
<li>The diameter of some trees is missing. Count those trees and remove them explicitly. Plot fecundity against diameter and describe the shape of the relationship.</li>
<li>On paper, explain why a <a href="../../Supplements/deterministic-functions.html#sec-fn-power">power law</a>, <span class="math inline">\(f(x)=ax^b\)</span>, is a candidate for these data. Read two points from the curve that you would draw through the middle of the cloud and calculate <span class="math inline">\(b\)</span> and <span class="math inline">\(a\)</span> from them. What are the units of <span class="math inline">\(a\)</span>? Draw the curve over the data.</li>
<li>On paper, calculate by which factor the fecundity changes when the diameter doubles. Which measure of the size of a tree is proportional to the square of its diameter?</li>
</ol>
<p><strong>Part B.</strong> The data set <code>DamselRecruitment_sum</code> comes from a field experiment with the three-spot damselfish <em>Dascyllus trimaculatus</em>, whose larvae settle on sea anemones (Schmitt, Holbrook and Osenberg 1999). Each of the 11 rows is a target density of settlers: <code>settler.den</code> is the density of settlers and <code>surv.den</code> is the mean density of survivors after six months, both as the number of fish per 0.1 m² of anemone. Load the data with <code>data(DamselRecruitment_sum, package = "emdbook")</code>.</p>
<ol start="4" type="1">
<li>Plot the density of survivors against the density of settlers. Read starting values for a Michaelis–Menten function from the plot, with their units, and draw the curve. Compare its initial slope with the fraction of the settlers that survived at the lowest densities.</li>
<li>Write a <a href="../../Supplements/deterministic-functions.html#sec-fn-hockey-stick">hockey stick</a> function with <code>ifelse()</code>, choose its two parameters by eye and add it to the plot. Where does it describe the data differently from the Michaelis–Menten function?</li>
<li>The <a href="../../Supplements/deterministic-functions.html#sec-fn-shepherd">Shepherd</a> function can be written as <span class="math inline">\(f(x)=\dfrac{sx}{1+(x/k)^c}\)</span>, where <span class="math inline">\(s\)</span> is the initial slope, <span class="math inline">\(k\)</span> is a scale parameter and <span class="math inline">\(c\)</span> is an exponent. Write it in R, give <span class="math inline">\(s\)</span> and <span class="math inline">\(k\)</span> the values that correspond to your Michaelis–Menten function, and draw it for <span class="math inline">\(c=0.8\)</span>, <span class="math inline">\(c=1\)</span> and <span class="math inline">\(c=1.2\)</span>. What does <span class="math inline">\(c\)</span> change, and which part of the data can tell us about it?</li>
<li>Which of the three functions are nested? What would you need in order to choose among them?</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>