<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-10-07">

<title>Ecological Models and Data Analysis – Chapter 5: Deterministic functions in ecology — solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../Chapter_1/Practicals/solution.html">Solutions</a></li><li class="breadcrumb-item"><a href="../../Chapter_5/Practicals/solution.html">Chapter 5</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Ecological Models and Data Analysis</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Theory</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_1/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_2/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_3/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_4/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_5/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Practicals</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_1/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_2/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_3/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_4/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_5/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Solutions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_1/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_2/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_3/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_4/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_5/Practicals/solution.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Chapter 5</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplements</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/deterministic-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deterministic functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculus refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/canned.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Formula-based methods</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercise-2-limits-and-end-behaviour" id="toc-exercise-2-limits-and-end-behaviour" class="nav-link active" data-scroll-target="#exercise-2-limits-and-end-behaviour"><span class="header-section-number">1</span> Exercise 2: Limits and end behaviour</a>
  <ul class="collapse">
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution"><span class="header-section-number">1.1</span> Solution</a>
  <ul class="collapse">
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1"><span class="header-section-number">1.1.1</span> Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2"><span class="header-section-number">1.1.2</span> Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3"><span class="header-section-number">1.1.3</span> Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4"><span class="header-section-number">1.1.4</span> Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5"><span class="header-section-number">1.1.5</span> Question 5</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercise-3-derivatives-and-slopes" id="toc-exercise-3-derivatives-and-slopes" class="nav-link" data-scroll-target="#exercise-3-derivatives-and-slopes"><span class="header-section-number">2</span> Exercise 3: Derivatives and slopes</a>
  <ul class="collapse">
  <li><a href="#solution-1" id="toc-solution-1" class="nav-link" data-scroll-target="#solution-1"><span class="header-section-number">2.1</span> Solution</a>
  <ul class="collapse">
  <li><a href="#question-1-1" id="toc-question-1-1" class="nav-link" data-scroll-target="#question-1-1"><span class="header-section-number">2.1.1</span> Question 1</a></li>
  <li><a href="#question-2-1" id="toc-question-2-1" class="nav-link" data-scroll-target="#question-2-1"><span class="header-section-number">2.1.2</span> Question 2</a></li>
  <li><a href="#question-3-1" id="toc-question-3-1" class="nav-link" data-scroll-target="#question-3-1"><span class="header-section-number">2.1.3</span> Question 3</a></li>
  <li><a href="#question-4-1" id="toc-question-4-1" class="nav-link" data-scroll-target="#question-4-1"><span class="header-section-number">2.1.4</span> Question 4</a></li>
  <li><a href="#question-5-1" id="toc-question-5-1" class="nav-link" data-scroll-target="#question-5-1"><span class="header-section-number">2.1.5</span> Question 5</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercise-4-special-points" id="toc-exercise-4-special-points" class="nav-link" data-scroll-target="#exercise-4-special-points"><span class="header-section-number">3</span> Exercise 4: Special points</a>
  <ul class="collapse">
  <li><a href="#solution-2" id="toc-solution-2" class="nav-link" data-scroll-target="#solution-2"><span class="header-section-number">3.1</span> Solution</a>
  <ul class="collapse">
  <li><a href="#question-1-2" id="toc-question-1-2" class="nav-link" data-scroll-target="#question-1-2"><span class="header-section-number">3.1.1</span> Question 1</a></li>
  <li><a href="#question-2-2" id="toc-question-2-2" class="nav-link" data-scroll-target="#question-2-2"><span class="header-section-number">3.1.2</span> Question 2</a></li>
  <li><a href="#question-3-2" id="toc-question-3-2" class="nav-link" data-scroll-target="#question-3-2"><span class="header-section-number">3.1.3</span> Question 3</a></li>
  <li><a href="#question-4-2" id="toc-question-4-2" class="nav-link" data-scroll-target="#question-4-2"><span class="header-section-number">3.1.4</span> Question 4</a></li>
  <li><a href="#question-5-2" id="toc-question-5-2" class="nav-link" data-scroll-target="#question-5-2"><span class="header-section-number">3.1.5</span> Question 5</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercise-5-parameters" id="toc-exercise-5-parameters" class="nav-link" data-scroll-target="#exercise-5-parameters"><span class="header-section-number">4</span> Exercise 5: Parameters</a>
  <ul class="collapse">
  <li><a href="#solution-3" id="toc-solution-3" class="nav-link" data-scroll-target="#solution-3"><span class="header-section-number">4.1</span> Solution</a>
  <ul class="collapse">
  <li><a href="#question-1-3" id="toc-question-1-3" class="nav-link" data-scroll-target="#question-1-3"><span class="header-section-number">4.1.1</span> Question 1</a></li>
  <li><a href="#question-2-3" id="toc-question-2-3" class="nav-link" data-scroll-target="#question-2-3"><span class="header-section-number">4.1.2</span> Question 2</a></li>
  <li><a href="#question-3-3" id="toc-question-3-3" class="nav-link" data-scroll-target="#question-3-3"><span class="header-section-number">4.1.3</span> Question 3</a></li>
  <li><a href="#question-4-3" id="toc-question-4-3" class="nav-link" data-scroll-target="#question-4-3"><span class="header-section-number">4.1.4</span> Question 4</a></li>
  <li><a href="#question-5-3" id="toc-question-5-3" class="nav-link" data-scroll-target="#question-5-3"><span class="header-section-number">4.1.5</span> Question 5</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercise-6-enzyme-kinetics" id="toc-exercise-6-enzyme-kinetics" class="nav-link" data-scroll-target="#exercise-6-enzyme-kinetics"><span class="header-section-number">5</span> Exercise 6: Enzyme kinetics</a>
  <ul class="collapse">
  <li><a href="#solution-4" id="toc-solution-4" class="nav-link" data-scroll-target="#solution-4"><span class="header-section-number">5.1</span> Solution</a>
  <ul class="collapse">
  <li><a href="#question-1-4" id="toc-question-1-4" class="nav-link" data-scroll-target="#question-1-4"><span class="header-section-number">5.1.1</span> Question 1</a></li>
  <li><a href="#question-2-4" id="toc-question-2-4" class="nav-link" data-scroll-target="#question-2-4"><span class="header-section-number">5.1.2</span> Question 2</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercise-7-choosing-functions-for-fecundity-and-for-recruitment" id="toc-exercise-7-choosing-functions-for-fecundity-and-for-recruitment" class="nav-link" data-scroll-target="#exercise-7-choosing-functions-for-fecundity-and-for-recruitment"><span class="header-section-number">6</span> Exercise 7: Choosing functions for fecundity and for recruitment</a>
  <ul class="collapse">
  <li><a href="#solution-5" id="toc-solution-5" class="nav-link" data-scroll-target="#solution-5"><span class="header-section-number">6.1</span> Solution</a>
  <ul class="collapse">
  <li><a href="#question-1-5" id="toc-question-1-5" class="nav-link" data-scroll-target="#question-1-5"><span class="header-section-number">6.1.1</span> Question 1</a></li>
  <li><a href="#question-2-5" id="toc-question-2-5" class="nav-link" data-scroll-target="#question-2-5"><span class="header-section-number">6.1.2</span> Question 2</a></li>
  <li><a href="#question-3-4" id="toc-question-3-4" class="nav-link" data-scroll-target="#question-3-4"><span class="header-section-number">6.1.3</span> Question 3</a></li>
  <li><a href="#question-4-4" id="toc-question-4-4" class="nav-link" data-scroll-target="#question-4-4"><span class="header-section-number">6.1.4</span> Question 4</a></li>
  <li><a href="#question-5-4" id="toc-question-5-4" class="nav-link" data-scroll-target="#question-5-4"><span class="header-section-number">6.1.5</span> Question 5</a></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6"><span class="header-section-number">6.1.6</span> Question 6</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7"><span class="header-section-number">6.1.7</span> Question 7</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../Chapter_1/Practicals/solution.html">Solutions</a></li><li class="breadcrumb-item"><a href="../../Chapter_5/Practicals/solution.html">Chapter 5</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Chapter 5: Deterministic functions in ecology — solutions</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>The fully worked first exercise is on the <a href="../../Chapter_5/Practicals/no_solution.html">student practical page</a>. These solutions use the same data and tasks as Exercises 2–7 on that page. The answers to the questions on paper are followed by a check in R where one is possible.</p>
<section id="exercise-2-limits-and-end-behaviour" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Exercise 2: Limits and end behaviour</h1>
<p>The first thing to find out about a function is where it starts and where it ends. For each of the five functions below:</p>
<ul>
<li>on paper, calculate the value of the function at the lower end of its domain and its limit as <span class="math inline">\(x\to\infty\)</span>, with their units;</li>
<li>on paper, find the simpler function that it resembles close to the lower end of its domain;</li>
<li>sketch the function by hand, and only then draw it with <code>curve()</code> to check your sketch.</li>
</ul>
<p>The first three questions are the core of this exercise and the last two are extra practice. The entries of the supplement that you need are the <a href="../../Supplements/deterministic-functions.html#sec-fn-hyperbolic">hyperbolic</a>, <a href="../../Supplements/deterministic-functions.html#sec-fn-monomolecular">saturating exponential</a>, <a href="../../Supplements/deterministic-functions.html#sec-fn-holling3">Holling type III</a> and <a href="../../Supplements/deterministic-functions.html#sec-fn-michaelis-menten">Michaelis–Menten</a> functions.</p>
<ol type="1">
<li>The mean mass of a seedling (mg) as a function of the number of seedlings in a pot, <span class="math inline">\(x\)</span>: <span class="math inline">\(f(x)=\dfrac{480}{12+x}\)</span>.</li>
<li>The amount of nitrogen released from a crop residue (kg/ha) as a function of the time since it was ploughed in, <span class="math inline">\(x\)</span> (weeks): <span class="math inline">\(f(x)=90\left(1-e^{-0.2x}\right)\)</span>.</li>
<li>The number of seeds removed by rodents in one night as a function of the density of seeds, <span class="math inline">\(x\)</span> (seeds/m²): <span class="math inline">\(f(x)=\dfrac{30x^2}{100+x^2}\)</span>.</li>
<li>The number of eggs in the clutch of an insect as a function of the body mass of the female, <span class="math inline">\(x\)</span> (mg), for <span class="math inline">\(x\ge5\)</span>: <span class="math inline">\(f(x)=2+\dfrac{10\,(x-5)}{15+(x-5)}\)</span>.</li>
<li>A function in which a power and an exponential compete, for <span class="math inline">\(x\ge0\)</span>: <span class="math inline">\(f(x)=0.5\,x^2e^{-0.4x}\)</span>. Compare its behaviour close to zero with that of a Ricker function.</li>
</ol>
<section id="solution" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="solution"><span class="header-section-number">1.1</span> Solution</h2>
<section id="question-1" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="question-1"><span class="header-section-number">1.1.1</span> Question 1</h3>
<p>At <span class="math inline">\(x=0\)</span> the function is <span class="math inline">\(f(0)=480/12=40\)</span> mg, the mass of a seedling that grows alone. As <span class="math inline">\(x\to\infty\)</span> the numerator stays at 480 while the denominator grows without bound, so <span class="math inline">\(f(x)\to0\)</span>: the function is a hyperbolic decline from <span class="math inline">\(a/b\)</span> to zero. The parameter <span class="math inline">\(b=12\)</span> is added to <span class="math inline">\(x\)</span>, so it is a number of seedlings per pot, and <span class="math inline">\(a=480\)</span> has the units of <span class="math inline">\(y\)</span> times those of <span class="math inline">\(x\)</span> (mg times seedlings per pot).</p>
<p>Close to zero, where <span class="math inline">\(x\ll12\)</span>, the denominator is almost 12 and the function stays close to 40 mg. Far from zero, where <span class="math inline">\(x\gg12\)</span>, the denominator is almost <span class="math inline">\(x\)</span> and <span class="math inline">\(f(x)\approx480/x\)</span>, so the mass of a seedling is inversely proportional to the number of seedlings. Between the two, at <span class="math inline">\(x=12\)</span>, the function has halved, <span class="math inline">\(f(12)=480/24=20\)</span> mg. A sketch therefore starts at 40, passes through 20 at <span class="math inline">\(x=12\)</span> and flattens towards zero.</p>
</section>
<section id="question-2" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="question-2"><span class="header-section-number">1.1.2</span> Question 2</h3>
<p>At <span class="math inline">\(x=0\)</span> we have <span class="math inline">\(e^{0}=1\)</span>, so <span class="math inline">\(f(0)=90\,(1-1)=0\)</span>. As <span class="math inline">\(x\to\infty\)</span> the exponential <span class="math inline">\(e^{-0.2x}\)</span> goes to zero and <span class="math inline">\(f(x)\to90\)</span> kg/ha, which is the amount of nitrogen that the residue can release. So <span class="math inline">\(a=90\)</span> has the units of <span class="math inline">\(y\)</span>, and <span class="math inline">\(b=0.2\)</span> multiplies <span class="math inline">\(x\)</span> inside an exponential, so it is a rate, with units 1/week.</p>
<p>For a small argument the exponential is close to its tangent line at zero, <span class="math inline">\(e^{-u}\approx1-u\)</span>. With <span class="math inline">\(u=0.2x\)</span>,</p>
<p><span class="math display">\[
f(x)\approx90\,\bigl(1-(1-0.2x)\bigr)=90\times0.2\,x=18\,x,
\]</span></p>
<p>so close to zero the function is a straight line through the origin with a slope of <span class="math inline">\(ab=18\)</span> kg/ha/week. The sketch starts along that line and bends towards the horizontal line at 90.</p>
</section>
<section id="question-3" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="question-3"><span class="header-section-number">1.1.3</span> Question 3</h3>
<p>At <span class="math inline">\(x=0\)</span> the numerator is zero, so <span class="math inline">\(f(0)=0\)</span>. For the limit we divide the numerator and the denominator by the highest power, <span class="math inline">\(x^2\)</span>:</p>
<p><span class="math display">\[
\lim_{x\to\infty}\frac{30x^2}{100+x^2}
=\lim_{x\to\infty}\frac{30}{100/x^2+1}=30.
\]</span></p>
<p>So the function saturates at <span class="math inline">\(a=30\)</span> seeds/night. Close to zero, where <span class="math inline">\(x^2\ll100\)</span>, the denominator is almost 100 and <span class="math inline">\(f(x)\approx30x^2/100=0.3\,x^2\)</span>. This is a parabola, which has a slope of zero at the origin and becomes steeper as <span class="math inline">\(x\)</span> increases. The Michaelis–Menten function starts as a straight line, <span class="math inline">\((a/b)\,x\)</span>. That is the difference between the two functions: the Holling type III function starts flat, accelerates and then saturates, so it is sigmoid. The rodents remove almost no seeds when seeds are scarce. Note that the formula contains <span class="math inline">\(b^2=100\)</span>, so <span class="math inline">\(b=10\)</span> seeds/m², and <span class="math inline">\(f(10)=30\times100/200=15\)</span>, half of the asymptote.</p>
</section>
<section id="question-4" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="question-4"><span class="header-section-number">1.1.4</span> Question 4</h3>
<p>The domain starts at <span class="math inline">\(x=5\)</span> mg, where the fraction is zero and <span class="math inline">\(f(5)=2\)</span> eggs. As <span class="math inline">\(x\to\infty\)</span> the fraction is a Michaelis–Menten function of <span class="math inline">\(x-5\)</span> and goes to 10, so <span class="math inline">\(f(x)\to2+10=12\)</span> eggs. In the notation of the theory, the function is shifted by <span class="math inline">\(c=5\)</span> mg along the <span class="math inline">\(x\)</span> axis and by <span class="math inline">\(d=2\)</span> eggs along the <span class="math inline">\(y\)</span> axis, with <span class="math inline">\(a=10\)</span> eggs and <span class="math inline">\(b=15\)</span> mg.</p>
<p>Close to the lower end, where <span class="math inline">\(x-5\ll15\)</span>, the denominator is almost 15 and</p>
<p><span class="math display">\[
f(x)\approx2+\frac{10}{15}\,(x-5),
\]</span></p>
<p>a straight line that starts at the point (5, 2) with a slope of <span class="math inline">\(a/b\approx0.67\)</span> eggs/mg. The function is halfway between 2 and 12, at 7 eggs, when <span class="math inline">\(x-5=b\)</span>, that is, at <span class="math inline">\(x=20\)</span> mg. So the sketch starts at (5, 2), passes through (20, 7) and levels off below 12.</p>
</section>
<section id="question-5" class="level3" data-number="1.1.5">
<h3 data-number="1.1.5" class="anchored" data-anchor-id="question-5"><span class="header-section-number">1.1.5</span> Question 5</h3>
<p>At <span class="math inline">\(x=0\)</span> the function is zero. As <span class="math inline">\(x\to\infty\)</span> the factor <span class="math inline">\(x^2\)</span> grows and <span class="math inline">\(e^{-0.4x}\)</span> decays. The exponential dominates any power, so the limit is zero. With L’Hôpital’s rule, applied twice because the first application still gives <span class="math inline">\(\infty/\infty\)</span>:</p>
<p><span class="math display">\[
\lim_{x\to\infty}\frac{0.5\,x^2}{e^{0.4x}}
=\lim_{x\to\infty}\frac{x}{0.4\,e^{0.4x}}
=\lim_{x\to\infty}\frac{1}{0.16\,e^{0.4x}}=0.
\]</span></p>
<p>Close to zero the exponential is almost one, so <span class="math inline">\(f(x)\approx0.5\,x^2\)</span>: the function starts as a parabola, with a slope of zero. A Ricker function starts as the straight line <span class="math inline">\(ax\)</span>, with a slope of <span class="math inline">\(a\)</span>. So both functions are humps that start and end at zero, but this one rises slowly at first and then accelerates, which the Ricker function cannot do. Since the function is zero at both ends and positive in between, it must have a maximum. The product rule gives <span class="math inline">\(f'(x)=0.5\,x\,(2-0.4x)\,e^{-0.4x}\)</span>, which is zero at <span class="math inline">\(x=2/0.4=5\)</span>.</p>
<p>We can verify our math with R by evaluating each function at the lower end of its domain, close to it and at a very large value of <span class="math inline">\(x\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The five functions of the exercise.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>seedling_mass <span class="ot">=</span> <span class="cf">function</span>(x) <span class="dv">480</span> <span class="sc">/</span> (<span class="dv">12</span> <span class="sc">+</span> x)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>nitrogen <span class="ot">=</span> <span class="cf">function</span>(x) <span class="dv">90</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.2</span> <span class="sc">*</span> x))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>seeds_removed <span class="ot">=</span> <span class="cf">function</span>(x) <span class="dv">30</span> <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (<span class="dv">100</span> <span class="sc">+</span> x<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>clutch <span class="ot">=</span> <span class="cf">function</span>(x) <span class="dv">2</span> <span class="sc">+</span> <span class="dv">10</span> <span class="sc">*</span> (x <span class="sc">-</span> <span class="dv">5</span>) <span class="sc">/</span> (<span class="dv">15</span> <span class="sc">+</span> (x <span class="sc">-</span> <span class="dv">5</span>))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>power_exponential <span class="ot">=</span> <span class="cf">function</span>(x) <span class="fl">0.5</span> <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.4</span> <span class="sc">*</span> x)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Value at the lower end of the domain, close to it, and at a very large x.</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">seedling_mass</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">100000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40.000000000 38.400000000  0.004799424</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nitrogen</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">100000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.000000  8.564632 90.000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seeds_removed</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">100000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.00000000  0.07481297 29.99999970</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clutch</span>(<span class="fu">c</span>(<span class="dv">5</span>, <span class="fl">5.5</span>, <span class="dv">100000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2.000000  2.322581 11.998500</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power_exponential</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">100000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0000000 0.1023413 0.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The approximations close to the lower end, at the same second value.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="dv">18</span> <span class="sc">*</span> <span class="fl">0.5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.3</span> <span class="sc">*</span> <span class="fl">0.5</span><span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.075</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">+</span> <span class="dv">10</span> <span class="sc">/</span> <span class="dv">15</span> <span class="sc">*</span> (<span class="fl">5.5</span> <span class="sc">-</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.333333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.5</span> <span class="sc">*</span> <span class="fl">0.5</span><span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.125</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A quick look at one of the functions; the others are drawn in the same way.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">seeds_removed</span>(x), <span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">60</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="st">"Density of seeds (seeds/m²)"</span>, <span class="at">ylab =</span> <span class="st">"Seeds removed (seeds/night)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="solution_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The values at the ends agree with the limits, and half a unit away from the lower end the approximations are close to the functions (for example, 9 against 8.56 kg/ha for the nitrogen). <a href="#fig-end_behaviour" class="quarto-xref">Figure&nbsp;1</a> shows the five functions.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-end_behaviour" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-end_behaviour-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="solution_files/figure-html/fig-end_behaviour-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-end_behaviour-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The five functions of Exercise 2. Dashed lines mark the asymptotes that are not zero.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="exercise-3-derivatives-and-slopes" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Exercise 3: Derivatives and slopes</h1>
<p>A derivative is the slope of a function, and it has the units of <span class="math inline">\(y\)</span> divided by the units of <span class="math inline">\(x\)</span>. Do all the questions on paper, name the rule that you use at each step (the rules are in the <a href="../../Supplements/calculus.html#sec-calc-rules">calculus refresher</a>), and give the units of every slope. The first three questions are the core of this exercise and the last two are extra practice. Questions 2 and 3 continue with functions of Exercise 2.</p>
<ol type="1">
<li>The body mass of a fish (g) as a function of its length <span class="math inline">\(x\)</span> (cm) follows the <a href="../../Supplements/deterministic-functions.html#sec-fn-power">power law</a> <span class="math inline">\(f(x)=0.01\,x^3\)</span>. Derive <span class="math inline">\(f'(x)\)</span> and calculate the mass and the slope for a fish of 20 cm. What are the units of the parameter 0.01?</li>
<li>For the saturating exponential function <span class="math inline">\(f(x)=a\left(1-e^{-bx}\right)\)</span>, derive <span class="math inline">\(f'(x)\)</span> and show that it can be written as <span class="math inline">\(f'(x)=b\,(a-f(x))\)</span>. What does this say about how the function approaches its asymptote? For the nitrogen released from a crop residue (<span class="math inline">\(a=90\)</span> kg/ha, <span class="math inline">\(b=0.2\)</span>/week), calculate the slope at the start and at the time when half of the nitrogen has been released.</li>
<li>For the Holling type III function <span class="math inline">\(f(x)=\dfrac{ax^2}{b^2+x^2}\)</span>, derive <span class="math inline">\(f'(x)\)</span>. What is the slope at <span class="math inline">\(x=0\)</span>? For the seeds removed by rodents (<span class="math inline">\(a=30\)</span> seeds/night, <span class="math inline">\(b=10\)</span> seeds/m²), calculate the slope at <span class="math inline">\(x=10\)</span> seeds/m².</li>
<li>The shell length of a snail (mm) as a function of its age <span class="math inline">\(x\)</span> (months) follows the <a href="../../Supplements/deterministic-functions.html#sec-fn-gompertz">Gompertz</a> function <span class="math inline">\(f(x)=a\exp\left(-e^{-b(x-c)}\right)\)</span> with <span class="math inline">\(a=24\)</span> mm, <span class="math inline">\(b=0.3\)</span>/month and <span class="math inline">\(c=4\)</span> months. Derive <span class="math inline">\(f'(x)\)</span> and write it in terms of <span class="math inline">\(f(x)\)</span>. Calculate the length and the growth rate of the snail at 4 months.</li>
<li>Derive the partial derivatives of the Ricker function <span class="math inline">\(f(x;a,b)=a\,x\,e^{-bx}\)</span> with respect to <span class="math inline">\(a\)</span> and with respect to <span class="math inline">\(b\)</span>, and calculate both for <span class="math inline">\(a=2\)</span>, <span class="math inline">\(b=0.5\)</span> and <span class="math inline">\(x=2\)</span>. At which value of <span class="math inline">\(x\)</span> does a small change in <span class="math inline">\(b\)</span> move the curve most?</li>
</ol>
<p>When you have finished, check your answers to questions 3 and 5 with <code>D()</code>.</p>
<section id="solution-1" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="solution-1"><span class="header-section-number">2.1</span> Solution</h2>
<section id="question-1-1" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="question-1-1"><span class="header-section-number">2.1.1</span> Question 1</h3>
<p>The constant multiple rule keeps the factor 0.01 and the power rule turns <span class="math inline">\(x^3\)</span> into <span class="math inline">\(3x^2\)</span>:</p>
<p><span class="math display">\[
f'(x)=0.01\times3\,x^{2}=0.03\,x^2.
\]</span></p>
<p>A fish of 20 cm has a mass of <span class="math inline">\(f(20)=0.01\times8000=80\)</span> g, and the slope there is <span class="math inline">\(f'(20)=0.03\times400=12\)</span> g/cm. That is, a fish that is one cm longer than 20 cm is about 12 g heavier. The parameter 0.01 multiplies a volume in cm³ and the result is a mass in g, so its units are g/cm³.</p>
</section>
<section id="question-2-1" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="question-2-1"><span class="header-section-number">2.1.2</span> Question 2</h3>
<p>We write the function as <span class="math inline">\(f(x)=a-a\,e^{-bx}\)</span>. By the sum rule we differentiate the two terms separately. The derivative of the constant <span class="math inline">\(a\)</span> is zero, and the rule for the exponential gives the derivative of <span class="math inline">\(e^{-bx}\)</span> as <span class="math inline">\(-b\,e^{-bx}\)</span>, so</p>
<p><span class="math display">\[
f'(x)=0-a\times(-b)\,e^{-bx}=ab\,e^{-bx}.
\]</span></p>
<p>From the formula of the function, <span class="math inline">\(a\,e^{-bx}=a-f(x)\)</span>, and therefore</p>
<p><span class="math display">\[
f'(x)=b\,\bigl(a-f(x)\bigr).
\]</span></p>
<p>In plain English, the slope is proportional to the distance that remains to the asymptote. The function closes a constant fraction of that distance per unit of <span class="math inline">\(x\)</span>, so it slows down as it approaches the asymptote and never reaches it.</p>
<p>At the start nothing has been released, <span class="math inline">\(f(0)=0\)</span>, and the slope is <span class="math inline">\(ab=0.2\times90=18\)</span> kg/ha/week, the slope of the straight line of Exercise 2. When half of the nitrogen has been released, <span class="math inline">\(f(x)=45\)</span> kg/ha and the slope is <span class="math inline">\(0.2\times(90-45)=9\)</span> kg/ha/week, half of the initial slope.</p>
</section>
<section id="question-3-1" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="question-3-1"><span class="header-section-number">2.1.3</span> Question 3</h3>
<p>The function is a quotient of <span class="math inline">\(g(x)=ax^2\)</span> and <span class="math inline">\(h(x)=b^2+x^2\)</span>, with <span class="math inline">\(g'(x)=2ax\)</span> and <span class="math inline">\(h'(x)=2x\)</span> by the power rule. The quotient rule gives</p>
<p><span class="math display">\[
\begin{aligned}
f'(x) &amp;= \frac{g'(x)\,h(x)-g(x)\,h'(x)}{h(x)^2}\\
&amp;= \frac{2ax\,(b^2+x^2)-ax^2\times2x}{(b^2+x^2)^2}\\
&amp;= \frac{2ab^2x}{(b^2+x^2)^2}.
\end{aligned}
\]</span></p>
<p>At <span class="math inline">\(x=0\)</span> the numerator is zero, so the slope is zero: the function starts flat, as the parabola of Exercise 2 showed. At <span class="math inline">\(x=b\)</span> the slope is <span class="math inline">\(2ab^3/(2b^2)^2=a/(2b)\)</span>. For the rodents this is <span class="math inline">\(30/20=1.5\)</span> (seeds/night)/(seeds/m²): at a density of 10 seeds/m², one more seed per m² adds one and a half seeds to the number removed in a night.</p>
</section>
<section id="question-4-1" class="level3" data-number="2.1.4">
<h3 data-number="2.1.4" class="anchored" data-anchor-id="question-4-1"><span class="header-section-number">2.1.4</span> Question 4</h3>
<p>The function is a chain of three functions, so we apply the chain rule twice. Write <span class="math inline">\(f(x)=a\,e^{u}\)</span> with <span class="math inline">\(u=-e^{v}\)</span> and <span class="math inline">\(v=-b\,(x-c)\)</span>. Then</p>
<p><span class="math display">\[
\begin{aligned}
\frac{dv}{dx} &amp;= -b,\\
\frac{du}{dx} &amp;= -e^{v}\,\frac{dv}{dx}=b\,e^{-b(x-c)},\\
f'(x) &amp;= a\,e^{u}\,\frac{du}{dx}
= b\,e^{-b(x-c)}\;a\exp\left(-e^{-b(x-c)}\right)
= b\,e^{-b(x-c)}\,f(x).
\end{aligned}
\]</span></p>
<p>At <span class="math inline">\(x=c\)</span> the inner exponential is <span class="math inline">\(e^{0}=1\)</span>. So the length of the snail at 4 months is <span class="math inline">\(f(4)=a\,e^{-1}=24/2.718\approx8.83\)</span> mm, and its growth rate is <span class="math inline">\(f'(4)=b\,f(4)=0.3\times8.83\approx2.65\)</span> mm/month.</p>
</section>
<section id="question-5-1" class="level3" data-number="2.1.5">
<h3 data-number="2.1.5" class="anchored" data-anchor-id="question-5-1"><span class="header-section-number">2.1.5</span> Question 5</h3>
<p>For a partial derivative we treat <span class="math inline">\(x\)</span> and the other parameter as constants. The parameter <span class="math inline">\(a\)</span> multiplies the rest of the formula, so by the constant multiple rule</p>
<p><span class="math display">\[
\frac{\partial f}{\partial a}=x\,e^{-bx}.
\]</span></p>
<p>For <span class="math inline">\(b\)</span> we need the rule for the exponential, where now <span class="math inline">\(b\)</span> is the variable and <span class="math inline">\(-x\)</span> is the constant that multiplies it:</p>
<p><span class="math display">\[
\frac{\partial f}{\partial b}=a\,x\times(-x)\,e^{-bx}=-a\,x^2e^{-bx}.
\]</span></p>
<p>For <span class="math inline">\(a=2\)</span>, <span class="math inline">\(b=0.5\)</span> and <span class="math inline">\(x=2\)</span> we have <span class="math inline">\(e^{-bx}=e^{-1}\approx0.368\)</span>, so <span class="math inline">\(\partial f/\partial a=2\times0.368\approx0.74\)</span> and <span class="math inline">\(\partial f/\partial b=-2\times4\times0.368\approx-2.94\)</span>. The derivative with respect to <span class="math inline">\(b\)</span> is negative for every <span class="math inline">\(x&gt;0\)</span>: a larger <span class="math inline">\(b\)</span> lowers the whole curve.</p>
<p>A small change in <span class="math inline">\(b\)</span> moves the curve most where <span class="math inline">\(x^2e^{-bx}\)</span> is largest. This is again a function of <span class="math inline">\(x\)</span> with a maximum, which we find with the product rule:</p>
<p><span class="math display">\[
\frac{d}{dx}\left(x^2e^{-bx}\right)=2x\,e^{-bx}-b\,x^2e^{-bx}=x\,(2-bx)\,e^{-bx}=0
\quad\Longrightarrow\quad x=\frac{2}{b}.
\]</span></p>
<p>So the curve is most sensitive to <span class="math inline">\(b\)</span> at <span class="math inline">\(x=2/b\)</span> (here <span class="math inline">\(x=4\)</span>), which is the inflection point of the Ricker function, on its way down. The parameter <span class="math inline">\(a\)</span> moves the curve most at the peak, <span class="math inline">\(x=1/b\)</span>, where <span class="math inline">\(x\,e^{-bx}\)</span> is largest. We will come back to this in <a href="../../Chapter_6/Theory.qmd">Chapter 6</a>: the observations that tell us most about a parameter are the ones taken where the curve responds most to it.</p>
<p>We can verify our math with R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Question 3: derivative of the Holling type III function with D(), and the formulas</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># derived on paper, 2 * a * b^2 * x / (b^2 + x^2)^2 and a / (2 * b) at x = b.</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>holling_3_derivative <span class="ot">=</span> <span class="fu">D</span>(<span class="fu">expression</span>(a <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (b<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> x<span class="sc">^</span><span class="dv">2</span>)), <span class="st">"x"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">eval</span>(holling_3_derivative, <span class="fu">list</span>(<span class="at">a =</span> <span class="dv">30</span>, <span class="at">b =</span> <span class="dv">10</span>, <span class="at">x =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="dv">30</span> <span class="sc">*</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="dv">10</span> <span class="sc">/</span> (<span class="dv">10</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">2</span>)<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="dv">30</span> <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Question 5: partial derivatives of the Ricker function with respect to a and to b.</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>ricker_da <span class="ot">=</span> <span class="fu">D</span>(<span class="fu">expression</span>(a <span class="sc">*</span> x <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>b <span class="sc">*</span> x)), <span class="st">"a"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>ricker_db <span class="ot">=</span> <span class="fu">D</span>(<span class="fu">expression</span>(a <span class="sc">*</span> x <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>b <span class="sc">*</span> x)), <span class="st">"b"</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">eval</span>(ricker_da, <span class="fu">list</span>(<span class="at">a =</span> <span class="dv">2</span>, <span class="at">b =</span> <span class="fl">0.5</span>, <span class="at">x =</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7357589</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eval</span>(ricker_db, <span class="fu">list</span>(<span class="at">a =</span> <span class="dv">2</span>, <span class="at">b =</span> <span class="fl">0.5</span>, <span class="at">x =</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.943036</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The formulas derived on paper.</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.5</span> <span class="sc">*</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7357589</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="dv">2</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.5</span> <span class="sc">*</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.943036</code></pre>
</div>
</div>
<p><code>D()</code> returns the same values as the formulas: 1.5 for the slope of the Holling type III function, and 0.74 and <span class="math inline">\(-2.94\)</span> for the two partial derivatives.</p>
</section>
</section>
</section>
<section id="exercise-4-special-points" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Exercise 4: Special points</h1>
<p>The special points of a function (a peak, an inflection point, a half-maximum) are what we can read from a plot, so we need them as expressions of the parameters. Do all the questions on paper and give the units of every result. The first three questions are the core of this exercise and the last two are extra practice.</p>
<ol type="1">
<li>For the saturating exponential function <span class="math inline">\(f(x)=a\left(1-e^{-bx}\right)\)</span>, derive the half-maximum <span class="math inline">\(x_{1/2}\)</span>. Then show that the function reaches three quarters of its asymptote at <span class="math inline">\(2x_{1/2}\)</span>. Calculate both times for the nitrogen released from a crop residue in Exercise 2 (<span class="math inline">\(b=0.2\)</span>/week).</li>
<li>The concentration of a pesticide in a soil falls from 8 to 2 mg/kg in 30 days. Assuming an <a href="../../Supplements/deterministic-functions.html#sec-fn-exponential">exponential</a> decay, <span class="math inline">\(f(x)=a\,e^{-bx}\)</span>, find its half-life, the rate <span class="math inline">\(b\)</span> and the characteristic scale <span class="math inline">\(1/b\)</span>, with their units. What is the concentration after one characteristic scale?</li>
<li>The number of adult parasitoids that emerge from a caterpillar as a function of the number of eggs laid in it, <span class="math inline">\(x\)</span>, follows the <a href="../../Supplements/deterministic-functions.html#sec-fn-hassell">Hassell</a> function with an exponent of 2, <span class="math inline">\(f(x)=\dfrac{ax}{(b+x)^2}\)</span>. Derive <span class="math inline">\(f'(x)\)</span> and find the location and the height of the peak as expressions of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. Calculate them for <span class="math inline">\(a=1280\)</span> and <span class="math inline">\(b=40\)</span> eggs. What is the initial slope?</li>
<li>For the Holling type III function <span class="math inline">\(f(x)=\dfrac{ax^2}{b^2+x^2}\)</span>, start from the derivative that you found in Exercise 3 and derive <span class="math inline">\(f''(x)\)</span>. Find the inflection point, and the value and the slope of the function there. Calculate them for the seeds removed by rodents (<span class="math inline">\(a=30\)</span> seeds/night, <span class="math inline">\(b=10\)</span> seeds/m²).</li>
<li>The intake of a herbivore (g/min) as a function of the biomass of the vegetation, <span class="math inline">\(x\)</span> (g/m²), follows the <a href="../../Supplements/deterministic-functions.html#sec-fn-holling4">Holling type IV</a> function <span class="math inline">\(f(x)=\dfrac{ax^2}{b+cx+x^2}\)</span> with <span class="math inline">\(a=12\)</span>, <span class="math inline">\(b=100\)</span> and <span class="math inline">\(c=-10\)</span>. Find the location and the height of the peak, using the fact that a quotient is zero where its numerator is zero. Compare the height of the peak with the limit of the function as <span class="math inline">\(x\to\infty\)</span>.</li>
</ol>
<p>When you have finished, check the peaks of questions 3 and 5 with <code>which.max()</code> on a fine grid of values of <span class="math inline">\(x\)</span>.</p>
<section id="solution-2" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="solution-2"><span class="header-section-number">3.1</span> Solution</h2>
<section id="question-1-2" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="question-1-2"><span class="header-section-number">3.1.1</span> Question 1</h3>
<p>The half-maximum is the value of <span class="math inline">\(x\)</span> at which the function equals half of its asymptote <span class="math inline">\(a\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
a\left(1-e^{-bx_{1/2}}\right) &amp;= \frac{a}{2}\\
e^{-bx_{1/2}} &amp;= \frac{1}{2}\\
-b\,x_{1/2} &amp;= \log\frac{1}{2}=-\log2\\
x_{1/2} &amp;= \frac{\log2}{b}.
\end{aligned}
\]</span></p>
<p>At twice that value, <span class="math inline">\(e^{-2bx_{1/2}}=\left(e^{-bx_{1/2}}\right)^2=1/4\)</span>, so <span class="math inline">\(f(2x_{1/2})=a\,(1-1/4)=3a/4\)</span>. That is, every interval of length <span class="math inline">\(x_{1/2}\)</span> halves the distance that remains to the asymptote, in the same way as every half-life halves an exponential decay. For the crop residue, <span class="math inline">\(x_{1/2}=0.693/0.2\approx3.5\)</span> weeks: half of the nitrogen (45 kg/ha) has been released after three and a half weeks and three quarters (67.5 kg/ha) after 6.9 weeks. Note that the half-maximum is a time, read on the <span class="math inline">\(x\)</span> axis, and that it depends only on <span class="math inline">\(b\)</span>.</p>
</section>
<section id="question-2-2" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="question-2-2"><span class="header-section-number">3.1.2</span> Question 2</h3>
<p>The concentration falls from 8 to 2 mg/kg, that is, to a quarter. A quarter is two successive halvings, so 30 days are two half-lives and the half-life is 15 days. The half-life of an exponential decay is <span class="math inline">\(\log2/b\)</span>, so</p>
<p><span class="math display">\[
b=\frac{\log2}{15}\approx0.046 \text{/day}, \qquad
\frac{1}{b}=\frac{15}{\log2}\approx21.6 \text{ days}.
\]</span></p>
<p>The characteristic scale <span class="math inline">\(1/b\)</span> is the time over which the concentration falls by a factor <span class="math inline">\(e\)</span>: after 21.6 days it is <span class="math inline">\(8/e\approx2.94\)</span> mg/kg. It is longer than the half-life because a factor <span class="math inline">\(e\approx2.72\)</span> is a larger reduction than a factor 2. The parameter <span class="math inline">\(a=8\)</span> mg/kg is the concentration at the start.</p>
</section>
<section id="question-3-2" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="question-3-2"><span class="header-section-number">3.1.3</span> Question 3</h3>
<p>The function is a quotient of <span class="math inline">\(g(x)=ax\)</span> and <span class="math inline">\(h(x)=(b+x)^2\)</span>, with <span class="math inline">\(g'(x)=a\)</span> and, by the power rule and the chain rule, <span class="math inline">\(h'(x)=2\,(b+x)\)</span>. The quotient rule gives</p>
<p><span class="math display">\[
\begin{aligned}
f'(x) &amp;= \frac{a\,(b+x)^2-2ax\,(b+x)}{(b+x)^4}\\
&amp;= \frac{a\,(b+x)\,(b+x-2x)}{(b+x)^4}\\
&amp;= \frac{a\,(b-x)}{(b+x)^3}.
\end{aligned}
\]</span></p>
<p>The derivative is zero where its numerator is zero, at <span class="math inline">\(x=b\)</span>. It is positive for <span class="math inline">\(x&lt;b\)</span> and negative for <span class="math inline">\(x&gt;b\)</span>, so this is a maximum:</p>
<p><span class="math display">\[
x_{\max}=b, \qquad f(x_{\max})=\frac{ab}{(2b)^2}=\frac{a}{4b}.
\]</span></p>
<p>For the parasitoids the peak is at 40 eggs, with <span class="math inline">\(1280/160=8\)</span> adults. With more than 40 eggs in a caterpillar, fewer adults emerge. The initial slope is <span class="math inline">\(f'(0)=ab/b^3=a/b^2\)</span>, here <span class="math inline">\(1280/1600=0.8\)</span> adults per egg: when there are few eggs, four out of five become adults. The parameter <span class="math inline">\(b\)</span> has the units of <span class="math inline">\(x\)</span> (eggs), and the initial slope shows that <span class="math inline">\(a\)</span> has the units of <span class="math inline">\(y\)</span> times those of <span class="math inline">\(x\)</span>.</p>
</section>
<section id="question-4-2" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="question-4-2"><span class="header-section-number">3.1.4</span> Question 4</h3>
<p>In Exercise 3 we found <span class="math inline">\(f'(x)=2ab^2x/(b^2+x^2)^2\)</span>. This is a quotient of <span class="math inline">\(g(x)=2ab^2x\)</span> and <span class="math inline">\(h(x)=(b^2+x^2)^2\)</span>, with <span class="math inline">\(g'(x)=2ab^2\)</span> and, by the chain rule, <span class="math inline">\(h'(x)=4x\,(b^2+x^2)\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
f''(x) &amp;= \frac{2ab^2\,(b^2+x^2)^2-2ab^2x\times4x\,(b^2+x^2)}{(b^2+x^2)^4}\\
&amp;= \frac{2ab^2\,(b^2+x^2-4x^2)}{(b^2+x^2)^3}\\
&amp;= \frac{2ab^2\,(b^2-3x^2)}{(b^2+x^2)^3}.
\end{aligned}
\]</span></p>
<p>The second derivative is zero where <span class="math inline">\(b^2-3x^2=0\)</span>, that is, at <span class="math inline">\(x=b/\sqrt3\)</span>. It is positive below that value (the function is convex) and negative above it (the function is concave), so this is the inflection point, where the function is steepest. Substituting <span class="math inline">\(x^2=b^2/3\)</span> in the function and in its derivative:</p>
<p><span class="math display">\[
f\!\left(\frac{b}{\sqrt3}\right)=\frac{a\,b^2/3}{b^2+b^2/3}=\frac{a}{4}, \qquad
f'\!\left(\frac{b}{\sqrt3}\right)=\frac{2ab^3/\sqrt3}{(4b^2/3)^2}
=\frac{3\sqrt3}{8}\,\frac{a}{b}\approx0.65\,\frac{a}{b}.
\]</span></p>
<p>For the rodents the inflection point is at <span class="math inline">\(10/\sqrt3\approx5.8\)</span> seeds/m², where they remove <span class="math inline">\(30/4=7.5\)</span> seeds/night and the slope is <span class="math inline">\(0.65\times3\approx1.95\)</span> (seeds/night)/(seeds/m²). Note that the inflection point lies below the half-maximum (<span class="math inline">\(b=10\)</span> seeds/m², with 15 seeds/night), whereas in a <a href="../../Supplements/deterministic-functions.html#sec-fn-logistic">logistic</a> function the two coincide.</p>
</section>
<section id="question-5-2" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="question-5-2"><span class="header-section-number">3.1.5</span> Question 5</h3>
<p>The function is a quotient of <span class="math inline">\(g(x)=ax^2\)</span> and <span class="math inline">\(h(x)=b+cx+x^2\)</span>, with <span class="math inline">\(g'(x)=2ax\)</span> and <span class="math inline">\(h'(x)=c+2x\)</span>. We only need the numerator of the quotient rule:</p>
<p><span class="math display">\[
\begin{aligned}
g'(x)\,h(x)-g(x)\,h'(x) &amp;= 2ax\,(b+cx+x^2)-ax^2\,(c+2x)\\
&amp;= 2abx+2acx^2+2ax^3-acx^2-2ax^3\\
&amp;= ax\,(2b+cx).
\end{aligned}
\]</span></p>
<p>It is zero at <span class="math inline">\(x=0\)</span> and where <span class="math inline">\(2b+cx=0\)</span>, that is, at <span class="math inline">\(x=-2b/c\)</span>, which is a positive value only when <span class="math inline">\(c\)</span> is negative. Here <span class="math inline">\(x_{\max}=-200/(-10)=20\)</span> g/m². The numerator is positive between 0 and 20 and negative beyond 20, so this is a maximum, with a height of</p>
<p><span class="math display">\[
f(20)=\frac{12\times400}{100-200+400}=\frac{4800}{300}=16 \text{ g/min}.
\]</span></p>
<p>For the limit we divide the numerator and the denominator by <span class="math inline">\(x^2\)</span>, which gives <span class="math inline">\(a/(b/x^2+c/x+1)\to a=12\)</span> g/min. So the peak is higher than the asymptote: the intake rises to 16 g/min at a biomass of 20 g/m² and then declines towards 12 g/min. With a negative <span class="math inline">\(c\)</span> the function approaches its asymptote from above. Here <span class="math inline">\(a\)</span> has the units of <span class="math inline">\(y\)</span>, <span class="math inline">\(c\)</span> the units of <span class="math inline">\(x\)</span> and <span class="math inline">\(b\)</span> the units of <span class="math inline">\(x\)</span> squared, since the three terms of the denominator must have the same units.</p>
<p>We can verify our math with R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Question 3: peak of the Hassell function with an exponent of 2 on a fine grid of eggs.</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>egg_grid <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">400</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>adults <span class="ot">=</span> <span class="dv">1280</span> <span class="sc">*</span> egg_grid <span class="sc">/</span> (<span class="dv">40</span> <span class="sc">+</span> egg_grid)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>egg_grid[<span class="fu">which.max</span>(adults)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(adults)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Question 5: peak of the Holling type IV function on a fine grid of biomass,</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and its value at a very large biomass.</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>biomass_grid <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">400</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>intake <span class="ot">=</span> <span class="dv">12</span> <span class="sc">*</span> biomass_grid<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (<span class="dv">100</span> <span class="sc">-</span> <span class="dv">10</span> <span class="sc">*</span> biomass_grid <span class="sc">+</span> biomass_grid<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>biomass_grid[<span class="fu">which.max</span>(intake)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(intake)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="dv">12</span> <span class="sc">*</span> <span class="dv">100000</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (<span class="dv">100</span> <span class="sc">-</span> <span class="dv">10</span> <span class="sc">*</span> <span class="dv">100000</span> <span class="sc">+</span> <span class="dv">100000</span><span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.0012</code></pre>
</div>
</div>
<p>The grids give a peak of 8 adults at 40 eggs and a peak of 16 g/min at 20 g/m², and the intake at a very large biomass is 12 g/min.</p>
</section>
</section>
</section>
<section id="exercise-5-parameters" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Exercise 5: Parameters</h1>
<p>The same curve can be written with different parameters, and a curve can be moved, stretched and bounded by changing its formula (see <a href="../../Chapter_5/Theory.html#sec-function-parameters">Parameters</a> and <a href="../../Chapter_5/Theory.html#sec-function-building">Building new functions</a> in the theory). Do all the questions on paper and give the units of every parameter. The first three questions are the core of this exercise and the last two are extra practice.</p>
<ol type="1">
<li>A wolf spider searches an area of <span class="math inline">\(\alpha=2\)</span> m²/day for prey and needs <span class="math inline">\(H=0.05\)</span> days to handle each prey. Write its functional response in the Holling type II form, <span class="math inline">\(f(x)=\dfrac{\alpha x}{1+\alpha Hx}\)</span>, where <span class="math inline">\(x\)</span> is the density of prey (prey/m²), and convert it to the Michaelis–Menten form, <span class="math inline">\(f(x)=\dfrac{ax}{b+x}\)</span>. What are <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, and what do they mean? A second species has <span class="math inline">\(a=50\)</span> prey/day and <span class="math inline">\(b=25\)</span> prey/m². What are its <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(H\)</span>?</li>
<li>Rewrite the Ricker function <span class="math inline">\(f(x)=a\,x\,e^{-bx}\)</span> so that its two parameters are the location of the peak, <span class="math inline">\(x_{\max}\)</span>, and the height of the peak, <span class="math inline">\(y_{\max}\)</span>. What are <span class="math inline">\(x_{\max}\)</span> and <span class="math inline">\(y_{\max}\)</span> for <span class="math inline">\(f(x)=8\,x\,e^{-0.25x}\)</span>?</li>
<li>A plant does not flower until it has a mass of 2 g, at which it carries 3 flowers. The number of flowers then increases with the mass of the plant, <span class="math inline">\(x\)</span> (g), and approaches 27 for the heaviest plants. It is halfway between 3 and 27 at a mass of 10 g. Write the formula of a shifted and scaled Michaelis–Menten function with these properties, for <span class="math inline">\(x\ge2\)</span>.</li>
<li>The probability that a plant species occurs at a site as a function of the pH of the soil, <span class="math inline">\(x\)</span>, is described with the composition <span class="math inline">\(f(x)=\operatorname{logit}^{-1}\left[d-b\,(x-c)^2\right]\)</span> with <span class="math inline">\(d=2\)</span>, <span class="math inline">\(b=0.5\)</span> and <span class="math inline">\(c=6\)</span>. What is the range of the function? Where is its peak and how high is it? At which values of the pH is the probability 0.5?</li>
<li>Show that the <a href="../../Supplements/deterministic-functions.html#sec-fn-shepherd">Shepherd</a> function <span class="math inline">\(f(x)=\dfrac{ax}{b+x^c}\)</span> contains the Michaelis–Menten function, and that the <a href="../../Supplements/deterministic-functions.html#sec-fn-richards">Richards</a> function <span class="math inline">\(f(x)=\dfrac{a}{\left[1+d\,e^{-b(x-c)}\right]^{1/d}}\)</span> contains the logistic function. Which function does the Richards function become for <span class="math inline">\(d=-1\)</span>?</li>
</ol>
<p>When you have finished, check your answers to questions 1 and 2 in R by evaluating both forms of each function at a few values of <span class="math inline">\(x\)</span>.</p>
<section id="solution-3" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="solution-3"><span class="header-section-number">4.1</span> Solution</h2>
<section id="question-1-3" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="question-1-3"><span class="header-section-number">4.1.1</span> Question 1</h3>
<p>With the values of the spider, <span class="math inline">\(\alpha H=2\times0.05=0.1\)</span> m² per prey and the functional response is <span class="math inline">\(f(x)=2x/(1+0.1x)\)</span> prey/day. To bring it to the Michaelis–Menten form we divide the numerator and the denominator by <span class="math inline">\(\alpha H\)</span>, so that <span class="math inline">\(x\)</span> stands alone in the denominator:</p>
<p><span class="math display">\[
f(x)=\frac{\alpha x}{1+\alpha Hx}
=\frac{(1/H)\,x}{1/(\alpha H)+x}
\quad\Longrightarrow\quad
a=\frac{1}{H}=20 \text{ prey/day}, \qquad
b=\frac{1}{\alpha H}=10 \text{ prey/m}^2.
\]</span></p>
<p>The asymptote <span class="math inline">\(a\)</span> is the number of prey that the spider eats per day when prey are so dense that it spends all its time handling them: one prey every 0.05 days. The half-maximum <span class="math inline">\(b\)</span> is the density of prey at which it eats half of that, 10 prey/day. For the second species we invert the two relations:</p>
<p><span class="math display">\[
\alpha=\frac{a}{b}=\frac{50}{25}=2 \text{ m}^2\text{/day}, \qquad
H=\frac{1}{a}=\frac{1}{50}=0.02 \text{ days per prey}.
\]</span></p>
<p>The two species search the same area per day, but the second one handles a prey in less than half the time (0.02 days is about half an hour). Note that the curves are different, whereas the two forms of each curve are the same function.</p>
</section>
<section id="question-2-3" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="question-2-3"><span class="header-section-number">4.1.2</span> Question 2</h3>
<p>In Exercise 1 we found <span class="math inline">\(x_{\max}=1/b\)</span> and <span class="math inline">\(y_{\max}=a/(be)\)</span>. We solve these for the old parameters, <span class="math inline">\(b=1/x_{\max}\)</span> and <span class="math inline">\(a=y_{\max}\,b\,e=y_{\max}\,e/x_{\max}\)</span>, and substitute:</p>
<p><span class="math display">\[
f(x)=\frac{y_{\max}\,e}{x_{\max}}\;x\;e^{-x/x_{\max}}
=y_{\max}\,\frac{x}{x_{\max}}\,e^{1-x/x_{\max}}.
\]</span></p>
<p>As a check, at <span class="math inline">\(x=x_{\max}\)</span> the formula gives <span class="math inline">\(y_{\max}\times1\times e^{0}=y_{\max}\)</span>. In this form both parameters can be read from a plot, <span class="math inline">\(x_{\max}\)</span> with the units of <span class="math inline">\(x\)</span> and <span class="math inline">\(y_{\max}\)</span> with the units of <span class="math inline">\(y\)</span>. It is the <a href="../../Supplements/deterministic-functions.html#sec-fn-generalised-ricker">generalised Ricker</a> function with an exponent of one. For <span class="math inline">\(f(x)=8xe^{-0.25x}\)</span> the peak is at <span class="math inline">\(x_{\max}=1/0.25=4\)</span> and its height is <span class="math inline">\(y_{\max}=8\times4/e\approx11.8\)</span>.</p>
</section>
<section id="question-3-3" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="question-3-3"><span class="header-section-number">4.1.3</span> Question 3</h3>
<p>We build the function with the four operations of <a href="../../Chapter_5/Theory.html#sec-function-shifts">Shifting and scaling</a>. The curve starts at the point (2, 3), so it is shifted by <span class="math inline">\(c=2\)</span> g along the <span class="math inline">\(x\)</span> axis and by <span class="math inline">\(d=3\)</span> flowers along the <span class="math inline">\(y\)</span> axis. The asymptote of the shifted function is <span class="math inline">\(d+a\)</span>, so <span class="math inline">\(a=27-3=24\)</span> flowers. The function is halfway between <span class="math inline">\(d\)</span> and <span class="math inline">\(d+a\)</span> when <span class="math inline">\(x-c=b\)</span>, so <span class="math inline">\(b=10-2=8\)</span> g:</p>
<p><span class="math display">\[
f(x)=3+\frac{24\,(x-2)}{8+(x-2)}=3+\frac{24\,(x-2)}{6+x}.
\]</span></p>
<p>As a check, <span class="math inline">\(f(2)=3\)</span>, <span class="math inline">\(f(10)=3+24\times8/16=15\)</span>, which is halfway between 3 and 27, and for a large <span class="math inline">\(x\)</span> the fraction approaches 24.</p>
</section>
<section id="question-4-3" class="level3" data-number="4.1.4">
<h3 data-number="4.1.4" class="anchored" data-anchor-id="question-4-3"><span class="header-section-number">4.1.4</span> Question 4</h3>
<p>The inverse logit, <span class="math inline">\(\operatorname{logit}^{-1}(u)=1/(1+e^{-u})\)</span>, returns a value between 0 and 1 for any <span class="math inline">\(u\)</span>, and it increases with <span class="math inline">\(u\)</span>. The inner function, <span class="math inline">\(u=d-b\,(x-c)^2\)</span>, is a parabola that opens downwards: its largest value is <span class="math inline">\(d\)</span>, at <span class="math inline">\(x=c\)</span>, and it goes to <span class="math inline">\(-\infty\)</span> as <span class="math inline">\(x\)</span> moves away from <span class="math inline">\(c\)</span> in either direction. Since the outer function is increasing, the composition peaks where the inner function peaks, at a pH of <span class="math inline">\(c=6\)</span>, with a height of</p>
<p><span class="math display">\[
\operatorname{logit}^{-1}(2)=\frac{1}{1+e^{-2}}\approx0.88.
\]</span></p>
<p>Far from <span class="math inline">\(c\)</span> the function goes to zero without reaching it, so its range is <span class="math inline">\(0&lt;y\le0.88\)</span>. The probability is 0.5 where the inner function is zero, because <span class="math inline">\(\operatorname{logit}^{-1}(0)=1/2\)</span>:</p>
<p><span class="math display">\[
d-b\,(x-c)^2=0 \quad\Longrightarrow\quad x=c\pm\sqrt{d/b}=6\pm\sqrt{4}=6\pm2.
\]</span></p>
<p>So the species occurs with a probability above 0.5 between a pH of 4 and a pH of 8.</p>
</section>
<section id="question-5-3" class="level3" data-number="4.1.5">
<h3 data-number="4.1.5" class="anchored" data-anchor-id="question-5-3"><span class="header-section-number">4.1.5</span> Question 5</h3>
<p>In the Shepherd function, <span class="math inline">\(c=1\)</span> gives <span class="math inline">\(x^{c}=x\)</span> and the formula becomes <span class="math inline">\(ax/(b+x)\)</span>, the Michaelis–Menten function. In the Richards function, <span class="math inline">\(d=1\)</span> makes the exponent <span class="math inline">\(1/d\)</span> equal to one and the formula becomes <span class="math inline">\(a/\left[1+e^{-b(x-c)}\right]\)</span>, the logistic function. In both cases the simpler function is obtained by fixing one parameter of the more general one, which is what <strong>nested</strong> means.</p>
<p>For <span class="math inline">\(d=-1\)</span> the exponent is <span class="math inline">\(1/d=-1\)</span>, so the bracket moves to the numerator:</p>
<p><span class="math display">\[
f(x)=\frac{a}{\left[1-e^{-b(x-c)}\right]^{-1}}=a\left(1-e^{-b(x-c)}\right).
\]</span></p>
<p>This is the saturating exponential function shifted by <span class="math inline">\(c\)</span> along the <span class="math inline">\(x\)</span> axis: it is zero at <span class="math inline">\(x=c\)</span> and approaches <span class="math inline">\(a\)</span>. So the Richards function contains a sigmoid function and a saturating function without an inflection point, depending on the value of <span class="math inline">\(d\)</span>.</p>
<p>We can verify our math with R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Question 1: the Holling type II form (alpha = 2, H = 0.05) and the Michaelis–Menten</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># form (a = 20, b = 10) at four densities of prey.</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>prey <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">20</span>, <span class="dv">80</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> prey <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fl">0.05</span> <span class="sc">*</span> prey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1.818182  6.666667 13.333333 17.777778</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="dv">20</span> <span class="sc">*</span> prey <span class="sc">/</span> (<span class="dv">10</span> <span class="sc">+</span> prey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1.818182  6.666667 13.333333 17.777778</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Question 2: the Ricker function with a = 8 and b = 0.25, and the form with the</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># location (4) and the height (8 * 4 / e) of the peak as parameters.</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>x_values <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">10</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>y_max <span class="ot">=</span> <span class="dv">8</span> <span class="sc">*</span> <span class="dv">4</span> <span class="sc">/</span> <span class="fu">exp</span>(<span class="dv">1</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="dv">8</span> <span class="sc">*</span> x_values <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.25</span> <span class="sc">*</span> x_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  6.230406 11.772142  6.566800</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>y_max <span class="sc">*</span> (x_values <span class="sc">/</span> <span class="dv">4</span>) <span class="sc">*</span> <span class="fu">exp</span>(<span class="dv">1</span> <span class="sc">-</span> x_values <span class="sc">/</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  6.230406 11.772142  6.566800</code></pre>
</div>
</div>
<p>Both pairs of lines return the same values, and the second pair shows the height of the peak, 11.77, at <span class="math inline">\(x=4\)</span>.</p>
</section>
</section>
</section>
<section id="exercise-6-enzyme-kinetics" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Exercise 6: Enzyme kinetics</h1>
<p>The data set <code>Puromycin</code> of base R contains the rate of an enzymatic reaction (<code>rate</code>, in counts/min/min) at six concentrations of the substrate (<code>conc</code>, in parts per million, ppm), measured in cells that were treated with the antibiotic puromycin (12 observations) and in untreated cells (11 observations) (Treloar 1974, in Bates and Watts 1988). The column <code>state</code> says to which of the two groups an observation belongs. Load the data with <code>data(Puromycin, package = "datasets")</code>.</p>
<p>This is the kind of experiment for which Michaelis and Menten proposed their function, <span class="math inline">\(f(x)=\dfrac{ax}{b+x}\)</span>, where <span class="math inline">\(x\)</span> is the concentration of the substrate and <span class="math inline">\(f(x)\)</span> is the rate of the reaction (see the <a href="../../Supplements/deterministic-functions.html#sec-fn-michaelis-menten">Michaelis–Menten</a> entry of the supplement). In this exercise you place the curve by eye and compare it with an alternative function.</p>
<ol type="1">
<li>Plot the rate against the concentration, with a different symbol for each state. Read <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> from the plot for each state, with their units, and draw the two curves over the data. Which of the two parameters differs between the states?</li>
<li>On paper, calculate the initial slope of the curve of the treated cells, with its units. The saturating exponential function <span class="math inline">\(g(x)=a\left(1-e^{-b_gx}\right)\)</span> has the same shape as the Michaelis–Menten function. Find the rate <span class="math inline">\(b_g\)</span> for which it has the same asymptote and the same initial slope as the curve of the treated cells. Which fraction of the asymptote does each function reach at <span class="math inline">\(x=b\)</span>? In R, draw both curves and find the concentration at which they differ most.</li>
</ol>
<section id="solution-4" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="solution-4"><span class="header-section-number">5.1</span> Solution</h2>
<section id="question-1-4" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="question-1-4"><span class="header-section-number">5.1.1</span> Question 1</h3>
<p>We load the data and write the function in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data and look at the first rows.</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Puromycin, <span class="at">package =</span> <span class="st">"datasets"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Puromycin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  conc rate   state
1 0.02   76 treated
2 0.02   47 treated
3 0.06   97 treated
4 0.06  107 treated
5 0.11  123 treated
6 0.11  139 treated</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Michaelis–Menten function: asymptote a and half-maximum b.</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>michaelis_menten <span class="ot">=</span> <span class="cf">function</span>(x, <span class="at">a =</span> <span class="dv">1</span>, <span class="at">b =</span> <span class="dv">1</span>) {</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  a <span class="sc">*</span> x <span class="sc">/</span> (b <span class="sc">+</span> x)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The observations are the points of <a href="#fig-puromycin_curves" class="quarto-xref">Figure&nbsp;2</a>, with filled symbols for the treated cells and open symbols for the untreated cells. To read the parameters we use the two landmarks of the function: the asymptote <span class="math inline">\(a\)</span>, which has the units of <span class="math inline">\(y\)</span>, and the half-maximum <span class="math inline">\(b\)</span>, which is the concentration at which the rate is <span class="math inline">\(a/2\)</span>. In the treated cells the rate is still increasing at the highest concentration, where it is a little above 200, and the Michaelis–Menten function approaches its asymptote slowly, so we take <span class="math inline">\(a=210\)</span> counts/min/min. Half of that, 105, is the rate at a concentration of about 0.06 ppm, so <span class="math inline">\(b=0.06\)</span> ppm. In the untreated cells the rate levels off at about 160, so we take <span class="math inline">\(a=165\)</span> counts/min/min. Half of that, about 82, is again the rate at about 0.06 ppm, so <span class="math inline">\(b=0.06\)</span> ppm. We add the two curves to the plot (<a href="#fig-puromycin_curves" class="quarto-xref">Figure&nbsp;2</a>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Values read from the plot: asymptote (counts/min/min) and half-maximum (ppm).</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>a_treated <span class="ot">=</span> <span class="dv">210</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>a_untreated <span class="ot">=</span> <span class="dv">165</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>b_both <span class="ot">=</span> <span class="fl">0.06</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Observations as points: filled for the treated cells and open for the untreated cells.</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rate <span class="sc">~</span> conc, <span class="at">data =</span> Puromycin,</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="fu">ifelse</span>(Puromycin<span class="sc">$</span>state <span class="sc">==</span> <span class="st">"treated"</span>, <span class="dv">16</span>, <span class="dv">1</span>),</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Concentration of substrate (ppm)"</span>, <span class="at">ylab =</span> <span class="st">"Rate (counts/min/min)"</span>)</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="co"># One curve per state, with a different line type.</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">michaelis_menten</span>(x, <span class="at">a =</span> a_treated, <span class="at">b =</span> b_both), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">michaelis_menten</span>(x, <span class="at">a =</span> a_untreated, <span class="at">b =</span> b_both), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"treated"</span>, <span class="st">"untreated"</span>),</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">bty =</span> <span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-puromycin_curves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-puromycin_curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="solution_files/figure-html/fig-puromycin_curves-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-puromycin_curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Rate of an enzymatic reaction against the concentration of the substrate in cells treated with puromycin (filled circles, solid line) and in untreated cells (open circles, dashed line). The curves are Michaelis–Menten functions with parameters read by eye: a = 210 and b = 0.06 for the treated cells, a = 165 and b = 0.06 for the untreated cells.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Both curves follow the observations of their group. So, by eye, the two states differ in the asymptote <span class="math inline">\(a\)</span>, which is the maximum rate of the reaction, and they share the half-maximum <span class="math inline">\(b\)</span>: the treated cells reach a higher rate, but they reach half of it at the same concentration. Whether the data support one <span class="math inline">\(b\)</span> for both states is a question that needs fitted models and a comparison between them, which is the topic of <a href="../../Chapter_6/Theory.qmd">Chapter 6</a>.</p>
</section>
<section id="question-2-4" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="question-2-4"><span class="header-section-number">5.1.2</span> Question 2</h3>
<p>The initial slope of the Michaelis–Menten function is <span class="math inline">\(a/b\)</span>. For the treated cells it is <span class="math inline">\(210/0.06=3500\)</span> (counts/min/min)/ppm.</p>
<p>The saturating exponential function has the asymptote <span class="math inline">\(a\)</span>, so <span class="math inline">\(a=210\)</span> for both functions. Its derivative is <span class="math inline">\(g'(x)=a\,b_g\,e^{-b_gx}\)</span> (Exercise 3), so its initial slope is <span class="math inline">\(g'(0)=a\,b_g\)</span>. Setting the two initial slopes equal,</p>
<p><span class="math display">\[
a\,b_g=\frac{a}{b} \quad\Longrightarrow\quad b_g=\frac{1}{b}=\frac{1}{0.06}\approx16.7
\text{/ppm}.
\]</span></p>
<p>Note that the two parameters have inverse units, as they should: <span class="math inline">\(b\)</span> is a concentration and <span class="math inline">\(b_g\)</span> is a rate per unit of concentration. At <span class="math inline">\(x=b\)</span> the Michaelis–Menten function is at half of its asymptote, by definition. The saturating exponential is at <span class="math inline">\(1-e^{-b_gb}=1-e^{-1}\approx0.63\)</span> of it. So the two functions start along the same line and end at the same value, but the saturating exponential bends later and more sharply. In R (<a href="#fig-puromycin_exponential" class="quarto-xref">Figure&nbsp;3</a>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Saturating exponential: asymptote a and rate b.</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>saturating_exponential <span class="ot">=</span> <span class="cf">function</span>(x, <span class="at">a =</span> <span class="dv">1</span>, <span class="at">b =</span> <span class="dv">1</span>) {</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  a <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(<span class="sc">-</span>b <span class="sc">*</span> x))</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Both functions on a fine grid of concentrations, with the same asymptote and</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="co"># the same initial slope.</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>conc_grid <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">1.2</span>, <span class="at">by =</span> <span class="fl">0.0001</span>)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>mm_values <span class="ot">=</span> <span class="fu">michaelis_menten</span>(conc_grid, <span class="at">a =</span> a_treated, <span class="at">b =</span> b_both)</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>exp_values <span class="ot">=</span> <span class="fu">saturating_exponential</span>(conc_grid, <span class="at">a =</span> a_treated, <span class="at">b =</span> <span class="dv">1</span> <span class="sc">/</span> b_both)</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Concentration at which the two functions differ most, and their values there.</span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>largest <span class="ot">=</span> <span class="fu">which.max</span>(exp_values <span class="sc">-</span> mm_values)</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>conc_grid[largest]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1508</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>mm_values[largest]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 150.2277</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>exp_values[largest]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 192.9905</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The two curves with the observations of the treated cells.</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>treated <span class="ot">=</span> Puromycin[Puromycin<span class="sc">$</span>state <span class="sc">==</span> <span class="st">"treated"</span>, ]</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rate <span class="sc">~</span> conc, <span class="at">data =</span> treated,</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Concentration of substrate (ppm)"</span>, <span class="at">ylab =</span> <span class="st">"Rate (counts/min/min)"</span>)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> conc_grid, <span class="at">y =</span> mm_values, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> conc_grid, <span class="at">y =</span> exp_values, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Michaelis–Menten"</span>, <span class="st">"Saturating exponential"</span>),</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">bty =</span> <span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-puromycin_exponential" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-puromycin_exponential-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="solution_files/figure-html/fig-puromycin_exponential-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-puromycin_exponential-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Michaelis–Menten function (solid line; a = 210, b = 0.06) and saturating exponential function with the same asymptote and the same initial slope (dashed line), with the observations of the treated cells.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two functions differ most at a concentration of 0.15 ppm, where the Michaelis–Menten function gives a rate of 150 and the saturating exponential a rate of 193. The saturating exponential is practically at its asymptote from 0.3 ppm onwards, whereas the Michaelis–Menten function is still rising at 1.1 ppm, as the observations are. With the same asymptote and the same initial slope, the exponential function is therefore too high between 0.1 and 0.6 ppm. To follow the observations it would need other values of its parameters, and then it would no longer share the initial slope.</p>
</section>
</section>
</section>
<section id="exercise-7-choosing-functions-for-fecundity-and-for-recruitment" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Exercise 7: Choosing functions for fecundity and for recruitment</h1>
<p>This exercise uses two data sets of the package <code>emdbook</code>, with a different shape each.</p>
<p><strong>Part A.</strong> The data set <code>FirDBHFec_sum</code> contains the diameter at breast height (<code>DBH</code>, in cm) and the fecundity (<code>fecundity</code>) of 333 balsam fir trees (<em>Abies balsamea</em>) on Whiteface Mountain, New York (Silvertown and Dodd 1999; Dodd and Silvertown 2000). Fecundity was measured as the number of cone rachises on a tree: the rachis is the axis of a cone, which stays on the branch after the cone has fallen apart. Load the data with <code>data(FirDBHFec_sum, package = "emdbook")</code>.</p>
<ol type="1">
<li>The diameter of some trees is missing. Count those trees and remove them explicitly. Plot fecundity against diameter and describe the shape of the relationship.</li>
<li>On paper, explain why a <a href="../../Supplements/deterministic-functions.html#sec-fn-power">power law</a>, <span class="math inline">\(f(x)=ax^b\)</span>, is a candidate for these data. Read two points from the curve that you would draw through the middle of the cloud and calculate <span class="math inline">\(b\)</span> and <span class="math inline">\(a\)</span> from them. What are the units of <span class="math inline">\(a\)</span>? Draw the curve over the data.</li>
<li>On paper, calculate by which factor the fecundity changes when the diameter doubles. Which measure of the size of a tree is proportional to the square of its diameter?</li>
</ol>
<p><strong>Part B.</strong> The data set <code>DamselRecruitment_sum</code> comes from a field experiment with the three-spot damselfish <em>Dascyllus trimaculatus</em>, whose larvae settle on sea anemones (Schmitt, Holbrook and Osenberg 1999). Each of the 11 rows is a target density of settlers: <code>settler.den</code> is the density of settlers and <code>surv.den</code> is the mean density of survivors after six months, both as the number of fish per 0.1 m² of anemone. Load the data with <code>data(DamselRecruitment_sum, package = "emdbook")</code>.</p>
<ol start="4" type="1">
<li>Plot the density of survivors against the density of settlers. Read starting values for a Michaelis–Menten function from the plot, with their units, and draw the curve. Compare its initial slope with the fraction of the settlers that survived at the lowest densities.</li>
<li>Write a <a href="../../Supplements/deterministic-functions.html#sec-fn-hockey-stick">hockey stick</a> function with <code>ifelse()</code>, choose its two parameters by eye and add it to the plot. Where does it describe the data differently from the Michaelis–Menten function?</li>
<li>The <a href="../../Supplements/deterministic-functions.html#sec-fn-shepherd">Shepherd</a> function can be written as <span class="math inline">\(f(x)=\dfrac{sx}{1+(x/k)^c}\)</span>, where <span class="math inline">\(s\)</span> is the initial slope, <span class="math inline">\(k\)</span> is a scale parameter and <span class="math inline">\(c\)</span> is an exponent. Write it in R, give <span class="math inline">\(s\)</span> and <span class="math inline">\(k\)</span> the values that correspond to your Michaelis–Menten function, and draw it for <span class="math inline">\(c=0.8\)</span>, <span class="math inline">\(c=1\)</span> and <span class="math inline">\(c=1.2\)</span>. What does <span class="math inline">\(c\)</span> change, and which part of the data can tell us about it?</li>
<li>Which of the three functions are nested? What would you need in order to choose among them?</li>
</ol>
<section id="solution-5" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="solution-5"><span class="header-section-number">6.1</span> Solution</h2>
<section id="question-1-5" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="question-1-5"><span class="header-section-number">6.1.1</span> Question 1</h3>
<p>We count the missing values with <code>is.na()</code> and keep the trees for which the diameter is known:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the fir data and count the trees without a diameter or without a fecundity.</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(FirDBHFec_sum, <span class="at">package =</span> <span class="st">"emdbook"</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(FirDBHFec_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(FirDBHFec_sum<span class="sc">$</span>DBH))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(FirDBHFec_sum<span class="sc">$</span>fecundity))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep the trees with a diameter.</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>fir <span class="ot">=</span> FirDBHFec_sum[<span class="sc">!</span><span class="fu">is.na</span>(FirDBHFec_sum<span class="sc">$</span>DBH), ]</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(fir)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 311</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(fir<span class="sc">$</span>DBH)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3.2 17.4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(fir<span class="sc">$</span>fecundity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   1 297</code></pre>
</div>
</div>
<p>The diameter is missing for 22 of the 333 trees, which leaves 311 trees with a diameter between 3.2 and 17.4 cm and between 1 and 297 cone rachises. We draw the plot, with the curve of question 2 already included (<a href="#fig-fir" class="quarto-xref">Figure&nbsp;4</a>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Power law: a is the value at x = 1 and b is the exponent.</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>power_law <span class="ot">=</span> <span class="cf">function</span>(x, <span class="at">a =</span> <span class="dv">1</span>, <span class="at">b =</span> <span class="dv">1</span>) {</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  a <span class="sc">*</span> x<span class="sc">^</span>b</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Observations as points and the curve of question 2 as a line.</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fecundity <span class="sc">~</span> DBH, <span class="at">data =</span> fir,</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Diameter at breast height (cm)"</span>, <span class="at">ylab =</span> <span class="st">"Fecundity (cone rachises)"</span>)</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">power_law</span>(x, <span class="at">a =</span> <span class="fl">0.5</span>, <span class="at">b =</span> <span class="dv">2</span>), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"#D55E00"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fir" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fir-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="solution_files/figure-html/fig-fir-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fir-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Fecundity of balsam fir trees against their diameter at breast height. The curve is a power law with parameters read by eye (a = 0.5, b = 2).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The fecundity increases faster and faster with the diameter, and the points spread out more as the diameter increases. There is no sign that the fecundity levels off within the range of the data.</p>
</section>
<section id="question-2-5" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="question-2-5"><span class="header-section-number">6.1.2</span> Question 2</h3>
<p>The smallest trees have almost no cones, so the function should start close to zero. From there it should increase faster and faster (a convex function), without a maximum and without an asymptote. A power law with an exponent <span class="math inline">\(b&gt;1\)</span> has these properties: it is zero at <span class="math inline">\(x=0\)</span>, it is convex and it has no asymptote (see the <a href="../../Supplements/deterministic-functions.html#sec-fn-power">power law</a> entry of the supplement).</p>
<p>A curve through the middle of the cloud passes approximately through 12.5 rachises at 5 cm and 50 rachises at 10 cm. For a power law the ratio of the two values of <span class="math inline">\(y\)</span> is <span class="math inline">\(y_2/y_1=(x_2/x_1)^b\)</span>, in which <span class="math inline">\(a\)</span> cancels. Taking logarithms on both sides and solving for <span class="math inline">\(b\)</span>:</p>
<p><span class="math display">\[
b=\frac{\log(y_2/y_1)}{\log(x_2/x_1)}=\frac{\log(50/12.5)}{\log(10/5)}
=\frac{\log4}{\log2}=2.
\]</span></p>
<p>With <span class="math inline">\(b\)</span> known, either point gives <span class="math inline">\(a\)</span>. From the second one, <span class="math inline">\(50=a\times10^2\)</span>, so <span class="math inline">\(a=0.5\)</span>. The units of <span class="math inline">\(a\)</span> depend on the exponent: <span class="math inline">\(ax^b\)</span> is a number of rachises and <span class="math inline">\(x^2\)</span> is in cm², so <span class="math inline">\(a\)</span> is in rachises per cm². The curve <span class="math inline">\(f(x)=0.5\,x^2\)</span> is the one drawn in <a href="#fig-fir" class="quarto-xref">Figure&nbsp;4</a>, where it passes through the middle of the cloud.</p>
</section>
<section id="question-3-4" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="question-3-4"><span class="header-section-number">6.1.3</span> Question 3</h3>
<p>For a power law, <span class="math inline">\(f(2x)=a\,(2x)^b=2^b\,ax^b=2^b f(x)\)</span>. So doubling the diameter multiplies the fecundity by <span class="math inline">\(2^b=4\)</span>, whatever the diameter that we start from: from 5 to 10 cm as well as from 8 to 16 cm. This is the property that defines a power law, in the same way as a constant half-life defines an exponential decay.</p>
<p>The cross-sectional area of the trunk is <span class="math inline">\(\pi(x/2)^2\)</span>, which is proportional to the square of the diameter. With an exponent of 2 the fecundity of a tree would be proportional to the cross-sectional area of its trunk, with <span class="math inline">\(a\times4/\pi\approx0.64\)</span> rachises per cm² of trunk. The exponent was read by eye, so this is a suggestion that the plot makes, and whether the data support an exponent of 2 requires an estimate with its confidence interval (<a href="../../Chapter_6/Theory.qmd">Chapter 6</a>).</p>
</section>
<section id="question-4-4" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="question-4-4"><span class="header-section-number">6.1.4</span> Question 4</h3>
<p>We load the data and calculate the fraction of the settlers that survived at each density, which we will need for the initial slope:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the damselfish data: 11 target densities of settlers.</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(DamselRecruitment_sum, <span class="at">package =</span> <span class="st">"emdbook"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>DamselRecruitment_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   settler.den  surv.den         SE
1     1.745988 0.8283553 0.44911121
2     2.011740 1.3092273 0.02652074
3     2.949125 2.3524027 0.45417618
4     4.492120 2.5343844 0.81623011
5     7.111503 2.7188487 1.79063079
6    13.480237 3.9592241 1.60719573
7    26.455599 6.6160628 1.74848343
8    50.009034 8.3219738 1.03032390
9    73.299807 8.9125316 0.95846931
10  134.485106 8.8796398 1.07960455
11  315.383056 8.5414147 0.32137276</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fraction of the settlers that survived, at each density.</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>DamselRecruitment_sum<span class="sc">$</span>surv.den <span class="sc">/</span> DamselRecruitment_sum<span class="sc">$</span>settler.den</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.47443368 0.65079365 0.79766117 0.56418443 0.38231704 0.29370583
 [7] 0.25008176 0.16640941 0.12159011 0.06602694 0.02708267</code></pre>
</div>
</div>
<p>The density of survivors increases with the density of settlers and levels off at about 9 fish per 0.1 m² from 50 settlers per 0.1 m² onwards. The densities of settlers go from 1.7 to 315, and seven of the eleven are below 30, so most of the points are crowded at the left of the plot (<a href="#fig-damsel" class="quarto-xref">Figure&nbsp;5</a>).</p>
<p>For the Michaelis–Menten function we need the asymptote and the half-maximum. The function approaches its asymptote slowly, so we take a value a little above the plateau, <span class="math inline">\(a=9.5\)</span> survivors per 0.1 m². Half of that, 4.75, lies between the survivors at 13.5 settlers (3.96) and at 26.5 settlers (6.62), so we take <span class="math inline">\(b=15\)</span> settlers per 0.1 m². The initial slope of this curve is <span class="math inline">\(a/b\approx0.63\)</span> survivors per settler. That is, at low density 63% of the settlers survive. At the four lowest densities the fraction that survived was 0.47, 0.65, 0.80 and 0.56, so the initial slope agrees with the data, although it was not used to choose the parameters.</p>
</section>
<section id="question-5-4" class="level3" data-number="6.1.5">
<h3 data-number="6.1.5" class="anchored" data-anchor-id="question-5-4"><span class="header-section-number">6.1.5</span> Question 5</h3>
<p>The hockey stick function has a slope <span class="math inline">\(a\)</span> up to the breakpoint <span class="math inline">\(c\)</span> and a plateau <span class="math inline">\(ac\)</span> beyond it. At the four highest densities there are between 8.3 and 8.9 survivors, so the plateau is at about 8.7. The line has to pass close to the last point before the plateau, 6.6 survivors at 26.5 settlers, which gives a slope of <span class="math inline">\(6.6/26.5\approx0.25\)</span> survivors per settler. With a breakpoint at <span class="math inline">\(c=35\)</span> settlers per 0.1 m² the plateau is <span class="math inline">\(ac=0.25\times35=8.75\)</span>. The function and the figure with both curves (<a href="#fig-damsel" class="quarto-xref">Figure&nbsp;5</a>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hockey stick function: slope a up to the breakpoint c, then the plateau a * c.</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>hockey_stick <span class="ot">=</span> <span class="cf">function</span>(x, <span class="at">a =</span> <span class="dv">1</span>, <span class="at">c =</span> <span class="dv">1</span>) {</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(x <span class="sc">&lt;</span> c, a <span class="sc">*</span> x, a <span class="sc">*</span> c)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a><span class="co"># The observations with both curves. michaelis_menten() was defined in Exercise 6.</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a><span class="co"># n = 500 makes curve() evaluate the function at enough points to show the corner.</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(surv.den <span class="sc">~</span> settler.den, <span class="at">data =</span> DamselRecruitment_sum, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>),</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Settlers per 0.1 m²"</span>, <span class="at">ylab =</span> <span class="st">"Survivors per 0.1 m²"</span>)</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">michaelis_menten</span>(x, <span class="at">a =</span> <span class="fl">9.5</span>, <span class="at">b =</span> <span class="dv">15</span>), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">hockey_stick</span>(x, <span class="at">a =</span> <span class="fl">0.25</span>, <span class="at">c =</span> <span class="dv">35</span>), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">n =</span> <span class="dv">500</span>)</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Michaelis–Menten"</span>, <span class="st">"Hockey stick"</span>),</span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">bty =</span> <span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-damsel" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-damsel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="solution_files/figure-html/fig-damsel-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-damsel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Density of surviving damselfish against the density of settlers. Solid line: Michaelis–Menten function (a = 9.5, b = 15). Dashed line: hockey stick function (a = 0.25, c = 35).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The points at the lowest densities are too close together in the figure to compare the two functions there, so we calculate their values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Values of the hockey stick and of the Michaelis–Menten function at the four lowest</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="co"># densities of settlers, next to the observed survivors.</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>lowest <span class="ot">=</span> DamselRecruitment_sum<span class="sc">$</span>settler.den[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hockey_stick</span>(lowest, <span class="at">a =</span> <span class="fl">0.25</span>, <span class="at">c =</span> <span class="dv">35</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4364969 0.5029349 0.7372813 1.1230301</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">michaelis_menten</span>(lowest, <span class="at">a =</span> <span class="fl">9.5</span>, <span class="at">b =</span> <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9904989 1.1234316 1.5608944 2.1893536</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>DamselRecruitment_sum<span class="sc">$</span>surv.den[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8283553 1.3092273 2.3524027 2.5343844</code></pre>
</div>
</div>
<p>The two functions differ in two places. Between 25 and 135 settlers the hockey stick is closer to the observations: the Michaelis–Menten function approaches its asymptote slowly and is still below the plateau there (7.3 against 8.3 survivors at 50 settlers). At low density it is the other way around: with a slope of 0.25 the hockey stick gives 0.4 to 1.1 survivors at the four lowest densities, where 0.8 to 2.5 were observed and where the Michaelis–Menten function gives 1.0 to 2.2. We could give the hockey stick the slope that the data show at low density (about 0.6), but then it would reach its plateau at <span class="math inline">\(8.75/0.6\approx15\)</span> settlers, where fewer than 4 fish survived. A hockey stick has one slope and a sharp corner, so it cannot describe the steep increase at low density and the plateau at once. The Michaelis–Menten function describes a slope that decreases gradually, but with these values it bends too early.</p>
<p>Note that the argument <code>c</code> of <code>hockey_stick()</code> does not interfere with the function <code>c()</code> (see <a href="../../Chapter_5/Theory.html#sec-functions-r">Functions in R</a>).</p>
</section>
<section id="question-6" class="level3" data-number="6.1.6">
<h3 data-number="6.1.6" class="anchored" data-anchor-id="question-6"><span class="header-section-number">6.1.6</span> Question 6</h3>
<p>We write the function with the input first and its three parameters after it. For <span class="math inline">\(c=1\)</span> it is <span class="math inline">\(sx/(1+x/k)=skx/(k+x)\)</span>, a Michaelis–Menten function with <span class="math inline">\(a=sk\)</span> and <span class="math inline">\(b=k\)</span>. So our curve corresponds to <span class="math inline">\(k=b=15\)</span> settlers per 0.1 m² and <span class="math inline">\(s=a/b=9.5/15\)</span> survivors per settler (<a href="#fig-damsel_shepherd" class="quarto-xref">Figure&nbsp;6</a>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Shepherd function with the initial slope s, the scale k and the exponent c.</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>shepherd <span class="ot">=</span> <span class="cf">function</span>(x, <span class="at">s =</span> <span class="dv">1</span>, <span class="at">k =</span> <span class="dv">1</span>, <span class="at">c =</span> <span class="dv">1</span>) {</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  s <span class="sc">*</span> x <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> (x <span class="sc">/</span> k)<span class="sc">^</span>c)</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial slope and scale that correspond to the Michaelis–Menten function.</span></span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>s_damsel <span class="ot">=</span> <span class="fl">9.5</span> <span class="sc">/</span> <span class="dv">15</span></span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>k_damsel <span class="ot">=</span> <span class="dv">15</span></span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Value at x = k and at the highest density of settlers, for the three exponents.</span></span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a><span class="fu">shepherd</span>(<span class="dv">15</span>, <span class="at">s =</span> s_damsel, <span class="at">k =</span> k_damsel, <span class="at">c =</span> <span class="fu">c</span>(<span class="fl">0.8</span>, <span class="dv">1</span>, <span class="fl">1.2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.75 4.75 4.75</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shepherd</span>(<span class="dv">315</span>, <span class="at">s =</span> s_damsel, <span class="at">k =</span> k_damsel, <span class="at">c =</span> <span class="fu">c</span>(<span class="fl">0.8</span>, <span class="dv">1</span>, <span class="fl">1.2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.059084  9.068182  5.037021</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The observations with the three curves; the vertical axis is extended for c = 0.8.</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(surv.den <span class="sc">~</span> settler.den, <span class="at">data =</span> DamselRecruitment_sum, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">17</span>),</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Settlers per 0.1 m²"</span>, <span class="at">ylab =</span> <span class="st">"Survivors per 0.1 m²"</span>)</span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">shepherd</span>(x, <span class="at">s =</span> s_damsel, <span class="at">k =</span> k_damsel, <span class="at">c =</span> <span class="fl">0.8</span>), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> <span class="dv">3</span>)</span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">shepherd</span>(x, <span class="at">s =</span> s_damsel, <span class="at">k =</span> k_damsel, <span class="at">c =</span> <span class="dv">1</span>), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">shepherd</span>(x, <span class="at">s =</span> s_damsel, <span class="at">k =</span> k_damsel, <span class="at">c =</span> <span class="fl">1.2</span>), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"c = 0.8"</span>, <span class="st">"c = 1"</span>, <span class="st">"c = 1.2"</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">bty =</span> <span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-damsel_shepherd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-damsel_shepherd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="solution_files/figure-html/fig-damsel_shepherd-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-damsel_shepherd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Shepherd functions with an initial slope s = 9.5/15 and a scale k = 15 for three values of the exponent c, with the damselfish data. With c = 1 (solid line) it is the Michaelis–Menten function of the previous figure.
</figcaption>
</figure>
</div>
</div>
</div>
<p>At <span class="math inline">\(x=k\)</span> the denominator is <span class="math inline">\(1+1^c=2\)</span> for any exponent, so the three curves pass through the same point, <span class="math inline">\(sk/2=4.75\)</span> survivors at 15 settlers, and they share the initial slope. The exponent changes what happens beyond <span class="math inline">\(k\)</span>. For large <span class="math inline">\(x\)</span> the function behaves as <span class="math inline">\(s\,k^c\,x^{1-c}\)</span>. With <span class="math inline">\(c=1\)</span> this is the constant <span class="math inline">\(sk\)</span>, the asymptote. With <span class="math inline">\(c&lt;1\)</span> the function keeps increasing without an asymptote (16.1 survivors at 315 settlers for <span class="math inline">\(c=0.8\)</span>), and with <span class="math inline">\(c&gt;1\)</span> it reaches a maximum and then declines towards zero (5.0 survivors at 315 settlers for <span class="math inline">\(c=1.2\)</span>). So the exponent is decided by the observations at the highest densities, of which there are four. They show a plateau, or a slight decline from 8.9 to 8.5 survivors, which a value of <span class="math inline">\(c\)</span> a little above one would describe. The standard errors of these means (the column <code>SE</code>) are between 0.3 and 1.1, so the decline is small compared with the uncertainty of the means.</p>
</section>
<section id="question-7" class="level3" data-number="6.1.7">
<h3 data-number="6.1.7" class="anchored" data-anchor-id="question-7"><span class="header-section-number">6.1.7</span> Question 7</h3>
<p>The Michaelis–Menten function is nested in the Shepherd function: it is the special case <span class="math inline">\(c=1\)</span>, as we showed in Exercise 5. The hockey stick is not nested in either of them, and neither of them is nested in the hockey stick, because no value of the parameters of one turns it into the other.</p>
<p>Looking at the curves is not enough to choose among them. The Shepherd function has one more parameter than the other two, so it can always be brought at least as close to the observations as the Michaelis–Menten function, and we need to know whether the improvement is worth a parameter. For that we need a model for the variation of the observations around the curve, so that each function has a likelihood, and estimates of the parameters by maximum likelihood in the place of values read by eye. The functions can then be compared with AIC, which was introduced in <a href="../../Chapter_4/Theory.html#sec-aic">Chapter 4</a> and works for nested functions and for functions that are not nested. This is what we do in <a href="../../Chapter_6/Theory.qmd">Chapter 6</a>. The ecology also has a say: a sharp corner means that survival is not limited at all until the anemone is full, whereas a gradual bend means that every additional settler lowers the survival of the others.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/AleMorales\.github\.io\/EcologicalModelsData2026\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>