<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Probability distributions – Ecological Models and Data Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-24c09a13944ec7e1f31d2917b1251fc2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Chapter_1/Theory.html">Theory</a></li><li class="breadcrumb-item"><a href="../Chapter_2/Theory.html">Chapter 2</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Ecological Models and Data Analysis</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_1/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_2/Theory.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_3/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Practicals</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_1/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_2/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_3/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Solutions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_1/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_2/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_3/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplements</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Supplements/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Supplements/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link" data-scroll-target="#learning-goals"><span class="header-section-number">2</span> Learning goals</a></li>
  <li><a href="#discrete-probability-distributions" id="toc-discrete-probability-distributions" class="nav-link" data-scroll-target="#discrete-probability-distributions"><span class="header-section-number">3</span> Discrete probability distributions</a>
  <ul class="collapse">
  <li><a href="#random-variables-and-probability" id="toc-random-variables-and-probability" class="nav-link" data-scroll-target="#random-variables-and-probability"><span class="header-section-number">3.1</span> Random variables and probability</a></li>
  <li><a href="#what-do-these-probabilities-mean" id="toc-what-do-these-probabilities-mean" class="nav-link" data-scroll-target="#what-do-these-probabilities-mean"><span class="header-section-number">3.2</span> What do these probabilities mean?</a></li>
  <li><a href="#sec-four_faces" id="toc-sec-four_faces" class="nav-link" data-scroll-target="#sec-four_faces"><span class="header-section-number">3.3</span> The four faces of a distribution</a></li>
  </ul></li>
  <li><a href="#sec-continuous_measurements" id="toc-sec-continuous_measurements" class="nav-link" data-scroll-target="#sec-continuous_measurements"><span class="header-section-number">4</span> Continuous probability distributions</a>
  <ul class="collapse">
  <li><a href="#probability-density" id="toc-probability-density" class="nav-link" data-scroll-target="#probability-density"><span class="header-section-number">4.1</span> Probability density</a></li>
  <li><a href="#mass-and-density" id="toc-mass-and-density" class="nav-link" data-scroll-target="#mass-and-density"><span class="header-section-number">4.2</span> Mass and density</a></li>
  <li><a href="#sec-continuous_four_faces" id="toc-sec-continuous_four_faces" class="nav-link" data-scroll-target="#sec-continuous_four_faces"><span class="header-section-number">4.3</span> The four faces of a continuous distribution</a></li>
  </ul></li>
  <li><a href="#sec-joint-independence" id="toc-sec-joint-independence" class="nav-link" data-scroll-target="#sec-joint-independence"><span class="header-section-number">5</span> Joint distributions</a>
  <ul class="collapse">
  <li><a href="#sec-two_continuous_variables" id="toc-sec-two_continuous_variables" class="nav-link" data-scroll-target="#sec-two_continuous_variables"><span class="header-section-number">5.1</span> Joint distributions of continuous variables</a></li>
  <li><a href="#independent-and-identically-distributed-random-variables" id="toc-independent-and-identically-distributed-random-variables" class="nav-link" data-scroll-target="#independent-and-identically-distributed-random-variables"><span class="header-section-number">5.2</span> Independent and identically distributed random variables</a></li>
  </ul></li>
  <li><a href="#sec-expectations" id="toc-sec-expectations" class="nav-link" data-scroll-target="#sec-expectations"><span class="header-section-number">6</span> Expectations and central moments</a></li>
  <li><a href="#sec-discrete_distributions" id="toc-sec-discrete_distributions" class="nav-link" data-scroll-target="#sec-discrete_distributions"><span class="header-section-number">7</span> Choosing a distribution</a>
  <ul class="collapse">
  <li><a href="#overdispersion" id="toc-overdispersion" class="nav-link" data-scroll-target="#overdispersion"><span class="header-section-number">7.1</span> Overdispersion</a>
  <ul class="collapse">
  <li><a href="#a-simple-diagnostic-for-overdispersion" id="toc-a-simple-diagnostic-for-overdispersion" class="nav-link" data-scroll-target="#a-simple-diagnostic-for-overdispersion"><span class="header-section-number">7.1.1</span> A simple diagnostic for overdispersion</a></li>
  <li><a href="#distributions-for-overdispersed-counts" id="toc-distributions-for-overdispersed-counts" class="nav-link" data-scroll-target="#distributions-for-overdispersed-counts"><span class="header-section-number">7.1.2</span> Distributions for overdispersed counts</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">8</span> Summary</a></li>
  <li><a href="#chapter-quiz" id="toc-chapter-quiz" class="nav-link" data-scroll-target="#chapter-quiz"><span class="header-section-number">9</span> Chapter quiz</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Chapter_1/Theory.html">Theory</a></li><li class="breadcrumb-item"><a href="../Chapter_2/Theory.html">Chapter 2</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Probability distributions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>In this chapter, we learn how to use probability distributions as the central pillar to build our statistical models. We focus on count data first. You may count, for example, surviving seedlings, flowering plants, or wildlife camera detections. We represent these counts using <strong>discrete random variables</strong> which take separate, countable values such as <span class="math inline">\(0, 1, 2, \ldots\)</span>. We then extend the same ideas to measurements such as tree height, body mass, or vegetation cover. We represent these measurements using <strong>continuous random variables</strong>, which can take any value within an interval.</p>
<p>The concepts are the same for both types of data, but the probabilities are calculated in a different way, so the chapter first covers discrete distributions and then continuous distributions. After that, we look at joint distributions of several random variables, at expectations, and at how to choose a distribution. This chapter is about the distributions themselves. How samples of data relate to distributions is the topic of <a href="../Chapter_3/Theory.html">Chapter 3</a>.</p>
</section>
<section id="learning-goals" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Learning goals</h1>
<p>In this chapter, we will cover:</p>
<ul>
<li>discrete random variables and probability;</li>
<li>the four faces of a distribution (mass or density, cumulative, quantile and samplers);</li>
<li>continuous random variables and probability density;</li>
<li>the difference between probability mass and probability density;</li>
<li>joint and marginal distributions and the assumption of independence;</li>
<li>expectations, means and variances of distributions;</li>
<li>how to choose a distribution, and the concept of overdispersion.</li>
</ul>
<p>We will use the Binomial distribution as the example for discrete data and the Normal distribution as the example for continuous data. The Poisson, Negative Binomial and other distributions for count data, and the LogNormal, Beta and other distributions for continuous data, are described in the <a href="../Supplements/distributions.html">Supplement</a>, which you will need for the practical.</p>
</section>
<section id="discrete-probability-distributions" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Discrete probability distributions</h1>
<section id="random-variables-and-probability" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="random-variables-and-probability"><span class="header-section-number">3.1</span> Random variables and probability</h2>
<p>A <strong>random variable</strong> is the quantity whose value is uncertain before we make that observation. For a count, its possible values are non-negative integers. We will use a hypothetical experiment on seed survival to illustrate how to model ecological count data. Suppose we randomly distribute several quadrats in a field and in each of them we place four seeds of a target species. We come back after a pre-specified period of time and we measure how many seeds survived inside the quadrat.</p>
<p>The random variable <span class="math inline">\(X\)</span> keeps track of the possible counts of seeds that would survive in a quadrat. If the quadrat contains four seeds, then <span class="math inline">\(X\)</span> can take any integer value from 0 to 4. Mathematically, this is expressed as:</p>
<p><span class="math display">\[
X \in \{0,1,2,3,4\}.
\]</span></p>
<p>The <strong>support</strong> of a random variable is the set of values that the variable can take. In this case <span class="math inline">\(X\)</span> can take a <strong>finite</strong> set of values. In other cases, there is no pre-specified maximum, such as the number of spores or insects that could fall into a trap. In those cases we will model count data with random variables that can take any non-negative integer value (i.e., <span class="math inline">\(\{0, 1, 2, ...\}\)</span>, formally known as <strong>countably infinite</strong>). Technically, this accounts for an infinite number of counts, though in practice the counts will always be finite and constrained to the relevant order of magnitude.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Discrete random variable">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Discrete random variable
</div>
</div>
<div class="callout-body-container callout-body">
<p>A random variable is discrete when it takes values from a finite or countably infinite set.</p>
</div>
</div>
<p>Note that <span class="math inline">\(X\)</span> does not keep track of the actual seeds that survived in a particular quadrat, that is what we call an <strong>observation</strong> of the real world. Rather, <span class="math inline">\(X\)</span> represents how likely we are to observe a particular number. That is measured by a <strong>probability</strong>. That is, a random variable will have a probability distribution associated with it that assigns a value between 0 and 1 to every possible observation or set of observations. For example, it might assign these probabilities:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(x\)</span></th>
<th style="text-align: right;"><span class="math inline">\(P(X=x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.15</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.20</td>
</tr>
</tbody>
</table>
<p>We can also define the probability of any set of values by addition of individual probabilities. For example, the probability that at least 3 seeds survive is:</p>
<p><span class="math display">\[
P(X \geq 3) = P(X = 3) + P(X = 4).
\]</span></p>
<p>The probability that any value occurs is the sum of all the individual probabilities, and that sum must always be 1:</p>
<p><span class="math display">\[
\sum_{\forall x} P(X = x) = 1,
\]</span></p>
<p>where <span class="math inline">\(\forall x\)</span> means “for all possible values <span class="math inline">\(x\)</span>”.</p>
<p>Note that the capital letter <span class="math inline">\(X\)</span> refers to the random variable, while the lower-case <span class="math inline">\(x\)</span> refers to a possible observation. This distinction looks fussy at first, but it helps to keep the model and the data separate once we start estimating parameters later in the course.</p>
</section>
<section id="what-do-these-probabilities-mean" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="what-do-these-probabilities-mean"><span class="header-section-number">3.2</span> What do these probabilities mean?</h2>
<p>We saw above that we could assign probabilities to the different possible observations and that probabilities obey some basic mathematical properties. What does it mean to say “the probability that 2 seeds survive is 0.30”? There are two complementary perspectives that one can take depending on how probability is being applied (see <a href="../Chapter_1/Theory.html">Chapter 1</a> for further details on applications of probability):</p>
<ul>
<li><p><strong>Epistemic probability</strong><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>: If the goal is to predict the number of seeds that survive in a specific quadrat, probability represents how certain we are about each possible predicted value (e.g., in the table above I am twice as confident that the value will be 2 compared to 1). This relates to how much knowledge or information we have about the system we are predicting.</p></li>
<li><p><strong>Aleatoric probability</strong><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>: Probability can also represent the relative frequency at which different counts will be observed across all the possible replications of the same experiment or observation protocol. This relates to errors in measurements, and stochasticity and variability in ecological systems.</p></li>
</ul>
<p>For many reasons, this course will focus on aleatoric probability as implemented by the Frequentist statistical paradigm<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>, so we will use probabilities to model the relative frequencies at which different observations (or, in <a href="../Chapter_3/Theory.html">Chapter 3</a>, different parameter estimates) can occur.</p>
</section>
<section id="sec-four_faces" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-four_faces"><span class="header-section-number">3.3</span> The four faces of a distribution</h2>
<p>When the set of possible observations is small we can keep track of probabilities in tables. However, as the number of possible observations increases this is not feasible. Instead, we use a <strong>probability mass function</strong> which is a formula that assigns a probability to every possible <span class="math inline">\(x\)</span>. From the mass function we can compute by countable addition the probability of any possible set of observations, which is what we call a <strong>probability distribution</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Probability distribution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Probability distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>A probability distribution assigns probabilities to all possible sets of values of a random variable. Its foundation is a probability mass function.</p>
</div>
</div>
<p>There are many probability distributions that already exist, and we represent them by their probability mass function. The oldest and most basic distribution for discrete data is the Binomial distribution, discovered by Jacob Bernoulli in 1713<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. This distribution assumes that we are observing a fixed number of events, each of which can have two values (0 or 1) and each event has the same fixed probability of having the value 1. It makes sense to use this distribution for our seed survival example: the event is whether a seed survives (1) or not (0) and we assume all seeds have the same survival probability.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>The probability mass function of the Binomial is given by:</p>
<p><span class="math display">\[
P(X=x)=\binom{n}{x}p^x(1-p)^{n-x},
\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the number of events being observed, and <span class="math inline">\(p\)</span> is the probability of an event having the value 1. I provide more details on this distribution (and others) in <a href="#sec-discrete_distributions" class="quarto-xref">Section&nbsp;7</a> and in the <a href="../Supplements/distributions.html#sec-binomial">Supplement</a>.</p>
<p>Every distribution has four functions that are interrelated<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> <a href="#fig-four_faces" class="quarto-xref">Figure&nbsp;1</a>:</p>
<ul>
<li>Probability mass;</li>
<li>Cumulative probability;</li>
<li>Quantile;</li>
<li>Random sampler.</li>
</ul>
<p>In R, all of these functions are implemented for each distribution. The name of each function consists of a prefix letter followed by a shortened name for the distribution. The four faces of the Binomial distribution are implemented by functions <code>dbinom</code>, <code>pbinom</code>, <code>qbinom</code> and <code>rbinom</code>, respectively.</p>
<p>To illustrate the four faces, we will assume in our seed survival example that each seed has a probability of survival of <span class="math inline">\(0.4\)</span> and that the variation in observations across different quadrats follows a Binomial distribution. In R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># size = n, prob = p in formula for Binomial</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>seed_survival_probability <span class="ot">=</span> <span class="fl">0.4</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>seed_count  <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">2</span>,   <span class="at">size =</span> seed_count, <span class="at">prob =</span> seed_survival_probability)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="at">q =</span> <span class="dv">2</span>,   <span class="at">size =</span> seed_count, <span class="at">prob =</span> seed_survival_probability)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qbinom</span>(<span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">size =</span> seed_count, <span class="at">prob =</span> seed_survival_probability)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">10</span>,  <span class="at">size =</span> seed_count, <span class="at">prob =</span> seed_survival_probability)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that the first argument (<code>x</code>, <code>q</code>, <code>p</code>, or <code>n</code>) is always the same for all distributions in R. The other arguments are the parameters for a given distribution (in this case, <code>size</code> is <span class="math inline">\(n\)</span> and <code>prob</code> is <span class="math inline">\(p\)</span> in the formula above).</p>
<div class="callout callout-style-default callout-note callout-titled" title="The four faces of distributions in R">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The four faces of distributions in R
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a distribution in R:</p>
<ul>
<li><code>d*</code> functions calculate probability mass</li>
<li><code>p*</code> functions calculate cumulative probabilities</li>
<li><code>q*</code> functions calculate quantiles</li>
<li><code>r*</code> functions generate random samples</li>
</ul>
<p>The first argument is conventionally named <code>x</code>, <code>q</code>, <code>p</code>, or <code>n</code>, respectively.</p>
</div>
</div>
<p>A <strong>cumulative probability function</strong> (<span class="math inline">\(F_X\)</span>) is the result of adding probability masses up to and including a value <span class="math inline">\(x\)</span> (<code>q</code> in <code>pbinom</code>):</p>
<p><span class="math display">\[
F_X(x)=P(X\leq x).
\]</span></p>
<p>For example, <span class="math inline">\(F_X(3)\)</span> is the probability that at most three seeds survive. The cumulative probability is always between zero and one, and it never decreases as <span class="math inline">\(x\)</span> increases. We will not use it much in this course<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
<p>A <strong>quantile function</strong> is the inverse of the cumulative probability function. That is, we supply a cumulative probability and ask at which value of <span class="math inline">\(x\)</span> it is reached. Because we are dealing with discrete variables, we define the <span class="math inline">\(\alpha\)</span>-quantile as the smallest <span class="math inline">\(x\)</span> whose cumulative probability (<code>p</code> in <code>qbinom</code>) reaches or exceeds <span class="math inline">\(\alpha\)</span>, which mathematically is written as:</p>
<p><span class="math display">\[
q_\alpha=\min\{x:F_X(x)\geq\alpha\}.
\]</span></p>
<p>We will use quantiles to describe a distribution numerically (e.g., the median of a distribution is the <span class="math inline">\(0.5\)</span> quantile) as complements to expectations and moments (see later). We will also use quantiles to quantify parameter uncertainty as confidence intervals (see <a href="../Chapter_3/Theory.html#sec-confidence_intervals">Chapter 3</a>).</p>
<p>The fourth face is not so much a function as a procedure. A random sampler is a procedure that generates possible samples from the distribution<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>. This means a series of possible observations that are compatible with the distribution. For example, if we want to simulate a collection of 10 quadrats from the example above, we would generate 10 random samples from the Binomial distribution.</p>
<p>We will use random sampling throughout the course (we will call it <strong>simulation</strong>) as it is a versatile way of analysing the statistical properties of a model being fitted to data. We will discuss in more detail how samples relate to their distributions in <a href="../Chapter_3/Theory.html#sec-samples">Chapter 3</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-four_faces" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-four_faces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-four_faces-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-four_faces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The four faces of a Binomial distribution with <span class="math inline">\(n = 4\)</span> and <span class="math inline">\(p = 0.4\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>When we simulate random samples in R, the computer does not observe a truly random physical process. It uses a deterministic algorithm to generate a <strong>pseudo-random sequence</strong>: a sequence designed to have the mathematical properties needed for random sampling. This is enough for the probability simulations we use in this course, while also making them reproducible.</p>
<p>A <strong>seed</strong> specifies the starting state of that algorithm. If you set the same seed before running the same simulation, R produces the same pseudo-random sequence again. We set a seed with <code>set.seed()</code>, usually once before a simulation or a batch of repeated simulations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a later random simulation reproducible.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Changing the seed changes the sequence. Always set the seed at the start of your script or (even better) before any random sampling, to make sure that you generate reproducible results.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: orchid fruit set">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: orchid fruit set
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a restoration plot, we tag six orchid flowers. Each of them has a probability of setting fruit of <span class="math inline">\(0.5\)</span>. Let <span class="math inline">\(X\)</span> be the number of these flowers that set fruit.</p>
<ol type="1">
<li>What values can <span class="math inline">\(X\)</span> take?</li>
<li>Use R to calculate (i) the probability that exactly four flowers set fruit and (ii) the probability that at most four set fruit, assuming a Binomial distribution.</li>
<li>What is the meaning of the second probability calculated in point 2?</li>
<li>Find the 0.75 quantile of <span class="math inline">\(X\)</span>. In words, what does this quantile tell you?</li>
<li>Which R function prefix (<code>d</code>, <code>p</code>, <code>q</code>, or <code>r</code>) did you use for each calculation?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The count can be any integer from 0 to 6. The exact-count probability uses <code>dbinom()</code>, the cumulative probability uses <code>pbinom()</code>, and the quantile uses <code>qbinom()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>flower_count <span class="ot">=</span> <span class="dv">6</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>fruit_set_probability <span class="ot">=</span> <span class="fl">0.5</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate an exact probability, a cumulative probability, and a quantile.</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">size =</span> flower_count, <span class="at">prob =</span> fruit_set_probability) <span class="co"># 0.23</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.234375</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="at">q =</span> <span class="dv">4</span>, <span class="at">size =</span> flower_count, <span class="at">prob =</span> fruit_set_probability) <span class="co"># 0.89</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.890625</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qbinom</span>(<span class="at">p =</span> <span class="fl">0.75</span>, <span class="at">size =</span> flower_count, <span class="at">prob =</span> fruit_set_probability) <span class="co"># 4</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>The quantile tells me at least 75% of the probability is on counts of four or fewer, but note that cumulative probability for four is 89%. The difference is due to the discrete nature of the counts.</p>
<p>The cumulative probability means that if we repeat this 6-plant experimental unit many, many times, 89% of them will have four flowers or less. Alternatively, it could mean that we are 89% sure that a particular 6-plant experimental unit will yield 4 flowers or less.</p>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-continuous_measurements" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Continuous probability distributions</h1>
<p>A <strong>continuous random variable</strong> can take any value within an interval of the real numbers, instead of a set of separate values. Its support is therefore an interval (e.g., all positive numbers, or all numbers between 0 and 1) and its values cannot be listed one by one. We use continuous random variables to model measurements such as height, body mass, leaf area, or vegetation cover. We will use the height of trees in a forest stand to illustrate how to model continuous data.</p>
<p>Let <span class="math inline">\(X\)</span> be the height of a tree in metres. Between any two heights, say 22 m and 23 m, there are infinitely many other possible heights (22.5 m, 22.25 m, 22.137 m, and so on), so we cannot build a table of probabilities for <span class="math inline">\(X\)</span> as we did for the seed counts.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Continuous random variable">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Continuous random variable
</div>
</div>
<div class="callout-body-container callout-body">
<p>A random variable is continuous when it can take any value within an interval. Its distribution assigns probabilities to intervals of values.</p>
</div>
</div>
<p>In practice, every instrument has a finite precision, so the values that we record are always rounded. For example, if heights are recorded to the nearest tenth of a metre, a record of 22.1 m stands for any height between 22.05 m and 22.15 m. We still treat height as a continuous random variable because the rounding interval is small compared to the variation in height among trees.</p>
<section id="probability-density" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="probability-density"><span class="header-section-number">4.1</span> Probability density</h2>
<p>With a discrete random variable we could assign a probability to every possible value. This is not possible for a continuous random variable: the reason is because between any two values (no matter how close) there are infinite possible values in between.This breaks the rule of addition that we used before. That is, for discrete variables, we could define a probability mass function and derive the probability of any set of values by adding its individual components. If you were to apply this to a continuous variable, you would end with a infinite sum of probabilities for any finite set of values, no matter how small. This would result in the probability of individuals values being zero (or infinitesimally small) which is rather useless.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>.</p>
<p>So, instead of the probability of a single value, we calculate the probability that <span class="math inline">\(X\)</span> falls within an interval, such as <span class="math inline">\(P(20&lt;X\leq25)\)</span>. These probabilities are calculated from a <strong>probability density function</strong> <span class="math inline">\(f_X(x)\)</span>, which plays as similar role as the probability mass function for discrete random variables. The probability of an interval is the integral of the density over that interval:</p>
<p><span class="math display">\[
P(a&lt;X\leq b)=\int_a^b f_X(x)\,dx.
\]</span></p>
<p>In plain English, the probability that <span class="math inline">\(X\)</span> falls between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> is the area under the density curve between those two values (see the first panel of <a href="#fig-four_faces_normal" class="quarto-xref">Figure&nbsp;2</a>). For these areas to be valid probabilities, a density cannot be negative and the total area under the curve must be 1:</p>
<p><span class="math display">\[
f_X(x)\geq 0 \quad \text{and} \quad \int_{-\infty}^{\infty} f_X(x)\,dx = 1.
\]</span></p>
<p>Note that, because a single value has (effectively) a probability of zero, it does not matter whether the endpoints of an interval are included or not. That is, <span class="math inline">\(P(a&lt;X\leq b)\)</span>, <span class="math inline">\(P(a\leq X\leq b)\)</span> and <span class="math inline">\(P(a&lt;X&lt;b)\)</span> are all the same.</p>
<p>As with discrete data, there are many continuous distributions and we represent them by their probability density function. The one we use as the example in this chapter is the Normal distribution. Its probability density function is given by:</p>
<p><span class="math display">\[
f_X(x)=\frac{1}{\sigma\sqrt{2\pi}}
\exp\left[-\frac{(x-\mu)^2}{2\sigma^2}\right],
\]</span></p>
<p>where <span class="math inline">\(\mu\)</span> is the mean, which sets the centre of the distribution, and <span class="math inline">\(\sigma &gt; 0\)</span> is the standard deviation, which sets its spread (means and standard deviations are defined in <a href="#sec-expectations" class="quarto-xref">Section&nbsp;6</a>). More details on this distribution are given in the <a href="../Supplements/distributions.html#sec-normal">Supplement</a>.</p>
<p>To illustrate the concepts in this section, we will assume that the height of the trees follows a Normal distribution with <span class="math inline">\(\mu = 22\)</span> m and <span class="math inline">\(\sigma = 4\)</span> m (the Normal distribution allows any real value, but with these parameters the probability of a negative height is negligible).</p>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: measuring tree height">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: measuring tree height
</div>
</div>
<div class="callout-body-container callout-body">
<p>A tree height is recorded to the nearest tenth of a metre as 22.1 m. What range of heights could have produced that record? Would a continuous distribution assign a positive probability to a height of exactly 22.1 m?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When rounding to the nearest tenth, heights between 22.05 m and 22.15 m are recorded as 22.1 m. Under a continuous distribution <span class="math inline">\(P(X=22.1)=0\)</span>, but the interval from 22.05 m to 22.15 m has a positive probability.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="mass-and-density" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="mass-and-density"><span class="header-section-number">4.2</span> Mass and density</h2>
<p>For a discrete distribution, the <code>d*</code> functions in R return a probability mass. For a continuous distribution, they return a probability density. These are different quantities that are easily confused, so the table below compares them:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Discrete distribution</th>
<th>Continuous distribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>What <code>d*</code> returns</td>
<td>A probability, <span class="math inline">\(P(X=x)\)</span></td>
<td>A density, <span class="math inline">\(f_X(x)\)</span>, with units of 1 over the unit of <span class="math inline">\(X\)</span></td>
</tr>
<tr class="even">
<td>Probability of one value</td>
<td>Can be larger than 0</td>
<td>Always 0</td>
</tr>
<tr class="odd">
<td>Probability of a set of values</td>
<td>Sum of probability masses</td>
<td>Integral of the density (area under the curve)</td>
</tr>
<tr class="even">
<td>Cumulative probability function</td>
<td>Increases in steps</td>
<td>Increases smoothly</td>
</tr>
<tr class="odd">
<td>Quantile <span class="math inline">\(q_\alpha\)</span></td>
<td><span class="math inline">\(\min\{x:F_X(x)\geq\alpha\}\)</span></td>
<td>The value <span class="math inline">\(x\)</span> for which <span class="math inline">\(F_X(x)=\alpha\)</span></td>
</tr>
<tr class="even">
<td>Can the value returned by <code>d*</code> exceed 1?</td>
<td>No</td>
<td>Yes</td>
</tr>
</tbody>
</table>
<p>That is, a density is a probability per unit of <span class="math inline">\(X\)</span>. For example, the density of the tree height model at 22 m is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Density of the tree height model at 22 m (units: per metre).</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="at">x =</span> <span class="dv">22</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09973557</code></pre>
</div>
</div>
<p>The result is approximately <span class="math inline">\(0.0997\)</span> per metre. This is not the probability that a tree is exactly 22 m tall (which is zero). However, if we multiply the density by the width of a narrow interval around 22 m, we obtain an approximation to the probability of that interval. For example, the probability of a height between 21.95 m and 22.05 m is approximately <span class="math inline">\(0.0997 \times 0.1 \approx 0.01\)</span>.</p>
<p>Now, if we express the same model in centimetres (<span class="math inline">\(\mu = 2200\)</span> cm and <span class="math inline">\(\sigma = 400\)</span> cm), the density changes:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The same model with height in centimetres (units: per centimetre).</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="at">x =</span> <span class="dv">2200</span>, <span class="at">mean =</span> <span class="dv">2200</span>, <span class="at">sd =</span> <span class="dv">400</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0009973557</code></pre>
</div>
</div>
<p>The density is 100 times smaller (approximately <span class="math inline">\(0.000997\)</span> per centimetre) because the same probability is spread over 100 times as many units. The probability of the interval does not change: 21.95 m to 22.05 m is an interval of 10 cm, so we get <span class="math inline">\(0.000997 \times 10 \approx 0.01\)</span> as before. In the same way, if we expressed height in units of 100 m (<span class="math inline">\(\mu = 0.22\)</span> and <span class="math inline">\(\sigma = 0.04\)</span>), the density at the mean would be approximately <span class="math inline">\(9.97\)</span>, which is larger than 1.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="A density is not the probability of a value">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>A density is not the probability of a value
</div>
</div>
<div class="callout-body-container callout-body">
<p>The value of a probability density function at <span class="math inline">\(x\)</span> is not <span class="math inline">\(P(X=x)\)</span>. A density is a probability per unit of <span class="math inline">\(X\)</span>: it changes with the units of measurement and it can be larger than 1. We obtain probabilities by integrating the density over an interval.</p>
</div>
</div>
</section>
<section id="sec-continuous_four_faces" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-continuous_four_faces"><span class="header-section-number">4.3</span> The four faces of a continuous distribution</h2>
<p>A continuous distribution has the same four faces as a discrete distribution (see <a href="#sec-four_faces" class="quarto-xref">Section&nbsp;3.3</a>), with a probability density function in place of the probability mass function (<a href="#fig-four_faces_normal" class="quarto-xref">Figure&nbsp;2</a>):</p>
<ul>
<li>Probability density;</li>
<li>Cumulative probability;</li>
<li>Quantile;</li>
<li>Random sampler.</li>
</ul>
<p>The four faces of the Normal distribution are implemented in R by the functions <code>dnorm</code>, <code>pnorm</code>, <code>qnorm</code> and <code>rnorm</code>, respectively. For the tree height model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># mean = mu, sd = sigma in formula for Normal</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>mean_height <span class="ot">=</span> <span class="dv">22</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>sd_height  <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="at">x =</span> <span class="dv">22</span>,   <span class="at">mean =</span> mean_height, <span class="at">sd =</span> sd_height)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">26</span>,   <span class="at">mean =</span> mean_height, <span class="at">sd =</span> sd_height)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">mean =</span> mean_height, <span class="at">sd =</span> sd_height)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">10</span>,   <span class="at">mean =</span> mean_height, <span class="at">sd =</span> sd_height)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Regarding R, in the earlier section on the four faces of discrete distributions also applies to continuous distributions, except that the <code>d*</code> functions calculate a probability density.</p>
<p>The <strong>cumulative probability function</strong> has the same definition as before, <span class="math inline">\(F_X(x)=P(X\leq x)\)</span>, but it is now calculated as an integral of the density rather than a sum of probability masses:</p>
<p><span class="math display">\[
F_X(x)=\int_{-\infty}^{x} f_X(u)\,du.
\]</span></p>
<p>We will use cumulative probabilities more often with continuous distributions, because they give us the probability of an interval without having to calculate any integral ourselves. We just need to subtract two cumulative probabilities:</p>
<p><span class="math display">\[
P(a&lt;X\leq b)=F_X(b)-F_X(a).
\]</span></p>
<p>For example, we can calculate the probability that a tree is between 18 m and 26 m tall. For the probability that a tree is taller than 30 m we need the upper tail of the distribution, that is <span class="math inline">\(P(X&gt;30)=1-F_X(30)\)</span>, which <code>pnorm()</code> calculates when we set <code>lower.tail = FALSE</code>. In R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subtract two cumulative probabilities to obtain the probability of an interval.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">26</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">18</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6826895</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the upper tail for the probability of a height above 30 m.</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02275013</code></pre>
</div>
</div>
<p>That is, the model assigns a probability of approximately <span class="math inline">\(0.68\)</span> to heights between 18 m and 26 m (i.e., within one standard deviation of the mean) and a probability of approximately <span class="math inline">\(0.023\)</span> to heights above 30 m.</p>
<p>The <strong>quantile function</strong> is again the inverse of the cumulative probability function. For a continuous distribution such as the Normal, the cumulative probability increases smoothly, so the inverse is exact: the <span class="math inline">\(\alpha\)</span>-quantile is the value <span class="math inline">\(q_\alpha\)</span> for which</p>
<p><span class="math display">\[
F_X(q_\alpha)=\alpha,
\]</span></p>
<p>and we do not need the “smallest <span class="math inline">\(x\)</span>” rule of the discrete case. For example, the <span class="math inline">\(0.95\)</span> quantile of the tree height model is approximately 28.6 m (<code>qnorm(p = 0.95, mean = 22, sd = 4)</code>). In other words, the model assigns a probability of <span class="math inline">\(0.95\)</span> to heights below 28.6 m.</p>
<p>The random sampler works as before: <code>rnorm()</code> generates possible tree heights that are compatible with the distribution. As the values are continuous we do not expect any of them to be repeated, so we cannot summarise a sample by counting how many times each value occurs, as we did for counts. Instead, we group the values into intervals and plot them as a <strong>histogram</strong> (fourth panel of <a href="#fig-four_faces_normal" class="quarto-xref">Figure&nbsp;2</a>). We will discuss histograms and other ways of describing samples of continuous data in <a href="../Chapter_3/Theory.html#sec-continuous_samples">Chapter 3</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-four_faces_normal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-four_faces_normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-four_faces_normal-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-four_faces_normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The four faces of a Normal distribution for tree height with a mean of 22 m and a standard deviation of 4 m.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: a tree height threshold">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: a tree height threshold
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under the Normal model for tree height (<span class="math inline">\(\mu = 22\)</span> m and <span class="math inline">\(\sigma = 4\)</span> m), calculate the probability that a tree is taller than 26 m. Find the height that marks the lower 10% of the distribution. Explain each result in words.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The first calculation is the upper tail of the cumulative probability and the second one is a quantile:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate an upper-tail probability and a lower-tail quantile.</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">26</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1586553</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fl">0.10</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.87379</code></pre>
</div>
</div>
<p>The first result is approximately <span class="math inline">\(0.159\)</span>, so the model assigns a probability of about 16% to heights above 26 m. The second result is approximately 16.9 m, so the model assigns a probability of 10% to heights below 16.9 m.</p>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-joint-independence" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Joint distributions</h1>
<p>Two random variables are said to be <strong>independent</strong> if knowledge about one of them does not change the probabilities for the other. Understanding this concept requires understanding joint distributions of multiple random variables. Let’s first illustrate it with a simple example involving two binary random variables (for variety, I will use seed germination).</p>
<p>Let’s consider germination of two planted seeds. Let <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> be random variables to track germination (<code>1</code>) or not (<code>0</code>) for each of the seeds, after a pre-specified period of time. The <strong>joint distribution</strong> of <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> assigns a probability to every combination of values for <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> (this is known as the <strong>product space</strong> of <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(X_2 \backslash X_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x_1 = 0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x_1 = 1\)</span></th>
<th style="text-align: right;">Marginal <span class="math inline">\(X_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(x_2 = 0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(P(X_1 = 0, X_2 = 0)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(P(X_1 = 1, X_2 = 0)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(P(X_2 = 0)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_2 = 1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(P(X_1 = 0, X_2 = 1)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(P(X_1 = 1, X_2 = 1)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(P(X_2 = 1)\)</span></td>
</tr>
<tr class="odd">
<td>Marginal <span class="math inline">\(X_1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(P(X_1 = 0)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(P(X_1 = 1)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
</tr>
</tbody>
</table>
<p>For example, <span class="math inline">\(P(X_1 = 0, X_2 = 0)\)</span> is the probability that neither seed germinates, whereas <span class="math inline">\(P(X_1 = 1, X_2 = 0)\)</span> indicates that the first seed germinates. The original distributions for <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are the <strong>marginal distributions</strong> of the joint distribution because you can recover them by adding over rows or columns. The marginal distribution of <span class="math inline">\(X_2\)</span> tells us about the probability of the second seed germinating, regardless of what is happening to the first seed. By the rule of addition, we just need to add all the joint probabilities where the second seed is germinating.</p>
<p>Now, if <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are independent, the probability of any particular combination is the product of their marginal distributions, that is:</p>
<p><span class="math display">\[
P(X_1=x_1, X_2=x_2)=P(X_1=x_1)P(X_2=x_2).
\]</span></p>
<p>If we now assume <span class="math inline">\(P(X_1 = 1) = 0.6\)</span> and <span class="math inline">\(P(X_2 = 1) = 0.3\)</span>, then the table becomes</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(X_2 \backslash X_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x_1 = 0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x_1 = 1\)</span></th>
<th style="text-align: right;">Marginal <span class="math inline">\(X_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(x_2 = 0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.4 \times 0.7 = 0.28\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.6 \times 0.7 = 0.42\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.70\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_2 = 1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.4 \times 0.3 = 0.12\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.6 \times 0.3 = 0.18\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.30\)</span></td>
</tr>
<tr class="odd">
<td>Marginal <span class="math inline">\(X_1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.40\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.60\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.00\)</span></td>
</tr>
</tbody>
</table>
<p>Real seeds often share a parent plant, a soil patch, a drought, or a hungry herbivore. In general, lack of independence can arise through spatial clustering, shared weather, competition, or repeated measurements of the same individual. <a href="../Chapter_7/Theory.qmd">Chapter 7</a> explores how to relax the assumption of independence to build more advanced models.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Independence is a modelling assumption">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Independence is a modelling assumption
</div>
</div>
<div class="callout-body-container callout-body">
<p>Independence means that knowing the value of one random variable does not change the probability distribution of another. It is not guaranteed merely because observations were collected at different locations or times.</p>
</div>
</div>
<section id="sec-two_continuous_variables" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-two_continuous_variables"><span class="header-section-number">5.1</span> Joint distributions of continuous variables</h2>
<p>The concepts of joint distribution, marginal distribution and independence also apply to continuous random variables, with densities in place of probabilities and integrals in place of sums. For two continuous random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, the <strong>joint probability density function</strong> <span class="math inline">\(f_{X,Y}(x,y)\)</span> assigns a density to every combination of values of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. The probability of a region <span class="math inline">\(A\)</span> of the product space is the integral of the joint density over that region:</p>
<p><span class="math display">\[
P\big((X,Y)\in A\big)=\iint_A f_{X,Y}(x,y)\,dx\,dy.
\]</span></p>
<p>In plain English, the joint density is a surface over the plane of all the combinations of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, and the probability of a region is the volume under that surface.</p>
<p>The <strong>marginal density</strong> of <span class="math inline">\(Y\)</span> is obtained by integrating the joint density over all the values of <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[
f_Y(y)=\int_{-\infty}^{\infty} f_{X,Y}(x,y)\,dx.
\]</span></p>
<p>This is the continuous version of adding over a row or a column like we did in the tables of the previous section. That is, the marginal density of <span class="math inline">\(Y\)</span> describes <span class="math inline">\(Y\)</span> regardless of the value of <span class="math inline">\(X\)</span>. Finally, <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent if their joint density is the product of their marginal densities:</p>
<p><span class="math display">\[
f_{X,Y}(x,y)=f_X(x)f_Y(y).
\]</span></p>
<p>We will use the diameter and the height of a tree to illustrate these concepts. Let <span class="math inline">\(X\)</span> be the diameter of the trunk in centimetres and <span class="math inline">\(Y\)</span> the height in metres of the same tree. We assume that <span class="math inline">\(X\)</span> follows a Normal distribution with a mean of 30 cm and a standard deviation of 5 cm, and that <span class="math inline">\(Y\)</span> follows the Normal distribution that we used before (a mean of 22 m and a standard deviation of 4 m). These are the two marginal distributions. For the joint distribution we use a <em>bivariate</em> Normal distribution, which has one more parameter, the <strong>correlation</strong>, that controls how strongly the two variables change together. A correlation of zero means that the two variables are independent, and we set it to <span class="math inline">\(0.7\)</span> so that trees with a large diameter also tend to be tall.</p>
<p><a href="#fig-joint_density" class="quarto-xref">Figure&nbsp;3</a> shows the contours of this joint density, together with 300 trees simulated from the same model. Each contour joins the combinations of diameter and height that have the same joint density, in the same way as the contour lines in a topographic map join places with the same elevation. The contours are tilted: the combinations of a large diameter with a large height have a higher density than the combinations of a large diameter with a small height. If diameter and height were independent, the contours would not be tilted.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-joint_density" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-joint_density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-joint_density-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-joint_density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Joint distribution of tree diameter and height. The lines are contours of the joint density of a bivariate Normal distribution with a correlation of 0.7 and the points are 300 trees simulated from that distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We can see the effect of the correlation on a probability. Each of the marginal distributions is symmetric around its mean, so the probability that a tree has a diameter above 30 cm is <span class="math inline">\(0.5\)</span>, and the probability that it is taller than 22 m is also <span class="math inline">\(0.5\)</span>. If diameter and height were independent, the probability that a tree is above both means would be <span class="math inline">\(0.5 \times 0.5 = 0.25\)</span>. Under the joint distribution with a correlation of <span class="math inline">\(0.7\)</span> this probability is approximately <span class="math inline">\(0.37\)</span>, because large diameters and large heights tend to occur together.</p>
</section>
<section id="independent-and-identically-distributed-random-variables" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="independent-and-identically-distributed-random-variables"><span class="header-section-number">5.2</span> Independent and identically distributed random variables</h2>
<p>We often make a stronger working assumption: observations are both independent and <strong>identically distributed</strong>, meaning that each follows the same probability distribution. We call this <strong>independent and identically distributed (i.i.d.)</strong>. When we take repeated observations of what we consider to be the same ecological phenomenon, we will treat these observations as i.i.d. Also, the random samples that are generated by R functions such as <code>rbinom</code> are i.i.d.</p>
<p>Going back to the two-seed germination trial we just imagined, if the two seeds are from the same species and origin, have been treated in the same manner and are buried in the same soil under the same environmental conditions, we will have no reason to believe that their behaviour differs. So we will treat them as i.i.d. If we then define <span class="math inline">\(P(X_1 = 1) = P(X_2 = 1) = 0.3\)</span> the table becomes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(X_2 \backslash X_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x_1 = 0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x_1 = 1\)</span></th>
<th style="text-align: right;">Marginal <span class="math inline">\(X_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(x_2 = 0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.7 \times 0.7 = 0.49\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.3 \times 0.7 = 0.21\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.70\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_2 = 1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.7 \times 0.3 = 0.21\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.3 \times 0.3 = 0.09\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.30\)</span></td>
</tr>
<tr class="odd">
<td>Marginal <span class="math inline">\(X_1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.70\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.30\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.00\)</span></td>
</tr>
</tbody>
</table>
<p>We will see that the i.i.d. assumption is going to be fundamental for the methods of parameter estimation in <a href="../Chapter_3/Theory.html">Chapter 3</a> and <a href="../Chapter_4/Theory.qmd">Chapter 4</a>.</p>
</section>
</section>
<section id="sec-expectations" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Expectations and central moments</h1>
<p>An <strong>expectation</strong> is the procedure of taking a probability-weighted average of any quantity calculated from a random variable. That is, for any function of a random variable <span class="math inline">\(f(X)\)</span>, you can define its expectation:</p>
<p><span class="math display">\[
E[f(X)] = \sum_x f(x) P(X=x).
\]</span></p>
<p>For a continuous random variable, we use an integral of the probability density instead (note that <span class="math inline">\(f\)</span> is the function we take the expectation of and <span class="math inline">\(f_X\)</span> is the density):</p>
<p><span class="math display">\[
E[f(X)] = \int_{-\infty}^{\infty} f(x) f_X(x)\,dx.
\]</span></p>
<p>The <strong>mean</strong> of a distribution (<span class="math inline">\(\mu\)</span>, also known as the <strong>expected value</strong>) is the expectation for <span class="math inline">\(f(X) = X\)</span>, that is:</p>
<p><span class="math display">\[
\mu = E[X] = \sum_x x P(X=x)
\]</span></p>
<p>for a discrete random variable and</p>
<p><span class="math display">\[
\mu = E[X] = \int_{-\infty}^{\infty} x f_X(x)\,dx
\]</span></p>
<p>for a continuous random variable.</p>
<p>For example, we can compute the mean of the Binomial distribution of seed survival as:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the Binomial probability mass to calculate a weighted average.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>seed_count <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>seed_survival_probability <span class="ot">=</span> <span class="fl">0.4</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>seed_values <span class="ot">=</span> <span class="fu">seq.int</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> seed_count)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>seed_probability <span class="ot">=</span> <span class="fu">dbinom</span>(</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> seed_values,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> seed_count,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> seed_survival_probability</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>expected_value <span class="ot">=</span> <span class="fu">sum</span>(seed_values <span class="sc">*</span> seed_probability)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>expected_value</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.6</code></pre>
</div>
</div>
<p>The <strong>variance</strong> of a distribution (<span class="math inline">\(Var(X)\)</span>) is the expectation for <span class="math inline">\(f(X) = (X-E[X])^2\)</span>, that is, the expected squared distance from the mean:</p>
<p><span class="math display">\[
\operatorname{Var}(X) = E[(X-E[X])^2] = \sum_x P(X=x)(x-E[X])^2.
\]</span></p>
<p>For a continuous random variable, the variance is:</p>
<p><span class="math display">\[
\operatorname{Var}(X) = E[(X-E[X])^2] = \int_{-\infty}^{\infty} (x-E[X])^2 f_X(x)\,dx.
\]</span></p>
<p>The variance is an example of a <strong>central moment</strong> of a distribution. The <span class="math inline">\(k\)</span>th central moment is the expectation of the <span class="math inline">\(k\)</span>th power of the distance from the mean, that is <span class="math inline">\(E[(X-E[X])^k]\)</span>, and the variance is the case <span class="math inline">\(k = 2\)</span>. Other central moments of interest are the <strong>skewness</strong> (<span class="math inline">\(k = 3\)</span>) and <strong>kurtosis</strong> (<span class="math inline">\(k = 4\)</span>). The skewness measures if the distribution is symmetric. The kurtosis measures how thick the tails are (i.e., spread of distribution far away from the mean).</p>
<p>The variance measures how widely a distribution spreads its probability across possible values. For two distributions with comparable means, a smaller variance generally means counts are more concentrated near the mean.</p>
<p>We can also calculate the variance for the Binomial model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Weight each squared distance from the mean by its probability.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>variance <span class="ot">=</span> <span class="fu">sum</span>((seed_values <span class="sc">-</span> expected_value)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> seed_probability)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>variance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.96</code></pre>
</div>
</div>
<p>The <strong>standard deviation</strong> is the square root of the variance:</p>
<p><span class="math display">\[
\operatorname{SD}(X)=\sqrt{\operatorname{Var}(X)}.
\]</span></p>
<p>For a continuous distribution we need to calculate integrals instead of sums. R can approximate an integral using numerical methods with the function <code>integrate()</code>. Its arguments are the function to be integrated (<code>f</code>) and the limits of the integral (<code>lower</code> and <code>upper</code>, which can be infinite). It returns a list with several elements, and the value of the integral is the element called <code>value</code>. For the tree height model (a Normal distribution with a mean of 22 m and a standard deviation of 4 m):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Integrate x times the density to obtain the mean of the tree height model.</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>expected_height <span class="ot">=</span> <span class="fu">integrate</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">f =</span> <span class="cf">function</span>(x) x <span class="sc">*</span> <span class="fu">dnorm</span>(<span class="at">x =</span> x, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">upper =</span> <span class="cn">Inf</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>)<span class="sc">$</span>value</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>expected_height</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Integrate the squared distance from the mean times the density to obtain the variance.</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>height_variance <span class="ot">=</span> <span class="fu">integrate</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">f =</span> <span class="cf">function</span>(x) (x <span class="sc">-</span> expected_height)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">dnorm</span>(<span class="at">x =</span> x, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">upper =</span> <span class="cn">Inf</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>)<span class="sc">$</span>value</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>height_variance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16</code></pre>
</div>
</div>
<p>We obtain a mean of 22 m and a variance of 16 m<span class="math inline">\(^2\)</span> (i.e., a standard deviation of 4 m). These are the values of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span> that we used to define the model, because the parameters of the Normal distribution are actually its mean and its standard deviation. For most other distributions the mean and the variance are functions of the parameters, as we saw for the Binomial distribution above.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Mean, variance and standard deviation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Mean, variance and standard deviation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The mean is a property of a probability distribution. It need not be an observable value. For example, a quadrat cannot contain 1.6 surviving seeds, even though that is the mean for the seed survival example. Variance measures the spread of a distribution in squared units. Standard deviation is the square root of variance and has the same units as the original variable, making it usually easier to interpret.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: fruit set on orchid plants">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: fruit set on orchid plants
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we tag 16 orchid flowers (2 plants, 8 flowers per plant) and each of the flowers has a probability of fruit set of 0.6 and we assume a Binomial model. Let <span class="math inline">\(T\)</span> be the total number of flowers setting fruit across both plants and assume that the fruit-setting outcomes of the 16 flowers are independent events.</p>
<ol type="1">
<li>Find the probability of every possible value of <span class="math inline">\(T\)</span>.</li>
<li>Calculate the mean and variance of <span class="math inline">\(T\)</span>.</li>
<li>Give one ecological reason why independence among the flowers might be doubtful.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The possible counts range from 0 to 16. First calculate the probability of each count, then use the weighted-sum formulas for the mean and variance:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the probability mass for all possible totals.</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>fruit_count_values <span class="ot">=</span> <span class="fu">seq.int</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">16</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>fruit_probabilities <span class="ot">=</span> <span class="fu">dbinom</span>(</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> fruit_count_values,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> <span class="dv">16</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> <span class="fl">0.6</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>expected_fruit_count <span class="ot">=</span> <span class="fu">sum</span>(fruit_count_values <span class="sc">*</span> fruit_probabilities)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>fruit_count_variance <span class="ot">=</span> <span class="fu">sum</span>(</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  (fruit_count_values <span class="sc">-</span> expected_fruit_count)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> fruit_probabilities</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>expected_fruit_count</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>fruit_count_variance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.84</code></pre>
</div>
</div>
<p>Flowers on the same plant may share physiological conditions or pollinator visits, making their outcomes dependent. The Binomial calculation is conditional on the stated independence assumption; <a href="../Chapter_7/Theory.qmd">Chapter 7</a> introduces models for grouped observations.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-discrete_distributions" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Choosing a distribution</h1>
<p>In all the examples for count data above we have used the Binomial distribution, and I made sure that the examples were adequate for such a distribution. However, there are many different distributions for counts and other discrete data, each with their own properties (e.g.&nbsp;how means and variances are related). These distributions are described in the <a href="../Supplements/distributions.html">distribution supplement</a>, with the formulae, a worked example and a practice exercise for each of them. You should read at least the entries for the <a href="../Supplements/distributions.html#sec-binomial">Binomial</a>, <a href="../Supplements/distributions.html#sec-poisson">Poisson</a> and <a href="../Supplements/distributions.html#sec-negative_binomial">Negative Binomial</a> distributions, as these are the ones we will use most often in the rest of the book.</p>
<p>The same is true for continuous data, where the Normal distribution was our example. The supplement classifies the continuous distributions according to the values that the random variable can take: <strong>unconstrained</strong> (any real value), <strong>positive</strong> (any value above zero), and <strong>constrained</strong> (any value within a range). You should also read the entries for the <a href="../Supplements/distributions.html#sec-normal">Normal</a>, <a href="../Supplements/distributions.html#sec-lognormal">LogNormal</a> and <a href="../Supplements/distributions.html#sec-beta">Beta</a> distributions, which are an example of each of these three types (e.g., the LogNormal is used for measurements such as body mass and the Beta for proportions such as vegetation cover).</p>
<p>Remember that there is no <em>correct</em> distribution for a given sample of data. The range of possible values and the ecological processes that are relevant give us plausible candidates, but often we are left with multiple candidate models. In <a href="../Chapter_6/Theory.qmd">Chapter 6</a> we will learn formal methods for model comparison, but for now we will use some basic heuristics to decide which distributions are reasonable to use.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Choosing a probability distribution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Choosing a probability distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>A distribution should be chosen according to the type and range of observed values, its mean–variance relationship, and how well it describes the observed data. Ecological interpretation is useful, but a distribution is not restricted to only the process from which it was originally derived.</p>
</div>
</div>
<section id="overdispersion" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="overdispersion"><span class="header-section-number">7.1</span> Overdispersion</h2>
<p>The <a href="../Supplements/distributions.html#sec-poisson">Poisson distribution</a> is the common starting point when we count events in a fixed unit of time, area, or sampling effort (e.g., insects caught per trap-night or seedlings per quadrat), so that there is no fixed upper limit to the count. It has a single parameter <span class="math inline">\(\lambda\)</span>, the expected count per sampling unit, and its mean and variance are both equal to that parameter:</p>
<p><span class="math display">\[
E[X]=\operatorname{Var}(X)=\lambda.
\]</span></p>
<p>When the variance is higher than the mean, we say that such data has <em>overdispersion</em> relative to the Poisson distribution<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>.</p>
<p>For example, seedling counts may differ strongly among quadrats because some have better habitat. But extra variation can also reflect differences in detection or dependence among observations. The distribution itself will not tell you why overdispersion happens. Note that if you could identify and measure the sources of overdispersion you could use the techniques from <a href="../Chapter_7/Theory.qmd">Chapter 7</a> to model it.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Overdispersion is a statistical description">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Overdispersion is a statistical description
</div>
</div>
<div class="callout-body-container callout-body">
<p>Overdispersion means that the observed variation is greater than the variation expected under a reference, often the Poisson distribution. It does not identify the ecological cause. Clustering, habitat differences, omitted predictors, detection variation, and dependence can all produce overdispersion.</p>
</div>
</div>
<section id="a-simple-diagnostic-for-overdispersion" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="a-simple-diagnostic-for-overdispersion"><span class="header-section-number">7.1.1</span> A simple diagnostic for overdispersion</h3>
<p>A first exploratory check compares the sample variance with the sample mean (for convenience just use <code>var()</code>; <a href="../Chapter_3/Theory.html#sec-samples">Chapter 3</a> explains the subtle difference between the variance of a sample and what <code>var()</code> calculates). If the observations are reasonably described as independent Poisson counts with the same mean, these quantities tend to be similar. The <strong>dispersion ratio</strong> measures to what extent this holds true:</p>
<p><span class="math display">\[
\text{dispersion ratio}
=
\frac{\text{sample variance}}{\text{sample mean}}.
\]</span></p>
<p>Here we simulate quadrat counts from a Negative Binomial model (described at the end of this section) to see what the ratio can look like when variation exceeds a Poisson model’s prediction:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate overdispersed quadrat counts from a Negative Binomial model.</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="at">seed =</span> <span class="dv">123</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>n_quadrats <span class="ot">=</span> <span class="dv">100</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>negative_binomial_size <span class="ot">=</span> <span class="fl">1.5</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>negative_binomial_mean <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">=</span> <span class="fu">rnbinom</span>(</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_quadrats,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> negative_binomial_size,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu =</span> negative_binomial_mean</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="ot">=</span> <span class="fu">mean</span>(counts)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>sample_variance <span class="ot">=</span> <span class="fu">var</span>(counts)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>dispersion_ratio <span class="ot">=</span> sample_variance <span class="sc">/</span> sample_mean</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(sample_mean, sample_variance, dispersion_ratio)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3.630000 11.811212  3.253777</code></pre>
</div>
</div>
<p>A ratio close to one is consistent with the Poisson mean–variance relationship; a substantially larger ratio suggests overdispersion relative to that model. It is possible to obtain a ratio substantially lower than one, although it is rare. This is called <em>underdispersion</em>.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: variation in orchid stem counts">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: variation in orchid stem counts
</div>
</div>
<div class="callout-body-container callout-body">
<p>Across a sample of restoration plots, the mean flowering-stem count is 3 and the sample variance is 12. Calculate the dispersion ratio and describe what it suggests relative to a Poisson model. Can this ratio tell you why the counts vary so much?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The dispersion ratio is <span class="math inline">\(12/3=4\)</span>. It suggests that the observed variation is greater than expected under a Poisson model with the same mean. The ratio alone cannot identify the cause; for example, plots may differ in habitat, or counts may be clustered.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="distributions-for-overdispersed-counts" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="distributions-for-overdispersed-counts"><span class="header-section-number">7.1.2</span> Distributions for overdispersed counts</h3>
<p>When a sample shows overdispersion, we need a distribution with an additional parameter that controls the extra variation. The <a href="../Supplements/distributions.html#sec-negative_binomial">Negative Binomial distribution</a> is the usual starting model for counts without an upper limit. It has a mean <span class="math inline">\(\mu\)</span> and a shape parameter <span class="math inline">\(k\)</span>, and its variance is <span class="math inline">\(\mu+\mu^2/k\)</span>. That is, the smaller <span class="math inline">\(k\)</span> the larger the variance, and the distribution approaches the Poisson distribution as <span class="math inline">\(k\)</span> becomes large. This is the model we used in the simulation above (R calls the shape parameter <code>size</code>).</p>
<p>When the count has a fixed upper limit (e.g., the number of survivors out of a known number of seedlings), overdispersion is defined relative to the Binomial distribution, and the <a href="../Supplements/distributions.html#sec-beta_binomial">Beta-Binomial distribution</a> plays the same role as the Negative Binomial did for the Poisson. Finally, the <a href="../Supplements/distributions.html#sec-com_poisson">Conway-Maxwell-Poisson distribution</a> can describe both overdispersion and underdispersion relative to the Poisson distribution. The formulae, R functions and worked examples for these three distributions are in the supplement.</p>
</section>
</section>
</section>
<section id="summary" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Summary</h1>
<p>A random variable keeps track of the possible values of an observation, and a probability distribution assigns probabilities to all possible sets of those values. Every distribution has four faces: a probability mass or density function, a cumulative probability function, a quantile function and a random sampler, implemented in R with the prefixes <code>d</code>, <code>p</code>, <code>q</code> and <code>r</code>. We used the Binomial distribution as the example for discrete data and the Normal distribution as the example for continuous data.</p>
<p>Discrete random variables have a probability mass for every possible value, and probabilities of sets of values are sums of masses. Continuous random variables have a probability density, the probability of any single value is zero, and probabilities of intervals are integrals of the density. A density is a probability per unit of the variable, so it depends on the units of measurement and can be larger than 1.</p>
<p>A joint distribution assigns probabilities (or densities) to the combinations of values of several random variables, and the marginal distributions are recovered by adding (or integrating) over the other variables. Random variables are independent when their joint distribution is the product of their marginal distributions. Independence is an assumption of the model, and the stronger assumption that observations are independent and identically distributed (i.i.d.) is the basis for the estimation methods in the next chapters.</p>
<p>An expectation is a probability-weighted average. The mean is the expectation of the random variable itself, the variance is the expected squared distance from the mean (the second central moment), and the standard deviation is its square root. They are calculated as sums for discrete distributions and as integrals for continuous distributions.</p>
<p>Finally, a distribution is chosen according to the type and range of the values, its mean–variance relationship and how well it describes the data. For counts, overdispersion relative to the Poisson distribution can be detected with the dispersion ratio and modelled with distributions such as the Negative Binomial. The <a href="../Supplements/distributions.html">Supplement</a> describes the distributions used in the rest of the book.</p>
</section>
<section id="chapter-quiz" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Chapter quiz</h1>
<p>Probability only becomes useful when you can move comfortably between an ecological question, the possible observations, and a model’s assumptions. Try each question before opening its solution.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Question 1: lichen patches">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 1: lichen patches
</div>
</div>
<div class="callout-body-container callout-body">
<p>On a fixed section of rock, let <span class="math inline">\(X\)</span> be the number of lichen patches found. Suppose every count from zero through 18 is possible, but no larger count is possible. What is the support of <span class="math inline">\(X\)</span>? Is it finite or countably infinite?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(X\)</span> can take the integer values 0 through 18. Its support is finite because the survey area has a maximum number of patches in this scenario.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 2: freshwater larvae">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 2: freshwater larvae
</div>
</div>
<div class="callout-body-container callout-body">
<p>A proposed distribution for the number of larvae in a sample assigns probabilities 0.15, 0.25, 0.40, and 0.30 to counts 0, 1, 2, and 3. Is this a valid probability distribution? Explain.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;Although each probability is non-negative, they sum to 1.10 rather than 1. Probabilities over all possible outcomes must sum to one.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 3: coral spawning">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 3: coral spawning
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a model of the number of coral colonies spawning on a reef, which R function prefix would you use to calculate (a) the probability of exactly five colonies, (b) the probability of five or fewer, (c) the 0.9 quantile, and (d) a random sample?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Use the <code>d</code> prefix for an exact probability, <code>p</code> for a cumulative probability, <code>q</code> for a quantile, and <code>r</code> to generate a random sample.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 4: exact height">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 4: exact height
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under a continuous model for tree height, what is <span class="math inline">\(P(X=22)\)</span>? Can a height still be recorded as 22 m?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The probability of a height of exactly 22 m is zero. A recorded height of 22 m stands for an interval of heights given by the precision of the measurement (e.g., from 21.5 m to 22.5 m if heights are rounded to the nearest metre), and that interval has a positive probability.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 5: density or probability">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 5: density or probability
</div>
</div>
<div class="callout-body-container callout-body">
<p>Tree height is modelled with a Normal distribution with a mean of 22 m and a standard deviation of 4 m. Which R expression gives the probability of a height between 18 m and 26 m? What does <code>dnorm(x = 22, mean = 22, sd = 4)</code> return?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The probability of the interval is the difference between two cumulative probabilities: <code>pnorm(q = 26, mean = 22, sd = 4) - pnorm(q = 18, mean = 22, sd = 4)</code>. The function <code>dnorm()</code> returns the probability density at 22 m, in units of probability per metre.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 6: a quantile">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 6: a quantile
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under the same Normal model for tree height, what does the value returned by <code>qnorm(p = 0.95, mean = 22, sd = 4)</code> mean?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is the height below which the model places a probability of 0.95. That is, under the model 95% of the tree heights are below that value and 5% are above it.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 7: acorn production">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 7: acorn production
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose acorn production by two oak trees is modelled with independent random variables. In this model, what does independence say about the probability of a particular joint outcome? Give one ecological factor that might make the assumption questionable.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Under independence, the probability of a particular pair of outcomes is the product of their separate probabilities. Shared weather or soil conditions could make production by the two trees dependent.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 8: joint or marginal">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 8: joint or marginal
</div>
</div>
<div class="callout-body-container callout-body">
<p>Each tree in a plot has a diameter and a height. Which distribution describes the height of a tree regardless of its diameter? Which distribution do we need to calculate the probability that a tree has a diameter between 25 and 35 cm and a height above 20 m?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The marginal distribution of height describes the height of a tree regardless of its diameter. The second probability refers to a combination of both measurements, so we need the joint distribution of diameter and height.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 9: trout eggs">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 9: trout eggs
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a group of 10 trout eggs, suppose each egg hatches with probability 0.25 and the outcomes are independent. Calculate the expected number hatched and the variance assuming a Binomial distribution. Can one group of eggs have the expected number of hatched eggs? What does the expected value describe?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For a Binomial model, <span class="math inline">\(E[X]=np=10(0.25)=2.5\)</span> and <span class="math inline">\(\operatorname{Var}(X)=np(1-p)=10(0.25)(0.75)=1.875\)</span>. A group cannot have a fractional number of hatched eggs. The expected value describes the long-run average count across comparable groups of eggs under the model.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 10: bumblebee nests">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 10: bumblebee nests
</div>
</div>
<div class="callout-body-container callout-body">
<p>Across meadow plots, the sample mean number of bumblebee nests is 2 and the sample variance is 6. Calculate the dispersion ratio and explain what it suggests relative to a Poisson model. Does it identify the ecological cause?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The ratio is <span class="math inline">\(6/2=3\)</span>, suggesting greater variation than expected under a Poisson model with the same mean. The ratio does not identify a cause; clustering, habitat differences, or dependence could contribute.</p>
</div>
</div>
</div>
</div>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>In some texts this is called subjective probability, but this has an unwarranted pejorative connotation.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This is sometimes called objective probability, which implies the other must be subjective.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Sometimes we may want to say something about uncertainty of predictions and then we will muddle the waters and step out of a strict Frequentist viewpoint and borrow some ideas from the competing camp, i.e., the Bayesian statistical paradigm. This is very common in practice (though it tends to work better with larger datasets). If the focus of your research is on forecasting and uncertainty quantification, you should do it in a Bayesian way and, instead of reading this book, read <a href="https://press.princeton.edu/books/hardcover/9780691160573/ecological-forecasting?srsltid=AU7gw4WqqIymK1Rnltv3sGazFOGdtKm1mR_bg1rz7cSucqUn3c_8nAxz">Ecological Forecasting</a> by Michael Dietze.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Bernoulli, J. (1713). <em>Ars Conjectandi</em>. Impensis Thurnisiorum, Fratrum.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The classic example is flipping a coin a fixed number of times and counting the number of heads. Many classical texts describe the Binomial in terms of failures and successes, but this language has strange connotations.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>I call them the four faces; this is terminology that I completely made up<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>it is the basis for calculating p-values, which we will completely ignore in this course<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>technically, independent and identically distributed samples; this is explained later<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>I am waving my hand here. The formal mathematics of probability of continuous variables is a lot more complicated than for discrete, involving a rather obscure mathematical subject called “Measure Theory” and the so-called Lebesgue measure. We do not need to understand that bit of math to do our job as ecologists but I understand if you are struggling to build an intuition that makes sense, I do too. I have actually looked at the math (these articles are pretty thorough and formal, but also have very nice figures: https://betanalpha.github.io/writing/) and I do not think it helped me much.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>The “relative to the Poisson distribution” bit is often omitted; it is generally implied that this is the reference<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>