<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-10-06">

<title>Chapter 4: Maximum likelihood estimation – Ecological Models and Data Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-24c09a13944ec7e1f31d2917b1251fc2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../Chapter_1/Practicals/no_solution.html">Practicals</a></li><li class="breadcrumb-item"><a href="../../Chapter_4/Practicals/no_solution.html">Chapter 4</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Ecological Models and Data Analysis</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Theory</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_1/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_2/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_3/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_4/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_5/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Practicals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_1/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_2/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_3/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_4/Practicals/no_solution.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Chapter 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_5/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Solutions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_1/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_2/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_3/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_4/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Chapter_5/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplements</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/deterministic-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deterministic functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calculus refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Supplements/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercise-1-survival-of-reed-frog-tadpoles" id="toc-exercise-1-survival-of-reed-frog-tadpoles" class="nav-link active" data-scroll-target="#exercise-1-survival-of-reed-frog-tadpoles"><span class="header-section-number">1</span> Exercise 1: Survival of reed frog tadpoles</a>
  <ul class="collapse">
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution"><span class="header-section-number">1.1</span> Solution</a>
  <ul class="collapse">
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1"><span class="header-section-number">1.1.1</span> Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2"><span class="header-section-number">1.1.2</span> Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3"><span class="header-section-number">1.1.3</span> Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4"><span class="header-section-number">1.1.4</span> Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5"><span class="header-section-number">1.1.5</span> Question 5</a></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6"><span class="header-section-number">1.1.6</span> Question 6</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercise-2-glacier-lily-seedlings-in-quadrats" id="toc-exercise-2-glacier-lily-seedlings-in-quadrats" class="nav-link" data-scroll-target="#exercise-2-glacier-lily-seedlings-in-quadrats"><span class="header-section-number">2</span> Exercise 2: Glacier lily seedlings in quadrats</a></li>
  <li><a href="#exercise-3-empty-quadrats-and-zero-inflation" id="toc-exercise-3-empty-quadrats-and-zero-inflation" class="nav-link" data-scroll-target="#exercise-3-empty-quadrats-and-zero-inflation"><span class="header-section-number">3</span> Exercise 3: Empty quadrats and zero inflation</a></li>
  <li><a href="#exercise-4-timber-volume-and-body-mass" id="toc-exercise-4-timber-volume-and-body-mass" class="nav-link" data-scroll-target="#exercise-4-timber-volume-and-body-mass"><span class="header-section-number">4</span> Exercise 4: Timber volume and body mass</a></li>
  <li><a href="#exercise-5-estimators-and-intervals-across-hypothetical-experiments" id="toc-exercise-5-estimators-and-intervals-across-hypothetical-experiments" class="nav-link" data-scroll-target="#exercise-5-estimators-and-intervals-across-hypothetical-experiments"><span class="header-section-number">5</span> Exercise 5: Estimators and intervals across hypothetical experiments</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../Chapter_1/Practicals/no_solution.html">Practicals</a></li><li class="breadcrumb-item"><a href="../../Chapter_4/Practicals/no_solution.html">Chapter 4</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Chapter 4: Maximum likelihood estimation</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 6, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Exercise 1 uses a laboratory experiment on the survival of tadpoles, Exercises 2 and 3 use field counts of glacier lily seedlings, and Exercise 4 uses measurements of trees and of penguins that come with R. Exercise 5 simulates hypothetical experiments from the models fitted in Exercise 4. Exercises 1 to 4 are the core of the practical and Exercise 5 is extra practice. The data of Exercises 1 to 3 are in the package <code>emdbook</code>, which you need to install once with <code>install.packages("emdbook")</code>. Work through the first example before trying the remaining exercises. The ideas and notation are introduced in the <a href="../../Chapter_4/Theory.html">Chapter 4 theory</a>.</p>
<section id="exercise-1-survival-of-reed-frog-tadpoles" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Exercise 1: Survival of reed frog tadpoles</h1>
<p>The data set <code>ReedfrogPred</code> in the package <code>emdbook</code> contains the results of laboratory experiments on the predation of tadpoles of the African reed frog <em>Hyperolius spinigularis</em> (Vonesh and Bolker 2005). Each row is a tank of 1.2 × 0.8 × 0.4 m. The variable <code>density</code> is the number of tadpoles that were placed in the tank at the start (10, 25 or 35) and <code>surv</code> is the number of tadpoles that survived. Questions 1 to 5 use the 24 tanks with predators, and question 6 also uses the 24 tanks without them:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the reed frog data from the emdbook package without attaching the package.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ReedfrogPred, <span class="at">package =</span> <span class="st">"emdbook"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep the 24 tanks with predators.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>predator_tanks <span class="ot">=</span> ReedfrogPred[ReedfrogPred<span class="sc">$</span>pred <span class="sc">==</span> <span class="st">"pred"</span>, ]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial number of tadpoles in each tank and number of survivors, and the number of tanks.</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>tadpoles <span class="ot">=</span> predator_tanks<span class="sc">$</span>density</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>survivors <span class="ot">=</span> predator_tanks<span class="sc">$</span>surv</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>n_tanks <span class="ot">=</span> <span class="fu">length</span>(survivors)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let <span class="math inline">\(X_i\)</span> be the number of survivors in tank <span class="math inline">\(i\)</span>, which started with <span class="math inline">\(n_i\)</span> tadpoles. We use a <a href="../../Supplements/distributions.html#sec-binomial">Binomial</a> model with the same probability of survival <span class="math inline">\(p\)</span> in all the tanks,</p>
<p><span class="math display">\[
X_i \sim \operatorname{Binomial}(n_i, p),
\]</span></p>
<p>and assume that the tanks are independent. Note that the tanks are not identically distributed, because <span class="math inline">\(n_i\)</span> differs among them. The likelihood is still the product of the contributions of the tanks, since the product only requires independence. Each contribution is calculated with the <span class="math inline">\(n_i\)</span> of its own tank.</p>
<ol type="1">
<li>On paper, write the likelihood contributions of the first three tanks (4, 9 and 7 survivors out of 10 tadpoles each) and their likelihood as a function of <span class="math inline">\(p\)</span>. Calculate the likelihood and the log-likelihood for <span class="math inline">\(p=0.5\)</span> and for <span class="math inline">\(p=2/3\)</span>, and verify the results in R.</li>
<li>On paper, derive the maximum likelihood estimator of <span class="math inline">\(p\)</span> for all the tanks by differentiating the log-likelihood (the <a href="../../Supplements/calculus.html#sec-calc-rules">rules of differentiation</a> are in the calculus refresher). Calculate the estimate.</li>
<li>Write the negative log-likelihood (NLL) as a function of <span class="math inline">\(\operatorname{logit}p\)</span> and minimise it with <code>optim()</code>. Check the convergence, report the estimate of <span class="math inline">\(p\)</span> and the standard error on the logit scale, and calculate a 95% Wald interval for <span class="math inline">\(p\)</span>.</li>
<li>Calculate the 95% likelihood interval for <span class="math inline">\(p\)</span> with <code>uniroot()</code> and compare it with the Wald interval.</li>
<li>Is the Binomial model adequate for these data? For each initial density, compare the variance of the number of survivors among tanks with the variance of the fitted model. What does the comparison imply for the intervals of questions 3 and 4?</li>
<li>The experiment also had 24 tanks without predators. Fit a model with one probability of survival for all 48 tanks and a model with one probability for each treatment, and compare them with AIC and AICc. How much does the presence of predators change the probability of survival?</li>
</ol>
<section id="solution" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="solution"><span class="header-section-number">1.1</span> Solution</h2>
<section id="question-1" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="question-1"><span class="header-section-number">1.1.1</span> Question 1</h3>
<p>The observational unit is one tank. The contribution of a tank to the likelihood is the probability that the Binomial model assigns to its number of survivors, <span class="math inline">\(P(X_i=x_i\mid p)=\binom{n_i}{x_i}p^{x_i}(1-p)^{n_i-x_i}\)</span>. The first three tanks started with 10 tadpoles each and had 4, 9 and 7 survivors, so their likelihood is</p>
<p><span class="math display">\[
\begin{aligned}
L(p\mid 4,9,7)
&amp;= \binom{10}{4}p^{4}(1-p)^{6}\times
   \binom{10}{9}p^{9}(1-p)^{1}\times
   \binom{10}{7}p^{7}(1-p)^{3}\\
&amp;= 210\times 10\times 120\;p^{20}(1-p)^{10}
= 252{,}000\;p^{20}(1-p)^{10}.
\end{aligned}
\]</span></p>
<p>The exponents are the total number of survivors (20) and the total number of tadpoles that died (10) in the three tanks. For <span class="math inline">\(p=0.5\)</span> the likelihood is <span class="math inline">\(252{,}000/2^{30}\approx 2.35\times10^{-4}\)</span> and for <span class="math inline">\(p=2/3\)</span> it is <span class="math inline">\(252{,}000\times 2^{20}/3^{30}\approx 1.28\times10^{-3}\)</span>. The log-likelihood is the logarithm of the same expression,</p>
<p><span class="math display">\[
\ell(p)=\log(252{,}000)+20\log p+10\log(1-p),
\]</span></p>
<p>which gives <span class="math inline">\(12.437-20.794=-8.357\)</span> for <span class="math inline">\(p=0.5\)</span> and <span class="math inline">\(12.437-8.109-10.986=-6.658\)</span> for <span class="math inline">\(p=2/3\)</span>. We can verify our math with R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The first three tanks: survivors and initial number of tadpoles.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>first_survivors <span class="ot">=</span> survivors[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>first_tadpoles <span class="ot">=</span> tadpoles[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>first_survivors</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4 9 7</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>first_tadpoles</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10 10 10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Likelihood contribution of each tank at p = 0.5 and at p = 2/3, and the likelihood of the</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># three tanks, which is the product of the contributions.</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> first_survivors, <span class="at">size =</span> first_tadpoles, <span class="at">prob =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.205078125 0.009765625 0.117187500</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> first_survivors, <span class="at">size =</span> first_tadpoles, <span class="at">prob =</span> <span class="dv">2</span> <span class="sc">/</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05690190 0.08670765 0.26012295</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dbinom</span>(<span class="at">x =</span> first_survivors, <span class="at">size =</span> first_tadpoles, <span class="at">prob =</span> <span class="fl">0.5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0002346933</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dbinom</span>(<span class="at">x =</span> first_survivors, <span class="at">size =</span> first_tadpoles, <span class="at">prob =</span> <span class="dv">2</span> <span class="sc">/</span> <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001283402</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-likelihood at the same two values: the sum of the log probabilities.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="at">x =</span> first_survivors, <span class="at">size =</span> first_tadpoles, <span class="at">prob =</span> <span class="fl">0.5</span>, <span class="at">log =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -8.357231</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="at">x =</span> first_survivors, <span class="at">size =</span> first_tadpoles, <span class="at">prob =</span> <span class="dv">2</span> <span class="sc">/</span> <span class="dv">3</span>, <span class="at">log =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -6.658241</code></pre>
</div>
</div>
<p>R returns the same values. The difference between the two log-likelihoods is 1.70, so the three counts are about 5.5 times more probable (<span class="math inline">\(e^{1.70}\)</span>) under <span class="math inline">\(p=2/3\)</span> than under <span class="math inline">\(p=0.5\)</span>. This is no coincidence, as 20 of the 30 tadpoles in these three tanks survived. The second tank, with 9 survivors out of 10, has a probability of only 0.0098 under <span class="math inline">\(p=0.5\)</span>.</p>
</section>
<section id="question-2" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="question-2"><span class="header-section-number">1.1.2</span> Question 2</h3>
<p>For all the tanks the log-likelihood is the sum of the logarithms of the 24 contributions:</p>
<p><span class="math display">\[
\begin{aligned}
\ell(p)
&amp;= \sum_{i=1}^{24}\log\binom{n_i}{x_i}
+\log(p)\sum_{i=1}^{24}x_i
+\log(1-p)\sum_{i=1}^{24}(n_i-x_i),\\
\frac{d\ell}{dp}
&amp;= \frac{1}{p}\sum_{i=1}^{24}x_i-\frac{1}{1-p}\sum_{i=1}^{24}(n_i-x_i),\\
0 &amp;= \frac{1}{\hat p}\sum_{i=1}^{24}x_i-\frac{1}{1-\hat p}\sum_{i=1}^{24}(n_i-x_i)
\quad\Longrightarrow\quad
\hat p=\frac{\sum_{i=1}^{24}x_i}{\sum_{i=1}^{24}n_i}.
\end{aligned}
\]</span></p>
<p>The first term of the log-likelihood does not contain <span class="math inline">\(p\)</span>, so it disappears when we differentiate. To solve the last line, multiply both sides by <span class="math inline">\(\hat p(1-\hat p)\)</span>, which gives <span class="math inline">\((1-\hat p)\sum x_i=\hat p\sum(n_i-x_i)\)</span>, and collect the terms with <span class="math inline">\(\hat p\)</span>. The second derivative, <span class="math inline">\(-\sum x_i/p^2-\sum(n_i-x_i)/(1-p)^2\)</span>, is negative for every <span class="math inline">\(p\)</span>, so this is a maximum. In R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total number of survivors and of tadpoles, and the maximum likelihood estimate from</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the derivation: p_hat = sum(x_i) / sum(n_i).</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>total_survivors <span class="ot">=</span> <span class="fu">sum</span>(survivors)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>total_tadpoles <span class="ot">=</span> <span class="fu">sum</span>(tadpoles)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>p_hat <span class="ot">=</span> total_survivors <span class="sc">/</span> total_tadpoles</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">survivors =</span> total_survivors, <span class="at">tadpoles =</span> total_tadpoles, <span class="at">p_hat =</span> p_hat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  survivors    tadpoles       p_hat 
264.0000000 560.0000000   0.4714286 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The derivative of the log-likelihood, sum(x) / p - (sum(n) - sum(x)) / (1 - p),</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># is zero at that value.</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>total_survivors <span class="sc">/</span> p_hat <span class="sc">-</span> (total_tadpoles <span class="sc">-</span> total_survivors) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>In total 264 of the 560 tadpoles survived, so <span class="math inline">\(\hat p=264/560\approx 0.471\)</span>, and the derivative of the log-likelihood is zero at that value. The maximum likelihood estimator (MLE) is the fraction of all the tadpoles that survived. That is, the tanks are pooled, and a tank with 35 tadpoles weighs more in the estimate than a tank with 10.</p>
</section>
<section id="question-3" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="question-3"><span class="header-section-number">1.1.3</span> Question 3</h3>
<p>A probability lies between zero and one, so we let the optimiser search over <span class="math inline">\(\operatorname{logit}p\)</span>, which can take any real value, and convert it into a probability with <code>plogis()</code> inside the function. The NLL has two arguments for the data, and <code>dbinom()</code> receives the vector with the initial number of tadpoles of each tank in its argument <code>size</code>. We start the search at <span class="math inline">\(p=0.5\)</span>, whose logit is zero:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Negative log-likelihood of the Binomial model with one survival probability p for all tanks.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># logit_p can take any real value and plogis() turns it into a probability.</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The tanks differ in the number of tadpoles n_i, so size is a vector.</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>binomial_nll <span class="ot">=</span> <span class="cf">function</span>(logit_p, survivors, tadpoles) {</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">=</span> <span class="fu">plogis</span>(logit_p)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="at">x =</span> survivors, <span class="at">size =</span> tadpoles, <span class="at">prob =</span> p, <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit starting from p = 0.5 (logit 0); hessian = TRUE is used for the standard error.</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>frog_fit <span class="ot">=</span> <span class="fu">optim</span>(</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">par =</span> <span class="dv">0</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">fn =</span> binomial_nll,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">survivors =</span> survivors,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">tadpoles =</span> tadpoles,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"BFGS"</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">hessian =</span> <span class="cn">TRUE</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>frog_fit<span class="sc">$</span>convergence</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate on the probability scale, and the minimum of the negative log-likelihood.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plogis</span>(frog_fit<span class="sc">$</span>par)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4714286</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>frog_fit<span class="sc">$</span>value</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 98.93615</code></pre>
</div>
</div>
<p>The convergence code is 0. By invariance, <code>plogis()</code> of the estimate of <span class="math inline">\(\operatorname{logit}p\)</span> is the MLE of <span class="math inline">\(p\)</span>: 0.471, the value that we derived on paper. The minimum of the NLL is 98.94, so the maximum log-likelihood is <span class="math inline">\(-98.94\)</span>.</p>
<p>The Hessian that <code>optim()</code> returns refers to the parameter that it searched over, so its inverse is the approximate variance of the estimate of <span class="math inline">\(\operatorname{logit}p\)</span>. We calculate the Wald interval on the logit scale and transform its endpoints back with <code>plogis()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The Hessian is a 1 by 1 matrix; take its single element. For this model the second</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># derivative of the NLL with respect to logit(p) is sum(n) * p * (1 - p).</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>frog_fit<span class="sc">$</span>hessian[<span class="dv">1</span>, <span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 139.5428</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>total_tadpoles <span class="sc">*</span> p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 139.5429</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard error on the logit scale and Wald interval on that scale, back-transformed</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to survival probabilities.</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>critical_value <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fl">0.975</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>se_logit_p <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> frog_fit<span class="sc">$</span>hessian[<span class="dv">1</span>, <span class="dv">1</span>])</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>wald_p <span class="ot">=</span> <span class="fu">plogis</span>(frog_fit<span class="sc">$</span>par <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> critical_value <span class="sc">*</span> se_logit_p)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">se_logit_p =</span> se_logit_p)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>se_logit_p 
0.08465376 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>wald_p</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4303732 0.5128741</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard error on the probability scale, from the formula for a proportion.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">/</span> total_tadpoles)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02109433</code></pre>
</div>
</div>
<p>The Hessian is 139.5, which agrees with the second derivative of the NLL calculated by hand. The standard error of the estimate of <span class="math inline">\(\operatorname{logit}p\)</span> is <span class="math inline">\(1/\sqrt{139.5}\approx 0.085\)</span> and the 95% Wald interval for the probability of survival goes from 0.430 to 0.513. As in the theory, we transformed the endpoints and not the standard error, because a standard error on the logit scale cannot be converted into a probability with <code>plogis()</code> (that requires the delta method of <a href="../../Chapter_6/Theory.qmd">Chapter 6</a>). For this model a standard error on the probability scale is available from a formula: the observed information for <span class="math inline">\(p\)</span> is <span class="math inline">\(\sum n_i/[\hat p(1-\hat p)]\)</span>, so the standard error is <span class="math inline">\(\sqrt{\hat p(1-\hat p)/\sum n_i}\approx 0.021\)</span>.</p>
</section>
<section id="question-4" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="question-4"><span class="header-section-number">1.1.4</span> Question 4</h3>
<p>The model has one parameter, so the profile is the log-likelihood itself. The likelihood interval contains the values of <span class="math inline">\(p\)</span> whose relative log-likelihood is above the cutoff of <span class="math inline">\(-1.92\)</span> (see <a href="../../Chapter_4/Theory.html#sec-profile_intervals">Profile likelihood intervals</a>). We write the relative log-likelihood as a function of <span class="math inline">\(p\)</span> and use <code>uniroot()</code> to find the two values at which it equals the cutoff. <code>uniroot()</code> needs an interval whose ends give values of opposite sign. The function that we give it is positive at the estimate, so we search between 0.2 and <span class="math inline">\(\hat p\)</span> and between <span class="math inline">\(\hat p\)</span> and 0.8, after checking that the relative log-likelihood is below the cutoff at 0.2 and at 0.8:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cutoff for a 95% interval: half the 95% quantile of a chi-squared distribution</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># with one degree of freedom.</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">=</span> <span class="fu">qchisq</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-likelihood of the Binomial model as a function of p, relative to the maximum.</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>binomial_relative <span class="ot">=</span> <span class="cf">function</span>(p) {</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="at">x =</span> survivors, <span class="at">size =</span> tadpoles, <span class="at">prob =</span> p, <span class="at">log =</span> <span class="cn">TRUE</span>)) <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    frog_fit<span class="sc">$</span>value</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Relative log-likelihood at the outer ends of the two search intervals.</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="fu">binomial_relative</span>(<span class="at">p =</span> <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -103.6945</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binomial_relative</span>(<span class="at">p =</span> <span class="fl">0.8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -148.0559</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># uniroot() finds where the relative log-likelihood equals -cutoff, below and above the</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate.</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>p_lower <span class="ot">=</span> <span class="fu">uniroot</span>(</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">f =</span> <span class="cf">function</span>(p) <span class="fu">binomial_relative</span>(p) <span class="sc">+</span> cutoff,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, p_hat),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">tol =</span> <span class="fl">1e-8</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>)<span class="sc">$</span>root</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>p_upper <span class="ot">=</span> <span class="fu">uniroot</span>(</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">f =</span> <span class="cf">function</span>(p) <span class="fu">binomial_relative</span>(p) <span class="sc">+</span> cutoff,</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval =</span> <span class="fu">c</span>(p_hat, <span class="fl">0.8</span>),</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">tol =</span> <span class="fl">1e-8</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>)<span class="sc">$</span>root</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">lower =</span> p_lower, <span class="at">upper =</span> p_upper)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    lower     upper 
0.4302855 0.5128324 </code></pre>
</div>
</div>
<p>The relative log-likelihood is <span class="math inline">\(-103.7\)</span> at <span class="math inline">\(p=0.2\)</span> and <span class="math inline">\(-148.1\)</span> at <span class="math inline">\(p=0.8\)</span>, far below the cutoff, so each search interval contains one crossing. The likelihood interval goes from 0.430 to 0.513, the same as the Wald interval to three decimals. The two methods agree because the sample is large: with 560 tadpoles the log-likelihood is very close to a parabola on the logit scale, which is the approximation behind the Wald interval. Under the Binomial model with independent tanks, we would report that the probability of survival is 0.47 with a 95% confidence interval from 0.43 to 0.51.</p>
</section>
<section id="question-5" class="level3" data-number="1.1.5">
<h3 data-number="1.1.5" class="anchored" data-anchor-id="question-5"><span class="header-section-number">1.1.5</span> Question 5</h3>
<p>The Binomial model gives the variance of the number of survivors, <span class="math inline">\(n_ip(1-p)\)</span>, as well as its mean, <span class="math inline">\(n_ip\)</span>. The experiment has several tanks for each initial density, so we can compare the variance of the number of survivors among the tanks of one density (calculated with <code>var()</code>, which uses the divisor <span class="math inline">\(n-1\)</span>) with the variance of the fitted model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variance of the number of survivors among tanks of the same initial density, and the</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># variance that the Binomial model gives, n * p * (1 - p), with the estimated p.</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>densities <span class="ot">=</span> <span class="fu">sort</span>(<span class="fu">unique</span>(tadpoles))</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>variance_comparison <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">density =</span> densities,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_tanks =</span> <span class="cn">NA</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">observed_variance =</span> <span class="cn">NA</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">binomial_variance =</span> <span class="cn">NA</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(densities)) {</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  in_group <span class="ot">=</span> tadpoles <span class="sc">==</span> densities[i]</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  variance_comparison<span class="sc">$</span>n_tanks[i] <span class="ot">=</span> <span class="fu">sum</span>(in_group)</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  variance_comparison<span class="sc">$</span>observed_variance[i] <span class="ot">=</span> <span class="fu">var</span>(survivors[in_group])</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  variance_comparison<span class="sc">$</span>binomial_variance[i] <span class="ot">=</span> densities[i] <span class="sc">*</span> p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat)</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>variance_comparison</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  density n_tanks observed_variance binomial_variance
1      10       8          3.714286          2.491837
2      25       8         24.839286          6.229592
3      35       8         64.267857          8.721429</code></pre>
</div>
</div>
<p>There are eight tanks at each density. With 10 tadpoles the variance among tanks is 3.7, against 2.5 under the model. With 25 tadpoles it is 24.8 against 6.2, and with 35 tadpoles 64.3 against 8.7. So the number of survivors varies more among tanks than the Binomial model allows, up to seven times more: the counts are overdispersed relative to the Binomial distribution (see <a href="../../Chapter_2/Theory.html#sec-discrete_distributions">Chapter 2</a>). A Binomial model with one <span class="math inline">\(p\)</span> assumes that every tadpole survives with the same probability and independently of the others. Tadpoles in the same tank share their predators and their conditions, so the probability of survival is likely to differ among tanks. The tanks also differed in the size of the tadpoles (the variable <code>size</code>), which is a candidate predictor of survival.</p>
<p>The consequence for questions 3 and 4 is that both intervals are too narrow. They are calculated as if the model had generated the data, that is, as if we had 560 independent tadpoles, while most of the variation is among the 24 tanks. The estimate of 0.47 is still the overall fraction of survivors. A model in which <span class="math inline">\(p\)</span> varies among tanks is the <a href="../../Supplements/distributions.html#sec-beta_binomial">Beta-Binomial</a> distribution of the supplement, and models for observations that are grouped are the subject of <a href="../../Chapter_7/Theory.qmd">Chapter 7</a>.</p>
</section>
<section id="question-6" class="level3" data-number="1.1.6">
<h3 data-number="1.1.6" class="anchored" data-anchor-id="question-6"><span class="header-section-number">1.1.6</span> Question 6</h3>
<p>The two treatments belong to the same experiment, so we can compare them with a model for all 48 tanks. The first model is the one of question 3 applied to all the tanks, with one probability of survival (<span class="math inline">\(K=1\)</span>). In the second model the tanks with predators have a probability <span class="math inline">\(p_{\mathrm{pred}}\)</span> and the tanks without predators a probability <span class="math inline">\(p_{\mathrm{no}}\)</span> (<span class="math inline">\(K=2\)</span>), and the contribution of a tank is calculated with the probability of its treatment. We write the NLL of the second model with the logit of both probabilities as parameters. Both models are compared with AIC and with AICc, which now uses the 48 tanks as <span class="math inline">\(n\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># All 48 tanks: survivors, initial number of tadpoles and treatment ("no" or "pred").</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>survivors_all <span class="ot">=</span> ReedfrogPred<span class="sc">$</span>surv</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>tadpoles_all <span class="ot">=</span> ReedfrogPred<span class="sc">$</span>density</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>treatment <span class="ot">=</span> ReedfrogPred<span class="sc">$</span>pred</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>n_tanks_all <span class="ot">=</span> <span class="fu">length</span>(survivors_all)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(treatment)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>treatment
  no pred 
  24   24 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># NLL of the model with one probability for each treatment. The first element of logit_p is</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the logit of the survival probability without predators and the second with predators.</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>treatment_nll <span class="ot">=</span> <span class="cf">function</span>(logit_p, survivors, tadpoles, treatment) {</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">=</span> <span class="fu">plogis</span>(logit_p)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  prob <span class="ot">=</span> <span class="fu">ifelse</span>(treatment <span class="sc">==</span> <span class="st">"pred"</span>, p[<span class="dv">2</span>], p[<span class="dv">1</span>])</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="at">x =</span> survivors, <span class="at">size =</span> tadpoles, <span class="at">prob =</span> prob, <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit both models; binomial_nll() of question 3 serves for the model with one probability.</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>pooled_fit <span class="ot">=</span> <span class="fu">optim</span>(</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">par =</span> <span class="dv">0</span>,</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">fn =</span> binomial_nll,</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">survivors =</span> survivors_all,</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">tadpoles =</span> tadpoles_all,</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"BFGS"</span></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>treatment_fit <span class="ot">=</span> <span class="fu">optim</span>(</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">par =</span> <span class="fu">c</span>(<span class="at">logit_p_no =</span> <span class="dv">0</span>, <span class="at">logit_p_pred =</span> <span class="dv">0</span>),</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">fn =</span> treatment_nll,</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">survivors =</span> survivors_all,</span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">tadpoles =</span> tadpoles_all,</span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">treatment =</span> treatment,</span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"BFGS"</span>,</span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">hessian =</span> <span class="cn">TRUE</span></span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">pooled =</span> pooled_fit<span class="sc">$</span>convergence, <span class="at">treatment =</span> treatment_fit<span class="sc">$</span>convergence)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   pooled treatment 
        0         0 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimates of the survival probabilities, and the fractions of survivors that they should</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># equal: all the tadpoles, and the tadpoles of each treatment.</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plogis</span>(pooled_fit<span class="sc">$</span>par)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6991076</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plogis</span>(treatment_fit<span class="sc">$</span>par)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  logit_p_no logit_p_pred 
   0.9267857    0.4714286 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(survivors_all) <span class="sc">/</span> <span class="fu">sum</span>(tadpoles_all)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6991071</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(survivors_all, treatment, sum) <span class="sc">/</span> <span class="fu">tapply</span>(tadpoles_all, treatment, sum)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       no      pred 
0.9267857 0.4714286 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC = 2K - 2 * log-likelihood and AICc = AIC + 2K(K + 1) / (n - K - 1), with n the</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co"># number of tanks. The minimum of the NLL is minus the maximum log-likelihood.</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>k_models <span class="ot">=</span> <span class="fu">c</span>(<span class="at">pooled =</span> <span class="dv">1</span>, <span class="at">treatment =</span> <span class="dv">2</span>)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>nll_models <span class="ot">=</span> <span class="fu">c</span>(<span class="at">pooled =</span> pooled_fit<span class="sc">$</span>value, <span class="at">treatment =</span> treatment_fit<span class="sc">$</span>value)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>aic_tanks <span class="ot">=</span> <span class="dv">2</span> <span class="sc">*</span> k_models <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> nll_models</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>aicc_tanks <span class="ot">=</span> aic_tanks <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> k_models <span class="sc">*</span> (k_models <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> (n_tanks_all <span class="sc">-</span> k_models <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">aic =</span> aic_tanks, <span class="at">aicc =</span> aicc_tanks)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      pooled treatment
aic  574.489  274.2580
aicc 574.576  274.5246</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% Wald intervals on the logit scale, with the endpoints transformed back, and the</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="co"># difference between the two estimated probabilities.</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>se_logit_tanks <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">solve</span>(treatment_fit<span class="sc">$</span>hessian)))</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">no =</span> <span class="fu">plogis</span>(treatment_fit<span class="sc">$</span>par[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> critical_value <span class="sc">*</span> se_logit_tanks[<span class="dv">1</span>]),</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred =</span> <span class="fu">plogis</span>(treatment_fit<span class="sc">$</span>par[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> critical_value <span class="sc">*</span> se_logit_tanks[<span class="dv">2</span>])</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]      [,2]
no   0.9020644 0.9456428
pred 0.4303732 0.5128741</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unname</span>(<span class="fu">plogis</span>(treatment_fit<span class="sc">$</span>par[<span class="dv">1</span>]) <span class="sc">-</span> <span class="fu">plogis</span>(treatment_fit<span class="sc">$</span>par[<span class="dv">2</span>]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4553572</code></pre>
</div>
</div>
<p>Both fits have convergence code 0. The model with one probability estimates 0.699, the fraction of the 1,120 tadpoles that survived. The model with two probabilities estimates 0.927 without predators and 0.471 with predators. These are the fractions of survivors in each group of tanks, as the derivation of question 2 predicts for a Binomial model, and the second is the estimate of question 3. The AIC is 574.5 for one probability and 274.3 for one probability per treatment, and the AICc is 574.6 and 274.5. The difference of about 300 units is far larger than the two units that the additional parameter costs, and the AICc gives the same comparison.</p>
<p>The ecological question is about the size of the effect. The probability of survival is 0.47 with predators (95% Wald interval from 0.43 to 0.51) and 0.93 without them (from 0.90 to 0.95), so the presence of predators lowers it by 0.46, from 0.93 to 0.47. We do not calculate an interval for that difference, because a standard error of a difference of two probabilities that were estimated on the logit scale requires the delta method of <a href="../../Chapter_6/Theory.qmd">Chapter 6</a>.</p>
<p>The evidence is weaker than the difference in AIC suggests. Question 5 showed that the counts of the tanks with predators vary more than the Binomial model allows, so their interval is too narrow and the difference in AIC overstates the evidence. The direction and the size of the effect are still what the data show. This is the first model of the book in which a parameter differs between groups. In <a href="../../Chapter_6/Theory.qmd">Chapter 6</a> parameters will depend on continuous predictors, and in <a href="../../Chapter_7/Theory.qmd">Chapter 7</a> on groups of observations.</p>
</section>
</section>
</section>
<section id="exercise-2-glacier-lily-seedlings-in-quadrats" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Exercise 2: Glacier lily seedlings in quadrats</h1>
<p>The data set <code>Lily_sum</code> in the package <code>emdbook</code> contains counts of the glacier lily <em>Erythronium grandiflorum</em> in a grid of 16 × 16 quadrats of 2 m × 2 m in Washington Gulch, sampled in 1992 (Thomson et al.&nbsp;1996). We use the column <code>seedlings</code>, the number of seedlings in each of the 256 quadrats. Load the data with <code>data(Lily_sum, package = "emdbook")</code>.</p>
<p>Let <span class="math inline">\(X_i\)</span> be the number of seedlings in quadrat <span class="math inline">\(i\)</span>. We use a <a href="../../Supplements/distributions.html#sec-negative_binomial">Negative Binomial</a> model with mean <span class="math inline">\(\mu\)</span> and shape <span class="math inline">\(k\)</span>,</p>
<p><span class="math display">\[
X_i \sim \operatorname{NegBin}(\mu, k), \qquad \operatorname{Var}(X_i)=\mu+\frac{\mu^2}{k},
\]</span></p>
<p>and assume that the quadrats are i.i.d. Neighbouring quadrats of a grid are likely to resemble each other, so this is a simplification, as it was for the visits to owl nests in the Chapter 3 practical (models for observations that are not independent start in <a href="../../Chapter_7/Theory.qmd">Chapter 7</a>).</p>
<ol type="1">
<li>Estimate <span class="math inline">\(\mu\)</span> and <span class="math inline">\(k\)</span> with the method of moments, as in the Chapter 3 practical. Also calculate the fraction of quadrats without seedlings and the largest count.</li>
<li>Write the NLL of the model with <span class="math inline">\(\log\mu\)</span> and <span class="math inline">\(\log k\)</span> as parameters and minimise it with <code>optim()</code>, using the method-of-moments estimates as starting values and <code>hessian = TRUE</code>. Report the estimates on the original scale. Compare the log-likelihood at the maximum likelihood estimates with the log-likelihood at the method-of-moments estimates.</li>
<li>Calculate the log-likelihood on a grid of values of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(k\)</span> with two nested <code>for</code> loops and draw the contours of the relative log-likelihood with <code>contour()</code>. Add both pairs of estimates and the contour of the approximate joint 95% confidence region. Is the method-of-moments estimate inside the region?</li>
<li>Calculate a 95% Wald interval for <span class="math inline">\(k\)</span> (on the log scale, with the endpoints transformed back) and a 95% profile likelihood interval for <span class="math inline">\(k\)</span> with <code>uniroot()</code>. Compare them.</li>
<li>Plot the relative frequencies of the counts together with the probabilities of the fitted Negative Binomial model and of a Poisson model. Compare the fraction of empty quadrats under each model with the observed fraction, and compare the two models with AIC and with its small-sample correction AICc (see <a href="../../Chapter_4/Theory.html#sec-aic">Model comparison with AIC</a>).</li>
</ol>
</section>
<section id="exercise-3-empty-quadrats-and-zero-inflation" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Exercise 3: Empty quadrats and zero inflation</h1>
<p>About half of the quadrats of Exercise 2 have no seedlings. The Negative Binomial model describes this with a small shape <span class="math inline">\(k\)</span>. A different explanation is that a fraction of the quadrats cannot have seedlings at all (for example, because no seeds arrive there), while the counts in the rest follow a Poisson distribution. This is a zero-inflated Poisson model (see <a href="../../Supplements/distributions.html#sec-zero_inflated">How to make zero-inflated distributions</a> in the supplement). Its probability mass function is</p>
<p><span class="math display">\[
P(X=x\mid\lambda,p_0)=
\begin{cases}
p_0+(1-p_0)\,e^{-\lambda}, &amp; x=0,\\[4pt]
(1-p_0)\,\dfrac{e^{-\lambda}\lambda^{x}}{x!}, &amp; x&gt;0,
\end{cases}
\]</span></p>
<p>where <span class="math inline">\(p_0\)</span> (<code>pzero</code> in the code of the supplement) is the probability that a quadrat cannot have seedlings and <span class="math inline">\(\lambda\)</span> is the mean number of seedlings in the quadrats that can have them. Use the same counts as in Exercise 2 and the same assumption of i.i.d. quadrats.</p>
<ol type="1">
<li>Write a function <code>dzipois(x, lambda, pzero, log = FALSE)</code> that returns the probability mass of the zero-inflated Poisson distribution, or its logarithm when <code>log = TRUE</code>. Check that the probabilities add up to one over a wide range of counts, for two combinations of parameter values.</li>
<li>Write the NLL with <span class="math inline">\(\log\lambda\)</span> and <span class="math inline">\(\operatorname{logit}p_0\)</span> as parameters. Choose starting values from the data (think of the fraction of empty quadrats and of the mean of the quadrats that are not empty) and fit the model with <code>optim()</code>. Interpret both estimates.</li>
<li>Compare the zero-inflated Poisson model with the Negative Binomial model of Exercise 2 using AIC and AICc. What does the comparison come down to when both models have the same number of parameters?</li>
<li>Plot the probabilities of both fitted models over the relative frequencies of the counts. Under each model, calculate the probability of an empty quadrat and the probability of 20 or more seedlings, and compare them with the observed fractions. What does each model say about how the counts arise? Can the comparison identify the ecological cause of the empty quadrats?</li>
</ol>
</section>
<section id="exercise-4-timber-volume-and-body-mass" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Exercise 4: Timber volume and body mass</h1>
<p>This exercise fits models to continuous measurements, so the contributions to the likelihood are densities. We use a <a href="../../Supplements/distributions.html#sec-gamma">Gamma</a> model with shape <span class="math inline">\(k\)</span> and rate <span class="math inline">\(r\)</span> (<code>shape</code> and <code>rate</code> in R), for which</p>
<p><span class="math display">\[
X_i \sim \operatorname{Gamma}(k, r), \qquad E[X_i]=\frac{k}{r},
\qquad \operatorname{Var}(X_i)=\frac{k}{r^2}.
\]</span></p>
<p>The first three questions use the data set <code>trees</code> of the Chapter 3 practical, with the measurements of 31 felled black cherry trees. That practical used their heights. Here <span class="math inline">\(X_i\)</span> is the volume of timber of tree <span class="math inline">\(i\)</span> in cubic feet (ft³), the column <code>Volume</code>. The last two questions use the data set <code>penguins</code>, which is part of the <code>datasets</code> package in R 4.5.0 and later.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> It contains measurements of adult penguins of three species near Palmer Station, Antarctica (Gorman, Williams and Fraser 2014). There <span class="math inline">\(X_i\)</span> is the body mass of Adelie penguin <span class="math inline">\(i\)</span>, the column <code>body_mass</code>, in grams. In both cases we assume that the observations are i.i.d.</p>
<ol type="1">
<li>Load the trees with <code>data(trees, package = "datasets")</code>. Write the NLL of the Gamma model with <code>dgamma(..., log = TRUE)</code> and with <span class="math inline">\(\log k\)</span> and <span class="math inline">\(\log r\)</span> as parameters. Calculate method-of-moments estimates from the formulas of the mean and the variance, use them as starting values and fit the model with <code>optim()</code> and <code>hessian = TRUE</code>. Report the estimates of <span class="math inline">\(k\)</span> and <span class="math inline">\(r\)</span> with their units and the maximum likelihood estimate of the mean volume.</li>
<li>Calculate the correlation between the estimates of <span class="math inline">\(\log k\)</span> and <span class="math inline">\(\log r\)</span> from the Hessian. Calculate the log-likelihood on a grid of values of <span class="math inline">\(k\)</span> and <span class="math inline">\(r\)</span> and draw the contours of the relative log-likelihood. What does the tilt of the contours mean?</li>
<li>Calculate a slice and a profile of the log-likelihood for the shape <span class="math inline">\(k\)</span> and plot both as relative log-likelihoods. Find the range of values of <span class="math inline">\(k\)</span> for which each curve is within 1.92 units of the maximum. Which of the two ranges is a confidence interval, and why is the slice narrower?</li>
<li>Load the penguins with <code>data(penguins, package = "datasets")</code> and keep the body masses of the Adelie penguins. One of them is missing: remove it explicitly. Fit the Gamma model to the masses in grams and again to the same masses in kilograms. With the masses in grams the NLL is a large number, and the default stopping rule of <code>optim()</code> can end the search too early, so add the argument <code>control = list(reltol = 1e-12)</code> to both fits (if R prints “NaNs produced” during the search, see the callout <a href="../../Chapter_4/Theory.html#sec-maximum-likelihood">When a fit fails or prints warnings</a>). Compare the estimates and the maximum log-likelihoods of the two fits. Explain the differences with the units of a density.</li>
<li>Fit a <a href="../../Supplements/distributions.html#sec-lognormal">LogNormal</a> model to the body masses with <code>dlnorm()</code> and <code>optim()</code>, in grams and in kilograms, and compare it with the Gamma model using AIC and AICc. Does the comparison depend on the units?</li>
</ol>
</section>
<section id="exercise-5-estimators-and-intervals-across-hypothetical-experiments" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Exercise 5: Estimators and intervals across hypothetical experiments</h1>
<p>This exercise is extra practice. With a single sample we cannot tell how far an estimate is from the parameter, or whether a confidence interval contains it, because the parameter is unknown. As in Exercise 3 of the Chapter 3 practical, we can study the behaviour of an estimator by simulating hypothetical experiments from a model whose parameters we know. Here we use the maximum likelihood estimates of Exercise 4 as the parameters of that model. The simulation then shows how the estimators and the intervals would behave if the fitted Gamma model had generated the data (see <a href="../../Chapter_4/Theory.html#sec-mle_properties">Properties of maximum likelihood estimators</a> and <a href="../../Chapter_4/Theory.html#sec-likelihood-uncertainty">Uncertainty from the likelihood</a>). This exercise continues with the objects of Exercise 4. The function that runs the simulation is given below the questions with three gaps, which you fill in.</p>
<ol type="1">
<li>For the shape <span class="math inline">\(k\)</span> of the Gamma model fitted to the tree volumes, calculate a 95% Wald interval (on the log scale, with the endpoints transformed back) and a 95% profile likelihood interval with <code>uniroot()</code>. Compare them.</li>
<li>Complete the first gap of the function <code>simulate_gamma_experiments()</code> below. Set seed 801 and simulate 2,000 hypothetical experiments, each with 31 trees from a Gamma model whose shape and rate are the maximum likelihood estimates of Exercise 4. For each experiment, the function estimates the shape by the method of moments and by maximum likelihood (the fit starts at the method-of-moments estimates and uses <code>control = list(reltol = 1e-12)</code>, as in Exercise 4). Compare the mean, the standard deviation and the mean squared error of the two estimators with the shape that you used to simulate. Tip: the function has the sample size, the shape and the rate as arguments because you will need it again in question 4.</li>
<li>Complete the second and the third gap, which record for each experiment whether the Wald interval and the profile likelihood interval for the shape contain the shape that you used to simulate, and calculate the coverage of both intervals. Hint: you do not need <code>uniroot()</code> inside the simulation. A profile likelihood interval contains a value whenever the profile log-likelihood at that value is within <code>qchisq(p = 0.95, df = 1) / 2</code> of the maximum log-likelihood, so one extra fit with the shape fixed at that value is enough.</li>
<li>Set seed 802 and repeat questions 2 and 3 with experiments of 151 penguins from the Gamma model fitted to the body masses in grams. How do the bias and the coverage change? The two simulations differ in the sample size and in the model. How can you check which of the two explains the change? Do it, without resetting the seed.</li>
<li>Why do these results only approximate the behaviour of the estimators and the intervals for the real trees and penguins?</li>
</ol>
<p>The function below needs <code>gamma_nll()</code> and <code>gamma_nll_given_shape()</code> from Exercise 4, and the objects <code>critical_value</code> and <code>cutoff</code> (the critical value of the standard Normal distribution and the cutoff of the relative log-likelihood for a 95% interval). It stores the results of every experiment in one row of a data frame. In each gap, replace <code>NA</code> by your own code. The lines that follow a gap use the names of the objects that the gap creates, so keep those names.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One simulation of hypothetical experiments from a Gamma model whose parameters we know.</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="co"># For each experiment: the maximum likelihood and the method-of-moments estimates of the</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="co"># shape, and whether the Wald interval (log scale) and the profile interval contain the</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="co"># shape that was used to simulate.</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>simulate_gamma_experiments <span class="ot">=</span> <span class="cf">function</span>(n_obs, shape, rate, n_experiments) {</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  results <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape_ml =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="at">times =</span> n_experiments),</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape_mom =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="at">times =</span> n_experiments),</span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">wald_covered =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="at">times =</span> n_experiments),</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">profile_covered =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="at">times =</span> n_experiments),</span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">converged =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="at">times =</span> n_experiments)</span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (e <span class="cf">in</span> <span class="fu">seq_len</span>(n_experiments)) {</span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># One hypothetical experiment and its method-of-moments estimates.</span></span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">=</span> <span class="fu">rgamma</span>(<span class="at">n =</span> n_obs, <span class="at">shape =</span> shape, <span class="at">rate =</span> rate)</span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a>    x_mean <span class="ot">=</span> <span class="fu">mean</span>(x)</span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a>    x_variance <span class="ot">=</span> <span class="fu">mean</span>((x <span class="sc">-</span> x_mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a>    shape_mom <span class="ot">=</span> x_mean<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> x_variance</span>
<span id="cb64-19"><a href="#cb64-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># GAP 1: maximum likelihood fit of the Gamma model to x with optim(), started at the</span></span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># method-of-moments estimates of the shape and the rate (on the log scale), with</span></span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># method = "BFGS", hessian = TRUE and control = list(reltol = 1e-12). Store the result</span></span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># in an object called fit.</span></span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">=</span> <span class="cn">NA</span></span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a>    shape_ml <span class="ot">=</span> <span class="fu">exp</span>(fit<span class="sc">$</span>par[<span class="dv">1</span>])</span>
<span id="cb64-26"><a href="#cb64-26" aria-hidden="true" tabindex="-1"></a>    se_log_shape <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fu">solve</span>(fit<span class="sc">$</span>hessian)[<span class="dv">1</span>, <span class="dv">1</span>])</span>
<span id="cb64-27"><a href="#cb64-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-28"><a href="#cb64-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># The Wald interval contains the shape when the estimate is within the critical value</span></span>
<span id="cb64-29"><a href="#cb64-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># of standard errors on the log scale. The profile interval contains it when the</span></span>
<span id="cb64-30"><a href="#cb64-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># relative profile log-likelihood at that shape is within the cutoff.</span></span>
<span id="cb64-31"><a href="#cb64-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-32"><a href="#cb64-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># GAP 2: TRUE when the Wald interval contains the shape that was used to simulate.</span></span>
<span id="cb64-33"><a href="#cb64-33" aria-hidden="true" tabindex="-1"></a>    wald_covered <span class="ot">=</span> <span class="cn">NA</span></span>
<span id="cb64-34"><a href="#cb64-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-35"><a href="#cb64-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># GAP 3: fit the model with the shape fixed at the shape that was used to simulate,</span></span>
<span id="cb64-36"><a href="#cb64-36" aria-hidden="true" tabindex="-1"></a>    <span class="co"># which re-estimates the rate only (use gamma_nll_given_shape() with method = "BFGS"</span></span>
<span id="cb64-37"><a href="#cb64-37" aria-hidden="true" tabindex="-1"></a>    <span class="co"># and control = list(reltol = 1e-12), starting at the estimate of log(rate) of fit),</span></span>
<span id="cb64-38"><a href="#cb64-38" aria-hidden="true" tabindex="-1"></a>    <span class="co"># and store it in an object called inner_fit. Then record in profile_covered whether the</span></span>
<span id="cb64-39"><a href="#cb64-39" aria-hidden="true" tabindex="-1"></a>    <span class="co"># relative profile log-likelihood at that shape is within the cutoff.</span></span>
<span id="cb64-40"><a href="#cb64-40" aria-hidden="true" tabindex="-1"></a>    inner_fit <span class="ot">=</span> <span class="cn">NA</span></span>
<span id="cb64-41"><a href="#cb64-41" aria-hidden="true" tabindex="-1"></a>    profile_covered <span class="ot">=</span> <span class="cn">NA</span></span>
<span id="cb64-42"><a href="#cb64-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-43"><a href="#cb64-43" aria-hidden="true" tabindex="-1"></a>    results<span class="sc">$</span>shape_ml[e] <span class="ot">=</span> shape_ml</span>
<span id="cb64-44"><a href="#cb64-44" aria-hidden="true" tabindex="-1"></a>    results<span class="sc">$</span>shape_mom[e] <span class="ot">=</span> shape_mom</span>
<span id="cb64-45"><a href="#cb64-45" aria-hidden="true" tabindex="-1"></a>    results<span class="sc">$</span>wald_covered[e] <span class="ot">=</span> wald_covered</span>
<span id="cb64-46"><a href="#cb64-46" aria-hidden="true" tabindex="-1"></a>    results<span class="sc">$</span>profile_covered[e] <span class="ot">=</span> profile_covered</span>
<span id="cb64-47"><a href="#cb64-47" aria-hidden="true" tabindex="-1"></a>    results<span class="sc">$</span>converged[e] <span class="ot">=</span> fit<span class="sc">$</span>convergence <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;&amp;</span> inner_fit<span class="sc">$</span>convergence <span class="sc">==</span> <span class="dv">0</span></span>
<span id="cb64-48"><a href="#cb64-48" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb64-49"><a href="#cb64-49" aria-hidden="true" tabindex="-1"></a>  results</span>
<span id="cb64-50"><a href="#cb64-50" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>With an older version of R, install the package <code>palmerpenguins</code> and load the data with <code>data(penguins, package = "palmerpenguins")</code>. It contains the same measurements, but the column with the body mass is called <code>body_mass_g</code>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>