<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>From samples to estimates – Ecological Models and Data Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-24c09a13944ec7e1f31d2917b1251fc2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Chapter_1/Theory.html">Theory</a></li><li class="breadcrumb-item"><a href="../Chapter_3/Theory.html">Chapter 3</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Ecological Models and Data Analysis</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_1/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_2/Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_3/Theory.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Practicals</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_1/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_2/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_3/Practicals/no_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Solutions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_1/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_2/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter_3/Practicals/solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplements</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Supplements/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Supplements/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link" data-scroll-target="#learning-goals"><span class="header-section-number">2</span> Learning goals</a></li>
  <li><a href="#sec-samples" id="toc-sec-samples" class="nav-link" data-scroll-target="#sec-samples"><span class="header-section-number">3</span> Samples and distributions</a>
  <ul class="collapse">
  <li><a href="#from-frequency-to-probability" id="toc-from-frequency-to-probability" class="nav-link" data-scroll-target="#from-frequency-to-probability"><span class="header-section-number">3.1</span> From frequency to probability</a></li>
  <li><a href="#empirical-distribution" id="toc-empirical-distribution" class="nav-link" data-scroll-target="#empirical-distribution"><span class="header-section-number">3.2</span> Empirical distribution</a>
  <ul class="collapse">
  <li><a href="#mean-variance-and-quantiles-of-a-data-sample" id="toc-mean-variance-and-quantiles-of-a-data-sample" class="nav-link" data-scroll-target="#mean-variance-and-quantiles-of-a-data-sample"><span class="header-section-number">3.2.1</span> Mean, variance and quantiles of a data sample</a></li>
  <li><a href="#asymptotic-convergence-of-the-empirical-distribution" id="toc-asymptotic-convergence-of-the-empirical-distribution" class="nav-link" data-scroll-target="#asymptotic-convergence-of-the-empirical-distribution"><span class="header-section-number">3.2.2</span> Asymptotic convergence of the empirical distribution</a></li>
  </ul></li>
  <li><a href="#sec-continuous_samples" id="toc-sec-continuous_samples" class="nav-link" data-scroll-target="#sec-continuous_samples"><span class="header-section-number">3.3</span> Samples of continuous measurements</a></li>
  </ul></li>
  <li><a href="#sec-estimates" id="toc-sec-estimates" class="nav-link" data-scroll-target="#sec-estimates"><span class="header-section-number">4</span> Parameters, estimators and estimates</a>
  <ul class="collapse">
  <li><a href="#method-of-moments" id="toc-method-of-moments" class="nav-link" data-scroll-target="#method-of-moments"><span class="header-section-number">4.1</span> Method of moments</a></li>
  </ul></li>
  <li><a href="#sec-sampling_distribution" id="toc-sec-sampling_distribution" class="nav-link" data-scroll-target="#sec-sampling_distribution"><span class="header-section-number">5</span> Sampling distributions</a>
  <ul class="collapse">
  <li><a href="#bias-and-variance" id="toc-bias-and-variance" class="nav-link" data-scroll-target="#bias-and-variance"><span class="header-section-number">5.1</span> Bias and variance</a></li>
  <li><a href="#mean-squared-error" id="toc-mean-squared-error" class="nav-link" data-scroll-target="#mean-squared-error"><span class="header-section-number">5.2</span> Mean squared error</a></li>
  </ul></li>
  <li><a href="#sec-standard_errors" id="toc-sec-standard_errors" class="nav-link" data-scroll-target="#sec-standard_errors"><span class="header-section-number">6</span> Standard errors</a></li>
  <li><a href="#sec-confidence_intervals" id="toc-sec-confidence_intervals" class="nav-link" data-scroll-target="#sec-confidence_intervals"><span class="header-section-number">7</span> Confidence intervals</a>
  <ul class="collapse">
  <li><a href="#coverage-checked-by-simulation" id="toc-coverage-checked-by-simulation" class="nav-link" data-scroll-target="#coverage-checked-by-simulation"><span class="header-section-number">7.1</span> Coverage checked by simulation</a></li>
  </ul></li>
  <li><a href="#sec-two_parameters" id="toc-sec-two_parameters" class="nav-link" data-scroll-target="#sec-two_parameters"><span class="header-section-number">8</span> Estimation of two parameters</a>
  <ul class="collapse">
  <li><a href="#method-of-moments-for-the-mean-and-the-variance" id="toc-method-of-moments-for-the-mean-and-the-variance" class="nav-link" data-scroll-target="#method-of-moments-for-the-mean-and-the-variance"><span class="header-section-number">8.1</span> Method of moments for the mean and the variance</a></li>
  </ul></li>
  <li><a href="#sec-large_samples" id="toc-sec-large_samples" class="nav-link" data-scroll-target="#sec-large_samples"><span class="header-section-number">9</span> Consistency and asymptotic normality</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">10</span> Summary</a></li>
  <li><a href="#chapter-quiz" id="toc-chapter-quiz" class="nav-link" data-scroll-target="#chapter-quiz"><span class="header-section-number">11</span> Chapter quiz</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Chapter_1/Theory.html">Theory</a></li><li class="breadcrumb-item"><a href="../Chapter_3/Theory.html">Chapter 3</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">From samples to estimates</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>In this chapter, we learn how to relate samples of data to probability distributions and how to use a sample to estimate the parameters of a model. In <a href="../Chapter_2/Theory.html">Chapter 2</a> we chose the parameters of a distribution and calculated probabilities, quantiles and expectations from them. In research we face the reverse problem: we have a limited sample of observations and we want to learn about the parameters of the model that we use to describe them.</p>
<p>The chapter has two parts. First we look at how samples and distributions are related, through relative frequencies and the empirical distribution of a sample, both for counts and for continuous measurements. We then define estimators and study how their estimates vary across repeated hypothetical experiments, which leads to standard errors and confidence intervals. The first part continues with the Binomial model of seed survival from Chapter 2. The second part uses a Poisson model for counts of seedlings and a Normal model for tree heights. Most of the data in this chapter are simulated, because in a simulation we know the parameters that generated each sample and we can compare the estimates with them.</p>
</section>
<section id="learning-goals" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Learning goals</h1>
<p>In this chapter, we will cover:</p>
<ul>
<li>how samples and distributions are related (relative frequencies and the empirical distribution);</li>
<li>histograms, density estimates and empirical cumulative distributions for continuous measurements;</li>
<li>parameters, estimators and estimates;</li>
<li>the method of moments;</li>
<li>the sampling distribution of an estimator, its bias, variance and mean squared error;</li>
<li>standard errors;</li>
<li>confidence intervals and their coverage;</li>
<li>consistency and asymptotic normality.</li>
</ul>
<p>We will use the Binomial, Poisson and Normal distributions throughout the chapter. They are described in the <a href="../Supplements/distributions.html">Supplement</a>.</p>
</section>
<section id="sec-samples" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Samples and distributions</h1>
<p>So far we have been working with mathematical models: we calculate probabilities and expectations of distributions. But in research we collect limited, often noisy, samples of data and want to generalise from these observations to the broader context in which they were collected. As discussed in Chapter 1, we use statistical models as approximations for the data generating process. This means that we treat the observations from our experiments as if they were random samples from our statistical model. In this section we learn in more detail about this relationship as it will be the basis for the rest of this chapter.</p>
<p>For example, we might want to learn about seed survival across a restoration site while observing only some quadrats. We cannot quietly turn those observed quadrats into a claim about the whole site. To make that connection, we need assumptions about how quadrats were selected and how their counts vary from quadrat to quadrat. We model this data generating process with a distribution that is (at least qualitatively) compatible with that process.</p>
<section id="from-frequency-to-probability" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="from-frequency-to-probability"><span class="header-section-number">3.1</span> From frequency to probability</h2>
<p>For a sample of counts, the <strong>relative frequency</strong> of a value is the number of times it appears divided by the sample size. Let’s simulate ten quadrats from the Binomial model of seed survival used in <a href="../Chapter_2/Theory.html#sec-four_faces">Chapter 2</a> (four seeds per quadrat, each surviving with probability 0.4):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters of the Binomial model of seed survival used in Chapter 2.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>seed_count <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>seed_survival_probability <span class="ot">=</span> <span class="fl">0.4</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate ten quadrats from the Binomial model.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="at">seed =</span> <span class="dv">123</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>n_quadrats <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>sample_survivors <span class="ot">=</span> <span class="fu">rbinom</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_quadrats,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> seed_count,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> seed_survival_probability</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>table()</code> counts how often each value appears. Divide by the number of quadrats to calculate relative frequencies:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count each possible value and divide by the sample size.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>seed_values <span class="ot">=</span> <span class="fu">seq.int</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> seed_count)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>count_survivors <span class="ot">=</span> <span class="fu">table</span>(<span class="fu">factor</span>(<span class="at">x =</span> sample_survivors, <span class="at">levels =</span> seed_values))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>relative_frequency <span class="ot">=</span> count_survivors <span class="sc">/</span> <span class="fu">length</span>(sample_survivors)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>relative_frequency</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1   2   3   4 
0.1 0.3 0.3 0.3 0.0 </code></pre>
</div>
</div>
<p>Some possible counts may be absent from a small sample. Setting all possible values as <code>factor()</code> levels makes <code>table()</code> include those counts with frequency zero.</p>
<p>The relative frequencies lie between zero and one and sum to one. Compare them with the probabilities predicted by the Binomial model that we use to approximate the data generating process:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Put the sample frequencies beside the model probabilities for comparison.</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed_count =</span> seed_values,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">relative_frequency =</span> <span class="fu">as.numeric</span>(<span class="at">x =</span> relative_frequency),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">probability =</span> <span class="fu">dbinom</span>(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> seed_values,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> seed_count,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> seed_survival_probability</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  seed_count relative_frequency probability
1          0                0.1      0.1296
2          1                0.3      0.3456
3          2                0.3      0.3456
4          3                0.3      0.1536
5          4                0.0      0.0256</code></pre>
</div>
</div>
<p>The two columns differ because the sample contains only ten quadrats. That is not a failure of the model: it is what sampling variation looks like. For small sample sizes, the relative frequencies and model probabilities can differ greatly. However, for independent and identically distributed (i.i.d.) observations, the relative frequency of each count approaches its model probability as sample size grows. This is a consequence of the <strong>Glivenko–Cantelli theorem</strong>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>For example, let <span class="math inline">\(I_i=1\)</span> when the <span class="math inline">\(i\)</span>th quadrat has exactly three surviving seeds and <span class="math inline">\(I_i=0\)</span> otherwise. The relative frequency of three survivors is <span class="math inline">\(\bar{I}_n=(I_1+\cdots+I_n)/n\)</span>. For any positive margin <span class="math inline">\(\varepsilon\)</span>,</p>
<p><span class="math display">\[
\lim_{n \to \infty}
P\left(\left|\bar{I}_n - P(X=3)\right| \ge \varepsilon\right)=0.
\]</span></p>
<p>In plain English, as <span class="math inline">\(n\)</span> grows, the chance that the relative frequency differs from the model probability by at least <span class="math inline">\(\varepsilon\)</span> becomes small. There are two probabilities here: the probability assigned to a count by the model, and the probability of seeing a relative frequency that is far from the model one. This convergence is not deterministic: a larger realised sample need not be closer to the model probability than every smaller realised sample.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Frequencies converge to probabilities">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Frequencies converge to probabilities
</div>
</div>
<div class="callout-body-container callout-body">
<p>For independent observations from the same distribution, the relative frequency of any specified value converges in probability to its probability mass as sample size grows.</p>
</div>
</div>
<p>We can push the simulation further and compare relative frequencies at sample sizes from 10 to 100,000 to see this convergence in action:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare relative frequencies for several sample sizes with the model.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="ot">=</span> <span class="dv">10</span><span class="sc">^</span>(<span class="fu">seq_len</span>(<span class="at">length.out =</span> <span class="dv">5</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>seed_values <span class="ot">=</span> <span class="fu">seq.int</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> seed_count)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>all_frequencies <span class="ot">=</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="fu">length</span>(seed_values),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">ncol =</span> <span class="fu">length</span>(sample_sizes) <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(all_frequencies) <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">as.character</span>(sample_sizes), <span class="st">"theory"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(sample_sizes)) {</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  sample_survivors <span class="ot">=</span> <span class="fu">rbinom</span>(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> sample_sizes[i],</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> seed_count,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> seed_survival_probability</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  count_survivors <span class="ot">=</span> <span class="fu">table</span>(<span class="fu">factor</span>(</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> sample_survivors,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">levels =</span> seed_values</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  all_frequencies[, i] <span class="ot">=</span> <span class="fu">as.numeric</span>(count_survivors) <span class="sc">/</span> sample_sizes[i]</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>all_frequencies[, <span class="fu">length</span>(sample_sizes) <span class="sc">+</span> <span class="dv">1</span>] <span class="ot">=</span> <span class="fu">dbinom</span>(</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> seed_values,</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> seed_count,</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> seed_survival_probability</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(all_frequencies, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      10  100  1000 10000 1e+05 theory
[1,] 0.1 0.11 0.129 0.125 0.130  0.130
[2,] 0.3 0.39 0.348 0.352 0.347  0.346
[3,] 0.3 0.35 0.359 0.347 0.344  0.346
[4,] 0.3 0.13 0.138 0.152 0.153  0.154
[5,] 0.0 0.02 0.026 0.024 0.026  0.026</code></pre>
</div>
</div>
<p>One sequence of samples cannot show convergence directly. For example, the relative frequency of three surviving seeds at 10,000 quadrats can happen to be closer to the model probability than its value at 100,000 quadrats. To show what usually changes with sample size, repeat the simulation 100 times at each size. This is shown in <a href="#fig-relative-frequency-convergence" class="quarto-xref">Figure&nbsp;1</a>. At small sample sizes, the repeated relative frequencies cover a wide range. As the sample size grows, the relative frequencies concentrate around the probabilities of the model. Individual samples can still generate values far from the line, but large deviations become less likely.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-relative-frequency-convergence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-relative-frequency-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-relative-frequency-convergence-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-relative-frequency-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Relative frequencies of exactly three surviving seeds for simulated samples of different sizes. The horizontal line is the probability assigned by the Binomial distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: fruit-set frequency">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: fruit-set frequency
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a sample of 24 tagged orchid flowers, 15 set fruit. Calculate the relative frequency of fruit set. Explain what this value estimates and why it need not equal the model fruit-set probability exactly.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The relative frequency is <span class="math inline">\(15/24=0.625\)</span>. It is not equal to the probability assigned by the model to that count, but it is probably not too different for a sample of 24.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="empirical-distribution" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="empirical-distribution"><span class="header-section-number">3.2</span> Empirical distribution</h2>
<p>Because of this relationship between the relative frequencies and probabilities, we often define the <strong>empirical distribution</strong> of a sample.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> This is a procedure where we assign each observed count its relative frequency and we treat it as if it were a probability mass function (<a href="#fig-ecdf" class="quarto-xref">Figure&nbsp;2</a>). In principle it is just a way to tabulate a (potentially long) collection of observations, but we will see that this also facilitates calculating properties of a sample such as quantiles or expectations that we can relate to the equivalent properties of the model.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Empirical distribution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Empirical distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>A distribution whose mass at each count equals the relative frequency in the sample.</p>
</div>
</div>
<p>The empirical distribution is also important because, generally speaking<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>, a sample whose empirical distribution matches well the model distribution will generate reasonable estimates of the model’s parameters with relatively low uncertainty. In this we would say that the “sample is representative” of the process we are trying to model. This is why it is crucial to avoid introducing biases in the way we collect data from experiment (motivating procedures such as randomisation).</p>
<p>Like any distribution, an empirical distribution has a cumulative function: the fraction of observations at or below each count. When comparing the empirical and model cumulative probability functions, we often use step-plots, which easily allow both functions side by side (<a href="#fig-ecdf" class="quarto-xref">Figure&nbsp;2</a>). These types of visualisations are useful if you want to compare how well a distribution matches a given sample of data (i.e., we want to test if a sample of observations could be treated as a random sample from a given distribution). We will expand on this notion in later chapters.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ecdf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ecdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-ecdf-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ecdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Empirical and model distribution for a sample of ten quadrats in the example on seed survival.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="mean-variance-and-quantiles-of-a-data-sample" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="mean-variance-and-quantiles-of-a-data-sample"><span class="header-section-number">3.2.1</span> Mean, variance and quantiles of a data sample</h3>
<p>Just like for any probability distribution described in <a href="../Chapter_2/Theory.html#sec-expectations">Chapter 2</a>, we can compute expectations such as means and variances from an empirical distribution, as well as quantiles by inverting the empirical cumulative distribution. We will simply replace probabilities in the formulae by relative frequencies of the sample.</p>
<p>Note that, strictly speaking, a data sample is just a collection of values. It does not have a mean or a variance; those are properties of distributions. However, language in applied statistics is often used lazily and inconsistently, which can lead to a lot of confusion. Whenever we say <em>sample mean</em> or <em>sample variance</em> we actually imply the mean or variance of the empirical distribution (but see below that the variance of a sample is an even more confusing term).</p>
<p>It is trivial to see that the mean of the empirical distribution equals the arithmetic mean of the sample:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate a small sample and calculate its weighted and ordinary means.</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>n_quadrats <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>seed_count <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>seed_survival_probability <span class="ot">=</span> <span class="fl">0.4</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>seed_values <span class="ot">=</span> <span class="fu">seq.int</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> seed_count)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>sample_survivors <span class="ot">=</span> <span class="fu">rbinom</span>(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_quadrats, <span class="at">size =</span> seed_count, <span class="at">prob =</span> seed_survival_probability</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>count_survivors <span class="ot">=</span> <span class="fu">table</span>(<span class="fu">factor</span>(<span class="at">x =</span> sample_survivors, <span class="at">levels =</span> seed_values))</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>relative_frequency <span class="ot">=</span> <span class="fu">as.numeric</span>(count_survivors) <span class="sc">/</span> n_quadrats</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>weighted_average <span class="ot">=</span> <span class="fu">sum</span>(relative_frequency <span class="sc">*</span> seed_values)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="ot">=</span> <span class="fu">mean</span>(sample_survivors)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(weighted_average, sample_mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.8 1.8</code></pre>
</div>
</div>
<p>However, the variance of the empirical distribution is not exactly the same as what we normally call <em>sample variance</em>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the variance of the empirical distribution</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>empirical_variance <span class="ot">=</span> <span class="fu">sum</span>((seed_values <span class="sc">-</span> weighted_average)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> relative_frequency)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>sample_variance <span class="ot">=</span> <span class="fu">var</span>(sample_survivors)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(empirical_variance, sample_variance)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.960000 1.066667</code></pre>
</div>
</div>
<p>It turns out that what most people call sample variance is actually a statistical estimator of the variance of the model distribution (i.e., in this case the variance of the Binomial distribution), which is a completely different concept. For reasons that will become clear in <a href="#sec-two_parameters" class="quarto-xref">Section&nbsp;8</a>, this variance is calculated with a different formula<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p>A quantile from the empirical distribution can be derived from the <code>quantile()</code> function. Note that when dealing with discrete data you need to use <code>type = 1</code> as an argument. For example, if we calculate the quantile for a cumulative probability of 0.5 (i.e.&nbsp;the median) it will return the smallest observed count whose empirical cumulative probability reaches <span class="math inline">\(0.5\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use type = 1 so the empirical quantile is one of the observed counts.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(<span class="at">x =</span> sample_survivors, <span class="at">probs =</span> <span class="fl">0.5</span>, <span class="at">type =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>50% 
  2 </code></pre>
</div>
</div>
<p>The function <code>quantile()</code> appears in many areas of statistics, and there are up to nine different ways of computing it in R. So the purpose for which we calculate the quantile really matters.</p>
</section>
<section id="asymptotic-convergence-of-the-empirical-distribution" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="asymptotic-convergence-of-the-empirical-distribution"><span class="header-section-number">3.2.2</span> Asymptotic convergence of the empirical distribution</h3>
<div class="callout callout-style-default callout-note callout-titled" title="Asymptotic convergence of empirical distribution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Asymptotic convergence of empirical distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>For independent observations from the same fixed distribution, the empirical probability mass function converges to the model probability mass function as sample size grows towards infinity. All the moments (means, variances, and others), as well as all quantiles from the empirical distribution, will also converge to their equivalent values in the model. With bounded counts, as in our Binomial example, the empirical mean and variance also converge to the values in the model. A finite sample can sometimes agree exactly; agreement is not guaranteed at any finite size.</p>
</div>
</div>
<p>By defining the empirical distribution we can now better understand how samples and distributions are related. That is, a collection of observations can be treated as a random sample from a model if the empirical distribution converges to that model as sample size increases. This does not imply that the observations are actual random samples from some mathematical stochastic representation; it simply means that we have modelled the variation across different observations correctly.</p>
<p>Note that in practice we can never verify this relationship as we will never have infinite samples and for any finite size there can be deviations. But it does mean that the larger the sample, the better we can judge if we have a good model (<a href="#fig-ecdf-binom" class="quarto-xref">Figure&nbsp;3</a>). Also, larger samples are more <strong>stable</strong>, meaning that there will be less variation across hypothetical repetitions of the experiment, which will increase our confidence (reduce our uncertainty) in the results (we cover this in more detail in <a href="#sec-sampling_distribution" class="quarto-xref">Section&nbsp;5</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ecdf-binom" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ecdf-binom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-ecdf-binom-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ecdf-binom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Model probabilities and sample frequencies for 10 quadrats (top) and 1,000 quadrats (bottom).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: orchid flowering across plots">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: orchid flowering across plots
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose each restoration plot contains 12 orchid plants. Each plant flowers with probability 0.25, independently of the others. Let <span class="math inline">\(X\)</span> be the number of flowering plants in a plot. This is a Binomial model. Simulate counts for 12 plots and for 500 plots. For each sample, calculate the empirical mean and plot the empirical mass function. Compare both distributions with the model probability mass function. What changes in the result from the larger sample? How much can you rely on a single simulation?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>One possible simulation is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate the two sample sizes and compare each with the same model.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">246</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>plants_per_plot <span class="ot">=</span> <span class="dv">12</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>flowering_probability <span class="ot">=</span> <span class="fl">0.25</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>small_plot_counts <span class="ot">=</span> <span class="fu">rbinom</span>(</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">12</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> plants_per_plot,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> flowering_probability</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>large_plot_counts <span class="ot">=</span> <span class="fu">rbinom</span>(</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">500</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> plants_per_plot,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> flowering_probability</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(small_plot_counts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.416667</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(large_plot_counts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.98</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>count_values <span class="ot">=</span> <span class="fu">seq.int</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> plants_per_plot)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>small_plot_table <span class="ot">=</span> <span class="fu">table</span>(<span class="fu">factor</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> small_plot_counts,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> count_values</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>large_plot_table <span class="ot">=</span> <span class="fu">table</span>(<span class="fu">factor</span>(</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> large_plot_counts,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> count_values</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>small_frequency <span class="ot">=</span> <span class="fu">as.numeric</span>(small_plot_table) <span class="sc">/</span> <span class="fu">length</span>(small_plot_counts)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>large_frequency <span class="ot">=</span> <span class="fu">as.numeric</span>(large_plot_table) <span class="sc">/</span> <span class="fu">length</span>(large_plot_counts)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>model_mass <span class="ot">=</span> <span class="fu">dbinom</span>(</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> count_values,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> plants_per_plot,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> flowering_probability</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>small_frequency_data <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">flowering_plants =</span> count_values,</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">probability =</span> small_frequency,</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">series =</span> <span class="st">"12 plots"</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>large_frequency_data <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">flowering_plants =</span> count_values,</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">probability =</span> large_frequency,</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">series =</span> <span class="st">"500 plots"</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>model_mass_data <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">flowering_plants =</span> count_values,</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">probability =</span> model_mass,</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">series =</span> <span class="st">"Binomial model"</span></span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Use bars for one empirical distribution, points for the other, and lines for the model.</span></span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Set common axis limits</span></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>all_probabilities <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>  small_frequency_data<span class="sc">$</span>probability,</span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a>  large_frequency_data<span class="sc">$</span>probability,</span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a>  model_mass_data<span class="sc">$</span>probability</span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a>  <span class="cn">NA</span>,</span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlim =</span> <span class="fu">range</span>(count_values),</span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(all_probabilities)),</span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a>  <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb18-48"><a href="#cb18-48" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Flowering plants per plot"</span>,</span>
<span id="cb18-49"><a href="#cb18-49" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Probability or relative frequency"</span></span>
<span id="cb18-50"><a href="#cb18-50" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-51"><a href="#cb18-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-52"><a href="#cb18-52" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> count_values)</span>
<span id="cb18-53"><a href="#cb18-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-54"><a href="#cb18-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw bars for the small empirical distribution</span></span>
<span id="cb18-55"><a href="#cb18-55" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(</span>
<span id="cb18-56"><a href="#cb18-56" aria-hidden="true" tabindex="-1"></a>  small_frequency_data,</span>
<span id="cb18-57"><a href="#cb18-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rect</span>(</span>
<span id="cb18-58"><a href="#cb18-58" aria-hidden="true" tabindex="-1"></a>    flowering_plants <span class="sc">-</span> <span class="fl">0.35</span>,</span>
<span id="cb18-59"><a href="#cb18-59" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb18-60"><a href="#cb18-60" aria-hidden="true" tabindex="-1"></a>    flowering_plants <span class="sc">+</span> <span class="fl">0.35</span>,</span>
<span id="cb18-61"><a href="#cb18-61" aria-hidden="true" tabindex="-1"></a>    probability,</span>
<span id="cb18-62"><a href="#cb18-62" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">"grey"</span>,</span>
<span id="cb18-63"><a href="#cb18-63" aria-hidden="true" tabindex="-1"></a>    <span class="at">border =</span> <span class="dv">1</span></span>
<span id="cb18-64"><a href="#cb18-64" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-65"><a href="#cb18-65" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-66"><a href="#cb18-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-67"><a href="#cb18-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Add points for the large empirical distribution</span></span>
<span id="cb18-68"><a href="#cb18-68" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(</span>
<span id="cb18-69"><a href="#cb18-69" aria-hidden="true" tabindex="-1"></a>  large_frequency_data,</span>
<span id="cb18-70"><a href="#cb18-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(</span>
<span id="cb18-71"><a href="#cb18-71" aria-hidden="true" tabindex="-1"></a>    flowering_plants,</span>
<span id="cb18-72"><a href="#cb18-72" aria-hidden="true" tabindex="-1"></a>    probability,</span>
<span id="cb18-73"><a href="#cb18-73" aria-hidden="true" tabindex="-1"></a>    <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb18-74"><a href="#cb18-74" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="dv">2</span></span>
<span id="cb18-75"><a href="#cb18-75" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-76"><a href="#cb18-76" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-77"><a href="#cb18-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-78"><a href="#cb18-78" aria-hidden="true" tabindex="-1"></a><span class="co"># Add vertical lines for the model distribution</span></span>
<span id="cb18-79"><a href="#cb18-79" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(</span>
<span id="cb18-80"><a href="#cb18-80" aria-hidden="true" tabindex="-1"></a>  model_mass_data,</span>
<span id="cb18-81"><a href="#cb18-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">segments</span>(</span>
<span id="cb18-82"><a href="#cb18-82" aria-hidden="true" tabindex="-1"></a>    flowering_plants,</span>
<span id="cb18-83"><a href="#cb18-83" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb18-84"><a href="#cb18-84" aria-hidden="true" tabindex="-1"></a>    flowering_plants,</span>
<span id="cb18-85"><a href="#cb18-85" aria-hidden="true" tabindex="-1"></a>    probability,</span>
<span id="cb18-86"><a href="#cb18-86" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="dv">3</span></span>
<span id="cb18-87"><a href="#cb18-87" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-88"><a href="#cb18-88" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-89"><a href="#cb18-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-90"><a href="#cb18-90" aria-hidden="true" tabindex="-1"></a><span class="co"># Add one legend for all three series</span></span>
<span id="cb18-91"><a href="#cb18-91" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(</span>
<span id="cb18-92"><a href="#cb18-92" aria-hidden="true" tabindex="-1"></a>  <span class="st">"topright"</span>,</span>
<span id="cb18-93"><a href="#cb18-93" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"12 plots"</span>, <span class="st">"500 plots"</span>, <span class="st">"Binomial model"</span>),</span>
<span id="cb18-94"><a href="#cb18-94" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb18-95"><a href="#cb18-95" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"grey"</span>, <span class="cn">NA</span>, <span class="cn">NA</span>),</span>
<span id="cb18-96"><a href="#cb18-96" aria-hidden="true" tabindex="-1"></a>  <span class="at">border =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="cn">NA</span>, <span class="cn">NA</span>),</span>
<span id="cb18-97"><a href="#cb18-97" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="dv">16</span>, <span class="cn">NA</span>),</span>
<span id="cb18-98"><a href="#cb18-98" aria-hidden="true" tabindex="-1"></a>  <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb18-99"><a href="#cb18-99" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Theory_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The larger sample will generally give a more stable empirical distribution and mean closer to the values in the model. A particular simulation need not be closer in every summary, and the empirical distribution need not exactly match the model.</p>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-continuous_samples" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-continuous_samples"><span class="header-section-number">3.3</span> Samples of continuous measurements</h2>
<p>The relationship between samples and distributions is the same for continuous measurements, but the tools to describe a sample need to be adapted. In a sample of continuous values we do not expect any value to be repeated, so the relative frequency of every observed value is <span class="math inline">\(1/n\)</span> and a table of relative frequencies tells us nothing. We will use the Normal model of tree height from <a href="../Chapter_2/Theory.html#sec-continuous_four_faces">Chapter 2</a>, with a mean of 22 m and a standard deviation of 4 m, to illustrate how to describe a sample of continuous data. We simulate the heights of 200 trees from this model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate the heights (in m) of 200 trees from the Normal model.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="at">seed =</span> <span class="dv">73</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>height_sample <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">200</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A <strong>histogram</strong> is the continuous counterpart of the table of relative frequencies. We divide the range of the measurements into intervals (called <strong>bins</strong>) and count the observations that fall in each bin. Dividing the count by the sample size gives the relative frequency of the bin, which we can compare with the probability that the model assigns to that interval. For example, for heights between 20 and 22 m:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Relative frequency of heights between 20 and 22 m in the sample.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(height_sample <span class="sc">&gt;</span> <span class="dv">20</span> <span class="sc">&amp;</span> height_sample <span class="sc">&lt;=</span> <span class="dv">22</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.195</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability that the model assigns to the same interval.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">22</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">20</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1914625</code></pre>
</div>
</div>
<p>That is, 39 of the 200 trees are in this bin, a relative frequency of <span class="math inline">\(39/200 = 0.195\)</span>, and the model probability is approximately <span class="math inline">\(0.191\)</span>. As with counts, the Glivenko–Cantelli theorem applies to each bin: its relative frequency converges to the model probability of the interval as sample size grows.</p>
<p>To compare a histogram with a probability density function we need to scale it in the same units. In a <strong>density-scaled histogram</strong> the height of each bar is the relative frequency divided by the width of the bin, so that the area of the bar equals the relative frequency and the areas of all bars add up to one. For the bin above, the height of the bar is <span class="math inline">\(0.195 / 2 = 0.0975\)</span> per metre (middle panel of <a href="#fig-histogram_density" class="quarto-xref">Figure&nbsp;4</a>), which we can compare with the Normal density in the middle of the bin (<code>dnorm(x = 21, mean = 22, sd = 4)</code> is approximately <span class="math inline">\(0.097\)</span> per metre). In R, <code>hist()</code> draws a histogram of counts by default and a density-scaled histogram with the argument <code>probability = TRUE</code>.</p>
<p>The width of the bins is our choice and it changes how the same sample looks (<a href="#fig-histogram_density" class="quarto-xref">Figure&nbsp;4</a>). Narrow bins contain few observations each, so the heights of the bars vary a lot from bin to bin. Wide bins are more stable, but hide the shape of the distribution within each bin. There is no correct bin width; the larger the sample, the narrower the bins can be.</p>
<p>A <strong>kernel density estimate</strong> is a smooth alternative to the histogram. Instead of counting observations in bins, it places a small smooth curve (the kernel, by default a Normal density) on top of every observation and averages these curves. The standard deviation of the kernel is called the <strong>bandwidth</strong> and it plays the same role as the bin width: a small bandwidth produces a wiggly estimate and a large bandwidth a very smooth one. In R, <code>density()</code> calculates the kernel density estimate and chooses a bandwidth from the sample:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Kernel density estimate of the sample; bw is the bandwidth that R chose (in m).</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>height_density <span class="ot">=</span> <span class="fu">density</span>(<span class="at">x =</span> height_sample)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>height_density<span class="sc">$</span>bw</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.310716</code></pre>
</div>
</div>
<p>Note that a kernel density estimate is calculated from the sample without assuming a model, whereas <code>dnorm()</code> is the density of the model that we chose. The two curves in <a href="#fig-histogram_density" class="quarto-xref">Figure&nbsp;4</a> differ because of sampling variation, even though the sample was generated from that model.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-histogram_density" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-histogram_density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-histogram_density-1.png" class="img-fluid figure-img" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-histogram_density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Density-scaled histograms of 200 simulated tree heights with bins of 0.5 m, 2 m and 6 m. The solid line is the density of the Normal model and the dashed line is the kernel density estimate of the sample.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The empirical cumulative distribution needs no adaptation: it is still the fraction of observations at or below each value, and it requires neither bins nor a bandwidth. With continuous data it increases by <span class="math inline">\(1/n\)</span> at each observed value, whereas the cumulative probability function of the model is a smooth curve (<a href="#fig-ecdf_normal" class="quarto-xref">Figure&nbsp;5</a>). In R, <code>ecdf()</code> returns the empirical cumulative distribution of a sample as a function that we can evaluate at any value:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ecdf() returns a function; evaluate it at a height of 26 m.</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>height_ecdf <span class="ot">=</span> <span class="fu">ecdf</span>(height_sample)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">height_ecdf</span>(<span class="dv">26</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.81</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cumulative probability of the model at the same height.</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">26</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8413447</code></pre>
</div>
</div>
<p>So 81% of the simulated trees are at most 26 m tall, while the model assigns a probability of approximately <span class="math inline">\(0.84\)</span> to that event. The mean, variance and quantiles of the sample are calculated as before (for continuous data the default <code>type</code> of <code>quantile()</code> is appropriate), and the asymptotic convergence described above also holds: the empirical cumulative distribution converges to the cumulative probability function of the model as sample size grows.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ecdf_normal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ecdf_normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-ecdf_normal-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ecdf_normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Empirical cumulative distribution of 200 simulated tree heights (dashed steps) and cumulative probability function of the Normal model (solid line).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: bins and seeds">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: bins and seeds
</div>
</div>
<div class="callout-body-container callout-body">
<p>You simulate 200 tree heights from the Normal model and draw a density-scaled histogram. Would a different seed produce the same histogram? Would a different bin width change the mean of the sample?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A different seed produces a different sample, so the histogram will change (although with 200 trees its overall shape should remain similar). The bin width only changes how the sample is displayed. The values in the sample remain the same and so does their mean.</p>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-estimates" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Parameters, estimators and estimates</h1>
<p>A <strong>parameter</strong> is a quantity that defines a model distribution, such as the probability <span class="math inline">\(p\)</span> of a Binomial distribution or the mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> of a Normal distribution. So far we have chosen the values of the parameters ourselves. With real data the parameters are unknown and we want to learn about them from a sample. An <strong>estimator</strong> is a rule (i.e., a function) that we apply to a sample to calculate a value for a parameter. Since we treat the observations as random variables, an estimator is also a random variable: a different sample would give a different result. An <strong>estimate</strong> is the value that the estimator returns for the sample that we actually observed. We mark estimators and estimates with a hat, e.g., <span class="math inline">\(\hat\lambda\)</span> for a parameter <span class="math inline">\(\lambda\)</span>.</p>
<p>To illustrate these concepts we will use counts of seedlings in quadrats across a restoration site. Let <span class="math inline">\(X_i\)</span> be the number of seedlings in quadrat <span class="math inline">\(i\)</span>. We model the counts with a <a href="../Supplements/distributions.html#sec-poisson">Poisson distribution</a>,</p>
<p><span class="math display">\[
X_i \sim \operatorname{Poisson}(\lambda),
\]</span></p>
<p>where <span class="math inline">\(\lambda\)</span> is the expected number of seedlings per quadrat. We assume that the counts are i.i.d. (see <a href="../Chapter_2/Theory.html#sec-joint-independence">Chapter 2</a>). That is, all quadrats have the same area and the same expected count, and the count in one quadrat does not change the probabilities for the others. The parameter <span class="math inline">\(\lambda\)</span> is unknown.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Parameter, estimator, and estimate">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Parameter, estimator, and estimate
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>parameter</strong> is a fixed, unknown quantity that defines the model distribution, such as <span class="math inline">\(\lambda\)</span>. An <strong>estimator</strong> is a rule applied to a random sample, so its result varies across hypothetical experiments. An <strong>estimate</strong> is the number obtained by applying that rule to one particular sample.</p>
</div>
</div>
<p>Suppose that ten quadrats give us the following counts:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seedling counts from ten illustrative quadrats.</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>seedling_counts <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">5</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean of the sample (seedlings per quadrat).</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(seedling_counts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>The mean of the sample is 4 seedlings per quadrat. As <span class="math inline">\(\lambda\)</span> is the mean of the Poisson distribution, the mean of the sample seems a reasonable estimate of <span class="math inline">\(\lambda\)</span>. The method of moments turns this intuition into a general procedure.</p>
<section id="method-of-moments" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="method-of-moments"><span class="header-section-number">4.1</span> Method of moments</h2>
<p>The <strong>method of moments</strong> constructs estimators by equating expectations of the model distribution to the same expectations of the empirical distribution of the sample (<a href="#sec-samples" class="quarto-xref">Section&nbsp;3</a>), and solving the resulting equations for the parameters. The expectations that we equate are the mean <span class="math inline">\(E[X]\)</span> and the central moments introduced in <a href="../Chapter_2/Theory.html#sec-expectations">Chapter 2</a>, starting with the variance <span class="math inline">\(\operatorname{Var}(X)=E[(X-E[X])^2]\)</span>. A model with one parameter needs one equation, which is normally the mean. A model with two parameters needs a second equation, which is normally the variance. The skewness and kurtosis could supply further equations for models with more parameters, but we do not need them in this course.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> The justification for the method is the asymptotic convergence of the empirical distribution: if the moments of the empirical distribution converge to the moments of the model as sample size grows, then a parameter calculated from the former should be close to the parameter of the model when the sample is large enough.</p>
<p>For a Poisson distribution the mean is <span class="math inline">\(E[X_i]=\lambda\)</span>. The mean of the empirical distribution is the mean of the <span class="math inline">\(n\)</span> counts in the sample,</p>
<p><span class="math display">\[
\overline X = \frac{1}{n}\sum_{i=1}^{n}X_i.
\]</span></p>
<p>Equating the two gives the method-of-moments estimator of <span class="math inline">\(\lambda\)</span>:</p>
<p><span class="math display">\[
\hat\lambda = \overline X.
\]</span></p>
<p>Applied to our ten quadrats, the estimate is <span class="math inline">\(\hat\lambda=4\)</span> seedlings per quadrat. A model with two parameters requires two equations, one for the mean and one for the variance, as we will see in <a href="#sec-two_parameters" class="quarto-xref">Section&nbsp;8</a>.</p>
<p>Maximum likelihood (<a href="../Chapter_4/Theory.qmd">Chapter 4</a>) is the method of estimation that we use in the rest of the course. We start with the method of moments because its estimators are short formulae, which makes it easier to study how estimates vary across samples. The concepts introduced in the rest of this chapter (sampling distribution, standard error and confidence interval) apply to any estimator.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: estimate from quadrats">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: estimate from quadrats
</div>
</div>
<div class="callout-body-container callout-body">
<p>A second sample of five quadrats has counts 2, 4, 3, 5, and 1. What are the parameter, the estimator, and the estimate under a Poisson model? Give the estimate with its units.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The parameter is <span class="math inline">\(\lambda\)</span>, the expected number of seedlings per quadrat. The estimator is <span class="math inline">\(\hat\lambda=\overline X\)</span>. For these five counts, the estimate is <span class="math inline">\((2+4+3+5+1)/5=3\)</span> seedlings per quadrat.</p>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-sampling_distribution" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Sampling distributions</h1>
<p>The <strong>sampling distribution</strong> of an estimator is the distribution of its estimates across repeated hypothetical experiments. Each hypothetical experiment repeats the whole data collection with the same design and sample size, on the same model, and gives a new sample and therefore a new estimate. It tells us how much an estimate could have changed if we had repeated the experiment, so we will use it to quantify the uncertainty in an estimate (<a href="#sec-standard_errors" class="quarto-xref">Section&nbsp;6</a> and <a href="#sec-confidence_intervals" class="quarto-xref">Section&nbsp;7</a>). The sampling distribution is an imaginary construct: in a real study we carry out the experiment once, obtain one estimate, and never observe the sampling distribution itself.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Sampling distribution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Sampling distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The distribution of the estimates of an estimator across repeated hypothetical experiments with the same design and sample size.</p>
</div>
</div>
<p>Note that there are two distributions and two kinds of repetition involved. Within one experiment, the quadrats are the replicates, and the Poisson distribution describes the variation of the counts across them. Between experiments, the sampling distribution of <span class="math inline">\(\hat\lambda\)</span> describes the variation of the mean of the <span class="math inline">\(n\)</span> quadrats of an experiment across hypothetical experiments. Adding quadrats to an experiment increases <span class="math inline">\(n\)</span>; it does not repeat the experiment.</p>
<p>With real data we only have one experiment, so we cannot observe the sampling distribution. For a finite sample its shape is in general unknown, except in special cases where it can be derived mathematically. The general way to study it is a simulation, where we choose the parameter of the model and carry out as many hypothetical experiments as we want. Let’s assume a Poisson model with <span class="math inline">\(\lambda=4\)</span> and an experiment with 30 quadrats, and carry out 2,000 hypothetical experiments. For each one we calculate the estimate of <span class="math inline">\(\lambda\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameter of the model, quadrats per experiment and number of hypothetical experiments.</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="at">seed =</span> <span class="dv">401</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>true_lambda <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>n_quadrats <span class="ot">=</span> <span class="dv">30</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>n_experiments <span class="ot">=</span> <span class="dv">2000</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># replicate() runs the expression n times and collects the results in a vector.</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Each run simulates one experiment with 30 quadrats and returns its estimate of lambda.</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>lambda_estimates <span class="ot">=</span> <span class="fu">replicate</span>(</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_experiments,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">expr =</span> <span class="fu">mean</span>(<span class="fu">rpois</span>(<span class="at">n =</span> n_quadrats, <span class="at">lambda =</span> true_lambda))</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean and standard deviation of the 2,000 estimates (one per hypothetical experiment).</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(lambda_estimates)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.9952</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(lambda_estimates)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3686016</code></pre>
</div>
</div>
<p>The estimates have a mean of approximately 4.00 and a standard deviation of approximately 0.37 seedlings per quadrat. Their distribution, which approximates the sampling distribution of <span class="math inline">\(\hat\lambda\)</span>, is shown in <a href="#fig-sampling_distribution" class="quarto-xref">Figure&nbsp;6</a>. The horizontal axis is a mean count per quadrat, which is why its values are not restricted to integers.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sampling_distribution" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sampling_distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-sampling_distribution-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sampling_distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Estimates of the mean seedling count from 2,000 simulated hypothetical experiments with 30 quadrats each. The vertical line is the value of the parameter used in the simulation.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="bias-and-variance" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="bias-and-variance"><span class="header-section-number">5.1</span> Bias and variance</h2>
<p>We describe a sampling distribution with its mean and its variance, which tell us whether the estimator is centred on the true parameter value and how much the estimates vary around that centre. The <strong>bias</strong> of an estimator is the difference between the mean of its sampling distribution and the parameter that it estimates. Using <span class="math inline">\(\theta\)</span> for a parameter in general and <span class="math inline">\(\hat\theta\)</span> for its estimator:</p>
<p><span class="math display">\[
\operatorname{Bias}(\hat\theta)=E[\hat\theta]-\theta.
\]</span></p>
<p>An estimator is <strong>unbiased</strong> when its bias is zero. For i.i.d. Poisson counts, <span class="math inline">\(E[\hat\lambda]=\lambda\)</span>, so the mean of the sample is an unbiased estimator of <span class="math inline">\(\lambda\)</span> (the sample mean is unbiased for the mean of the model for any distribution). However, unbiasedness is the exception and not the rule. Most estimators are biased in finite samples, such as the method-of-moments estimator of a variance (<a href="#sec-two_parameters" class="quarto-xref">Section&nbsp;8</a>), or a non-linear function of an unbiased estimator (e.g., <span class="math inline">\(e^{-\hat\lambda}\)</span> as an estimator of the probability <span class="math inline">\(e^{-\lambda}\)</span> of an empty quadrat). In general, we can only expect the bias of an estimator to become small as the sample size grows (<a href="#sec-large_samples" class="quarto-xref">Section&nbsp;9</a>). Bias is a property of the whole sampling distribution: individual estimates of an unbiased estimator still fall above or below the parameter (<a href="#fig-sampling_distribution" class="quarto-xref">Figure&nbsp;6</a>).</p>
<p>The <strong>variance of an estimator</strong> is the variance of its sampling distribution. For the mean of <span class="math inline">\(n\)</span> i.i.d. Poisson counts,</p>
<p><span class="math display">\[
\operatorname{Var}(\hat\lambda)=\frac{\lambda}{n}.
\]</span></p>
<p>In other words, the variance of the estimator decreases as the sample size grows. The variance of the counts in individual quadrats remains <span class="math inline">\(\lambda\)</span>; what decreases is the variation among the means of hypothetical experiments. We can compare these results with the simulation:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare the simulated bias and variance with the variance derived from the model.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">simulated_bias =</span> <span class="fu">mean</span>(lambda_estimates) <span class="sc">-</span> true_lambda,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">simulated_variance =</span> <span class="fu">var</span>(lambda_estimates),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">model_variance =</span> true_lambda <span class="sc">/</span> n_quadrats</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    simulated_bias simulated_variance     model_variance 
        -0.0048000          0.1358671          0.1333333 </code></pre>
</div>
</div>
<p>The simulated bias is close to zero (approximately <span class="math inline">\(-0.005\)</span>) and the simulated variance (approximately <span class="math inline">\(0.136\)</span>) is close to <span class="math inline">\(4/30 \approx 0.133\)</span>. They do not match exactly because 2,000 hypothetical experiments are still a finite sample of repetitions (i.e., with this simulation we are approximating the true sampling distribution, all the asymptotic properties we described before still hold).</p>
<p>The formula <span class="math inline">\(\lambda/n\)</span> is a special case of a general result: the mean of <span class="math inline">\(n\)</span> i.i.d. observations has variance <span class="math inline">\(\sigma^2/n\)</span>, where <span class="math inline">\(\sigma^2\)</span> is the variance of the model (which equals <span class="math inline">\(\lambda\)</span> for a Poisson distribution). Exact formulas like this are available for only a few estimators. For the others, we rely on large-sample approximations (<a href="#sec-large_samples" class="quarto-xref">Section&nbsp;9</a>) or on simulation.</p>
</section>
<section id="mean-squared-error" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="mean-squared-error"><span class="header-section-number">5.2</span> Mean squared error</h2>
<p>The <strong>mean squared error</strong> (MSE) combines bias and variance into one measure of the quality of an estimator. It is the expected squared distance between the estimator and the parameter:</p>
<p><span class="math display">\[
\operatorname{MSE}(\hat\theta)
= E[(\hat\theta-\theta)^2]
= \operatorname{Var}(\hat\theta)
  + \operatorname{Bias}(\hat\theta)^2.
\]</span></p>
<p>For an unbiased estimator the MSE equals its variance, so for the mean of Poisson counts it is <span class="math inline">\(\lambda/n\)</span>. In the simulation:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average squared distance between the estimates and the parameter.</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>((lambda_estimates <span class="sc">-</span> true_lambda)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1358222</code></pre>
</div>
</div>
<p>The MSE is useful to compare estimators of the same parameter. A biased estimator can have a smaller MSE than an unbiased one if its variance is sufficiently smaller.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> We will see an example with two estimators of a variance in <a href="#sec-two_parameters" class="quarto-xref">Section&nbsp;8</a> and in the practical.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: what varies?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: what varies?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two independent studies each sample 30 quadrats and report means of 3.7 and 4.2 seedlings per quadrat. What varies between the studies? Can we conclude from these two estimates that the estimator is biased?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The samples and therefore the estimates vary; the parameter <span class="math inline">\(\lambda\)</span> of the model is the same in both studies. Bias is the difference between the mean of the sampling distribution and the parameter, and two estimates are not enough to describe a sampling distribution (also, in a real study we would not know <span class="math inline">\(\lambda\)</span>).</p>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-standard_errors" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Standard errors</h1>
<p>The <strong>standard error</strong> (SE) of an estimator is the standard deviation of its sampling distribution:</p>
<p><span class="math display">\[
\operatorname{SE}(\hat\theta)
= \sqrt{\operatorname{Var}(\hat\theta)}.
\]</span></p>
<p>We prefer it to the variance when reporting uncertainty because it has the same units as the estimate. For the mean of <span class="math inline">\(n\)</span> i.i.d. observations with variance <span class="math inline">\(\sigma^2\)</span>, <span class="math inline">\(\operatorname{Var}(\overline X)=\sigma^2/n\)</span>. A Poisson distribution has variance <span class="math inline">\(\lambda\)</span>, so for the mean of Poisson counts <span class="math inline">\(\operatorname{SE}(\hat\lambda)=\sqrt{\lambda/n}\)</span>. In the simulation above this is <span class="math inline">\(\sqrt{4/30} \approx 0.365\)</span>, which is close to the standard deviation of the 2,000 estimates (0.37).</p>
<p>With real data we do not know <span class="math inline">\(\lambda\)</span>, so we cannot calculate the standard error. Instead we replace the parameter with its estimate:</p>
<p><span class="math display">\[
\widehat{\operatorname{SE}}(\hat\lambda)
= \sqrt{\frac{\hat\lambda}{n}}.
\]</span></p>
<p>This is known as a <strong>plug-in estimate</strong>, and it means that the standard error that we report is itself an estimate, and a rough one in small samples. For the ten quadrats of <a href="#sec-estimates" class="quarto-xref">Section&nbsp;4</a>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate of lambda and number of quadrats in the sample.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>lambda_hat <span class="ot">=</span> <span class="fu">mean</span>(seedling_counts)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>n_counts <span class="ot">=</span> <span class="fu">length</span>(seedling_counts)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plug the estimate into the formula of the standard error.</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>estimated_se <span class="ot">=</span> <span class="fu">sqrt</span>(lambda_hat <span class="sc">/</span> n_counts)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>estimated_se</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6324555</code></pre>
</div>
</div>
<p>The estimated standard error is approximately 0.63 seedlings per quadrat. That is, across hypothetical experiments with ten quadrats each, we would expect the estimates of <span class="math inline">\(\lambda\)</span> to vary with a standard deviation of about 0.63 seedlings per quadrat. This calculation relies on the Poisson model: if the counts are overdispersed with respect to the Poisson distribution (see <a href="../Chapter_2/Theory.html#sec-discrete_distributions">Chapter 2</a>), this formula will underestimate the variation across hypothetical experiments.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Standard deviation and standard error">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Standard deviation and standard error
</div>
</div>
<div class="callout-body-container callout-body">
<p>These two terms are often confused. The <strong>standard deviation</strong> describes the variation among the observations (here, the counts in individual quadrats). For our ten quadrats <code>sd(seedling_counts)</code> is approximately 1.83 seedlings per quadrat. The <strong>standard error</strong> describes the variation of an estimate across hypothetical experiments (here, 0.63 seedlings per quadrat for the mean). A larger sample reduces the standard error, but it does not reduce the standard deviation of the observations.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: change the sample size">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: change the sample size
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the mean of the model is 4 seedlings per quadrat, what happens to the standard error of <span class="math inline">\(\hat\lambda\)</span> when the sample grows from 25 to 100 quadrats? Does the standard deviation of the individual counts change?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The standard error changes from <span class="math inline">\(\sqrt{4/25}=0.4\)</span> to <span class="math inline">\(\sqrt{4/100}=0.2\)</span> seedlings per quadrat. That is, a sample four times larger halves the standard error. The standard deviation of an individual count remains <span class="math inline">\(\sqrt{4}=2\)</span> seedlings per quadrat.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-confidence_intervals" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Confidence intervals</h1>
<p>A <strong>confidence interval</strong> is a range of values for a parameter, calculated from a sample with a procedure whose behaviour across repeated hypothetical experiments we can describe, exactly in special cases and approximately in general. The <strong>confidence level</strong> (e.g., 95%) is the fraction of hypothetical experiments for which the interval calculated with that procedure would contain the parameter. We will use confidence intervals to report the uncertainty of parameter estimates in the rest of the course.</p>
<p>A simple procedure is available when the sampling distribution of the estimator is approximately Normal (<a href="#sec-large_samples" class="quarto-xref">Section&nbsp;9</a> discusses when this is the case). An approximate 95% confidence interval is then</p>
<p><span class="math display">\[
\hat\theta \pm z_{0.975}\,\widehat{\operatorname{SE}}(\hat\theta),
\]</span></p>
<p>where <span class="math inline">\(z_{0.975} \approx 1.96\)</span> is the <span class="math inline">\(0.975\)</span> quantile of the standard Normal distribution (mean 0 and standard deviation 1). This quantile leaves a probability of <span class="math inline">\(0.025\)</span> in each tail, hence 95% in between. This type of interval is known as a <strong>Wald interval</strong>.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> For the ten quadrats:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 0.975 quantile of the standard Normal distribution.</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>critical_value <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fl">0.975</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Lower and upper endpoints of the interval.</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>interval <span class="ot">=</span> lambda_hat <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> critical_value <span class="sc">*</span> estimated_se</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>interval</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.76041 5.23959</code></pre>
</div>
</div>
<p>The interval goes from approximately 2.76 to 5.24 seedlings per quadrat. It is an interval for the parameter <span class="math inline">\(\lambda\)</span> (the mean count), so it says nothing about the range of counts in individual quadrats.</p>
<div class="callout callout-style-default callout-note callout-titled" title="What 95% confidence means">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What 95% confidence means
</div>
</div>
<div class="callout-body-container callout-body">
<p>The parameter is fixed and the interval is random: its endpoints change from one hypothetical experiment to the next. If we repeated the experiment many times and calculated an interval from each sample with the same procedure, about 95% of those intervals would contain the parameter. Once an interval has been calculated, it either contains the parameter or it does not, so we do not say that the parameter has a probability of 95% of being inside it.</p>
</div>
</div>
<p>To see this in action, visit <a href="https://logarithmic.net/2017/dance/">https://logarithmic.net/2017/dance/</a> and watch the “dance of the confidence intervals”.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> <a href="#fig-dance_ci" class="quarto-xref">Figure&nbsp;7</a> shows a static version for the Poisson model of seedling counts, with the sampling distribution of the estimate at the top and the estimates and 95% intervals of 20 hypothetical experiments below it.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dance_ci" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dance_ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-dance_ci-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dance_ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Dance of the confidence intervals for a Poisson model with a mean of 4 seedlings per quadrat. Top: simulated sampling distribution of the estimated mean for experiments with 30 quadrats (2,000 hypothetical experiments). Bottom: estimates (points) and 95% Wald intervals (lines) for 20 hypothetical experiments. The dashed line is the parameter of the model and the interval in vermillion does not contain it.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="coverage-checked-by-simulation" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="coverage-checked-by-simulation"><span class="header-section-number">7.1</span> Coverage checked by simulation</h2>
<p>The fraction of hypothetical experiments for which the interval actually contains the parameter is called the <strong>coverage</strong> of the procedure. The Wald interval relies on an approximation (and on a plug-in standard error), so its coverage may differ from the confidence level that we intended. We can check this with a simulation, where we know <span class="math inline">\(\lambda\)</span>. For each simulated experiment we calculate the interval and record whether it contains the parameter:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameter of the model, quadrats per experiment and number of hypothetical experiments.</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="at">seed =</span> <span class="dv">402</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>true_lambda <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>n_quadrats <span class="ot">=</span> <span class="dv">30</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>n_experiments <span class="ot">=</span> <span class="dv">2000</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>critical_value <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fl">0.975</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Each run returns TRUE if the interval of that experiment contains lambda.</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>covered <span class="ot">=</span> <span class="fu">replicate</span>(</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_experiments,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">expr =</span> {</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Simulate one experiment and calculate its estimate and standard error.</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>    counts <span class="ot">=</span> <span class="fu">rpois</span>(<span class="at">n =</span> n_quadrats, <span class="at">lambda =</span> true_lambda)</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>    estimate <span class="ot">=</span> <span class="fu">mean</span>(counts)</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>    se <span class="ot">=</span> <span class="fu">sqrt</span>(estimate <span class="sc">/</span> n_quadrats)</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the endpoints and check whether lambda lies between them.</span></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>    lower <span class="ot">=</span> estimate <span class="sc">-</span> critical_value <span class="sc">*</span> se</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>    upper <span class="ot">=</span> estimate <span class="sc">+</span> critical_value <span class="sc">*</span> se</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>    lower <span class="sc">&lt;=</span> true_lambda <span class="sc">&amp;&amp;</span> true_lambda <span class="sc">&lt;=</span> upper</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a><span class="co"># The mean of TRUE and FALSE values is the fraction of TRUE values.</span></span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(covered)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.944</code></pre>
</div>
</div>
<p>The simulated coverage is 0.944, very close to the intended 0.95. This result is specific to a mean of 4 and 30 quadrats. When the expected total count <span class="math inline">\(n\lambda\)</span> is small, the sampling distribution of <span class="math inline">\(\hat\lambda\)</span> is far from Normal and the coverage of the Wald interval can be noticeably lower than 95%. The lower endpoint can even be negative, which is not a possible value for the mean of a Poisson distribution.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: interpret an interval">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: interpret an interval
</div>
</div>
<div class="callout-body-container callout-body">
<p>A study reports a 95% confidence interval of 2.8 to 5.2 seedlings per quadrat. What does the 95% refer to? Which assumptions would you check before using this interval?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The 95% refers to the coverage of the procedure across hypothetical experiments: about 95% of the intervals calculated in this way would contain the parameter. For a Wald interval based on a Poisson model, we would check whether the counts can be treated as i.i.d. Poisson (e.g., whether they are overdispersed) and whether the sample is large enough for the Normal approximation.</p>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-two_parameters" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Estimation of two parameters</h1>
<p>The concepts above apply in the same way to continuous measurements and to models with more than one parameter. We return to the Normal model of tree height from <a href="../Chapter_2/Theory.html#sec-continuous_four_faces">Chapter 2</a>. Let <span class="math inline">\(X_i\)</span> be the height in metres of tree <span class="math inline">\(i\)</span> and assume that the heights are i.i.d. with</p>
<p><span class="math display">\[
X_i \sim \operatorname{Normal}(\mu,\sigma^2),
\]</span></p>
<p>where <span class="math inline">\(\mu\)</span> is the mean of the model (in m) and <span class="math inline">\(\sigma^2\)</span> its variance (in m²). Remember that the argument <code>sd</code> of <code>rnorm()</code> and related functions takes the standard deviation <span class="math inline">\(\sigma\)</span>.</p>
<section id="method-of-moments-for-the-mean-and-the-variance" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="method-of-moments-for-the-mean-and-the-variance"><span class="header-section-number">8.1</span> Method of moments for the mean and the variance</h2>
<p>The model has two parameters, so the method of moments needs two equations. The mean is <span class="math inline">\(E[X]=\mu\)</span>, which gives <span class="math inline">\(\hat\mu=\overline X\)</span> as before. The variance is <span class="math inline">\(\operatorname{Var}(X)=E[(X-\mu)^2]=\sigma^2\)</span>. Its counterpart in the empirical distribution is the mean of the squared deviations of the heights from the mean of the sample, so equating the two gives</p>
<p><span class="math display">\[
\widehat{\sigma^2}_{\mathrm{MM}}
= \frac{1}{n}\sum_{i=1}^{n}(X_i-\overline X)^2.
\]</span></p>
<p>That is, the method-of-moments estimators of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span> are the mean and the variance of the empirical distribution (<a href="#sec-samples" class="quarto-xref">Section&nbsp;3</a>). We can calculate them for a simulated sample of 25 trees and compare the variance with the result of <code>var()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate the heights (in m) of 25 trees from the Normal model.</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="at">seed =</span> <span class="dv">403</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>tree_heights <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">25</span>, <span class="at">mean =</span> <span class="dv">22</span>, <span class="at">sd =</span> <span class="dv">4</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean of the sample and the two estimates of the variance.</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>height_mean <span class="ot">=</span> <span class="fu">mean</span>(tree_heights)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>variance_mm <span class="ot">=</span> <span class="fu">mean</span>((tree_heights <span class="sc">-</span> height_mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>variance_with_var <span class="ot">=</span> <span class="fu">var</span>(tree_heights)</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_m =</span> height_mean,</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">variance_mm_m2 =</span> variance_mm,</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">variance_with_var_m2 =</span> variance_with_var</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              mean_m       variance_mm_m2 variance_with_var_m2 
            22.03297             18.34253             19.10681 </code></pre>
</div>
</div>
<p>The estimate of the mean is approximately 22.0 m. The two estimates of the variance differ: 18.3 m² with the method of moments and 19.1 m² with <code>var()</code>. We already found this difference in <a href="#sec-samples" class="quarto-xref">Section&nbsp;3</a> and can now explain it. The method-of-moments estimator divides the sum of squared deviations by <span class="math inline">\(n\)</span>, whereas <code>var()</code> divides it by <span class="math inline">\(n-1\)</span>. For i.i.d. observations, the expectations of the two estimators are</p>
<p><span class="math display">\[
E[\widehat{\sigma^2}_{\mathrm{MM}}]
= \frac{n-1}{n}\sigma^2,
\qquad
E[s^2]=\sigma^2,
\]</span></p>
<p>where <span class="math inline">\(s^2\)</span> denotes the estimator calculated by <code>var()</code>. So the method-of-moments estimator of the variance is biased: on average it underestimates <span class="math inline">\(\sigma^2\)</span> by <span class="math inline">\(\sigma^2/n\)</span>. This happens because the deviations are calculated with respect to <span class="math inline">\(\overline X\)</span>, which is estimated from the same sample and is therefore closer to the observations than <span class="math inline">\(\mu\)</span>. Dividing by <span class="math inline">\(n-1\)</span> removes the bias, and that is the estimator that most people call the sample variance.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> This unbiasedness does not carry over to transformations of the estimator: <span class="math inline">\(s\)</span>, the square root of <span class="math inline">\(s^2\)</span>, is a biased estimator of <span class="math inline">\(\sigma\)</span>. The bias of the method-of-moments estimator decreases as sample size grows (<span class="math inline">\(16/25 = 0.64\)</span> m² in this example, but only <span class="math inline">\(0.16\)</span> m² with 100 trees). Note that being unbiased does not imply having the smallest MSE; in the practical you will compare the MSE of the two estimators with a simulation.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
</section>
</section>
<section id="sec-large_samples" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Consistency and asymptotic normality</h1>
<p>In <a href="#sec-samples" class="quarto-xref">Section&nbsp;3</a> we saw that the mean, variance and quantiles of the empirical distribution converge to those of the model as sample size grows. Method-of-moments estimators are calculated from the moments of the empirical distribution, so they inherit this behaviour. An estimator <span class="math inline">\(\hat\theta_n\)</span> calculated from a sample of size <span class="math inline">\(n\)</span> is <strong>consistent</strong> if it converges in probability to the parameter. That is, for any positive margin <span class="math inline">\(\varepsilon\)</span>,</p>
<p><span class="math display">\[
\lim_{n \to \infty}
P\left(\left|\hat\theta_n - \theta\right| \ge \varepsilon\right)=0.
\]</span></p>
<p>This is the same statement that we made for relative frequencies, now applied to an estimator, and it should be read in the same way. The mean of i.i.d. Poisson counts is a consistent estimator of <span class="math inline">\(\lambda\)</span>. The method-of-moments estimator of the variance of the Normal model is also consistent, although it is biased for any finite sample.</p>
<p>The standard error tells us how fast an estimator approaches the parameter. For the mean of Poisson counts it is <span class="math inline">\(\sqrt{\lambda/n}\)</span>, so we need a sample four times larger to halve the standard error.</p>
<p>Large samples have a second consequence. The mean of <span class="math inline">\(n\)</span> i.i.d. observations from a distribution with finite variance has a sampling distribution that approaches a Normal distribution as <span class="math inline">\(n\)</span> grows, <strong>regardless of the distribution of the individual observations</strong>. This result is the <strong>central limit theorem</strong>, and an estimator with this behaviour is said to be <strong>asymptotically normal</strong> (in <a href="../Chapter_4/Theory.qmd">Chapter 4</a> we will generalize this result to other parameters besides the mean). For the mean of Poisson counts:</p>
<p><span class="math display">\[
\hat\lambda \overset{\mathrm{approx}}{\sim}
\operatorname{Normal}\left(\lambda,\frac{\lambda}{n}\right)
\quad\text{for sufficiently large }n.
\]</span></p>
<p>This is the justification for the Wald interval in <a href="#sec-confidence_intervals" class="quarto-xref">Section&nbsp;7</a>. How large <span class="math inline">\(n\)</span> needs to be depends on the model. In <a href="#fig-asymptotic_normality" class="quarto-xref">Figure&nbsp;8</a> the sampling distribution of <span class="math inline">\(\hat\lambda\)</span> for samples of 5 quadrats is discrete (the mean of five counts can only change in steps of <span class="math inline">\(0.2\)</span>, so each bar is one possible value) and slightly asymmetric, with a longer tail to the right, whereas for 100 quadrats the Normal approximation is close. Note that the counts in individual quadrats still follow a Poisson distribution in both cases; it is the distribution of their mean that approaches a Normal distribution.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-asymptotic_normality" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-asymptotic_normality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Theory_files/figure-html/fig-asymptotic_normality-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-asymptotic_normality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Sampling distributions of the mean seedling count for samples of 5 and 100 quadrats (2,000 simulated samples each) under a Poisson model with a mean of 4. The curves are the Normal approximations.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Finite samples and special cases">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Finite samples and special cases
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a finite sample, an estimator is in general biased and the shape of its sampling distribution is unknown. Exact results, such as the <span class="math inline">\(t\)</span> interval for the mean of Normal observations, exist only for a few estimators and models. For the models in this course we can make confident statements about bias, variance, standard errors and confidence intervals only for large samples. For small samples they are approximations, and simulation is the tool to check how good they are.</p>
</div>
</div>
<p>Consistency, coverage and asymptotic normality are all derived under the assumed model, in our case i.i.d. Poisson counts. In a real restoration site the expected count may change with habitat, seedlings may be clustered, or some seedlings may be missed. A larger sample does not correct for this. Instead, we need a model that describes those sources of variation, such as the distributions for overdispersed counts in <a href="../Chapter_2/Theory.html#sec-discrete_distributions">Chapter 2</a> or the models for grouped observations in <a href="../Chapter_7/Theory.qmd">Chapter 7</a>.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Practice: two studies of different size">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Practice: two studies of different size
</div>
</div>
<div class="callout-body-container callout-body">
<p>A study of 20 quadrats estimates 3.9 seedlings per quadrat and another study of 100 quadrats estimates 4.2. The mean of the model is 4. Does this contradict the consistency of the estimator?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;Consistency states that the probability of an error larger than any given margin decreases towards zero as sample size grows. It does not state that every larger sample is closer to the parameter than every smaller one, so the smaller study can produce the closer estimate by chance.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="summary" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Summary</h1>
<p>A sample is treated as a collection of random draws from a model distribution. The relative frequencies of a sample of counts, or the density-scaled histogram of a sample of continuous measurements, are compared with the probability mass or density of the model. The empirical distribution assigns each observation its relative frequency, and its mean, variance, quantiles and cumulative distribution converge to those of the model as sample size grows.</p>
<p>An estimator is a rule that calculates a value for a parameter from a sample, and an estimate is its result for one sample. The method of moments constructs estimators by equating moments of the model to moments of the empirical distribution. The sampling distribution of an estimator describes how its estimates vary across repeated hypothetical experiments. Its mean determines the bias, its standard deviation is the standard error, and the mean squared error combines both. Most estimators are biased in finite samples, and exact formulas for their sampling distribution exist only in special cases, so in general we rely on large-sample results or on simulation.</p>
<p>A confidence interval is calculated with a procedure that contains the parameter in a given fraction of hypothetical experiments (its coverage). The intended coverage is only approximately achieved in general. Wald intervals rely on the asymptotic normality of the estimator. Simulation allows us to check bias, standard errors and coverage, because we know the parameters that generated the samples. All these properties are derived under the assumed model.</p>
<p>In <a href="../Chapter_4/Theory.qmd">Chapter 4</a> we introduce maximum likelihood, a general method of estimation that we will use in the rest of the course. The estimators will change, but we will describe their uncertainty with the same concepts.</p>
</section>
<section id="chapter-quiz" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Chapter quiz</h1>
<p>The questions below follow the order of the chapter. Try each question before opening its solution.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Question 1: moth emergence">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 1: moth emergence
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a sample of 30 host plants, moths emerged from 9. Calculate the relative frequency of emergence. How does this relate to the probability of emergence for all relevant host plants?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The relative frequency is <span class="math inline">\(9/30=0.3\)</span>. It is a sample-based estimate of the probability, not necessarily the exact model probability. Another sample could produce a different relative frequency.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 2: caddisfly larvae">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 2: caddisfly larvae
</div>
</div>
<div class="callout-body-container callout-body">
<p>You sample the number of caddisfly larvae in many equal-sized stream sections. As the number of sections grows, what do you generally expect to happen to the empirical distribution relative to the distribution that generated the data? Is exact agreement expected for a finite sample?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>With more independent observations from the same distribution, the empirical distribution generally becomes closer to the generating distribution. Exact agreement is not expected in a finite sample, and individual simulations can vary.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 3: a sample and its model">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 3: a sample and its model
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why might a density-scaled histogram of 100 simulated tree heights differ from the density of the model used to generate them?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The relative frequency of each bin varies from sample to sample around the probability that the model assigns to that bin, and the shape of the histogram also depends on the bin width that we choose.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 4: an estimate">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 4: an estimate
</div>
</div>
<div class="callout-body-container callout-body">
<p>The mean of the counts from 20 quadrats is 5.1 seedlings per quadrat. Under a Poisson model, name the parameter, the estimator, and the estimate.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The parameter is the mean <span class="math inline">\(\lambda\)</span> of the model. The estimator is <span class="math inline">\(\hat\lambda=\overline X\)</span>. Its estimate for these counts is 5.1 seedlings per quadrat.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 5: a histogram of means">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 5: a histogram of means
</div>
</div>
<div class="callout-body-container callout-body">
<p>A histogram contains the mean of each of 1,000 simulated samples. Does it describe the empirical distribution of individual observations or the sampling distribution of an estimator?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It approximates the sampling distribution of the mean. Each value in the histogram is one estimate calculated from a whole sample.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 6: bias and variance">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 6: bias and variance
</div>
</div>
<div class="callout-body-container callout-body">
<p>The mean of the sampling distribution of an estimator equals the parameter, but individual estimates vary considerably. Is the estimator biased? Is its variance zero?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is unbiased, because the mean of its sampling distribution equals the parameter. Its variance is larger than zero, because its estimates vary across hypothetical experiments.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 7: standard error">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 7: standard error
</div>
</div>
<div class="callout-body-container callout-body">
<p>For 100 i.i.d. quadrats under a Poisson model with <span class="math inline">\(\lambda=4\)</span>, what is the standard error of the estimated mean count? What is the standard deviation of the count in one quadrat?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The standard error is <span class="math inline">\(\sqrt{4/100}=0.2\)</span> seedlings per quadrat. The standard deviation of one count is <span class="math inline">\(\sqrt{4}=2\)</span> seedlings per quadrat.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 8: meaning of a confidence interval">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 8: meaning of a confidence interval
</div>
</div>
<div class="callout-body-container callout-body">
<p>Does a calculated 95% confidence interval assign a probability of 95% to the parameter lying inside it? Explain what the 95% describes.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;The 95% describes the procedure: across hypothetical experiments, about 95% of the intervals calculated in this way contain the parameter (if the coverage of the procedure equals its confidence level). The parameter is fixed, so one calculated interval either contains it or it does not.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 9: estimating a variance">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 9: estimating a variance
</div>
</div>
<div class="callout-body-container callout-body">
<p>Which divisor does the method-of-moments estimator of the variance use, and which one does <code>var()</code> use? What happens to the bias of the former as sample size grows?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-41-contents" aria-controls="callout-41" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-41" class="callout-41-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The method-of-moments estimator divides by <span class="math inline">\(n\)</span> and <code>var()</code> divides by <span class="math inline">\(n-1\)</span>. For i.i.d. observations, the bias of the method-of-moments estimator is <span class="math inline">\(-\sigma^2/n\)</span>, which approaches zero as <span class="math inline">\(n\)</span> grows.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Question 10: small samples">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Question 10: small samples
</div>
</div>
<div class="callout-body-container callout-body">
<p>You estimate a parameter of a non-Normal model from 15 observations. Can you assume that the estimator is unbiased and that its sampling distribution is Normal? How could you check how reliable the standard error and the confidence interval are?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;In a finite sample an estimator is in general biased, and the shape of its sampling distribution is unknown, except in special cases where it can be derived exactly (such as the mean of Normal observations). The standard error and the confidence interval are approximations that rely on large-sample results, so with 15 observations they may be unreliable. We can simulate many hypothetical experiments of the same size from the assumed model with known parameters, and calculate the bias, the standard deviation of the estimates and the coverage of the interval, as we did for the Wald interval.</p>
</div>
</div>
</div>
</div>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Valery Glivenko and Francesco Cantelli proved that the empirical cumulative distribution of an i.i.d. sample (defined below) converges uniformly to the cumulative distribution of the model, that is, for all values at once and not only for one value at a time. The theorem extends the law of large numbers. The weak law of large numbers says that the relative frequency of a single event, such as the count being at most three, converges in probability to the probability of that event. The Glivenko–Cantelli theorem says that this holds simultaneously for every such event, and that the largest difference between the two cumulative distributions converges to zero with probability one (almost surely), which is a stronger form of convergence than convergence in probability. Because the probability mass of a count is the difference between two cumulative probabilities, it also converges.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Andrey Kolmogorov first formalised and defined the empirical distribution function (the cumulative version, introduced below) in 1933.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>this is not a formal statistical statement, more of a heuristic derived from experience and common sense, to build intuition<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>To make matters worse, many individuals will claim dogmatically that this second way of calculating the sample variance is the correct one, without realising what the differences are between the two. Unfortunately, this type of confusion and misunderstanding from sloppy use of language is very common in applied statistics… And this has also polluted AI chatbots, so sometimes trying to understand proper statistics becomes a very uphill battle.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Formally, the method of moments equates the raw moments <span class="math inline">\(E[X^k]\)</span> of the model and the empirical distribution. The central moments are functions of the raw moments (for example, <span class="math inline">\(\operatorname{Var}(X)=E[X^2]-E[X]^2\)</span>), so equating them gives the same estimators. We use central moments because the mean and the variance are the summaries that we are used to interpreting.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Classical statistics put a strong emphasis on using unbiased estimates of parameters. Nowadays, many fields of research increasingly favour biased estimates when this substantially reduces the mean squared error. If you want to learn more, look into the <em>bias–variance trade-off</em>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>When the observations are i.i.d. from a Normal distribution, the sampling distribution of the mean is known exactly and there is an interval for the mean with exactly 95% coverage, a special case that does not extend to other models. It uses <span class="math inline">\(s/\sqrt n\)</span> as the estimated standard error, where <span class="math inline">\(s\)</span> is the square root of the variance estimator calculated by <code>var()</code> (see <a href="#sec-two_parameters" class="quarto-xref">Section&nbsp;8</a>), and replaces <span class="math inline">\(z_{0.975}\)</span> by the <span class="math inline">\(0.975\)</span> quantile <span class="math inline">\(t_{n-1,\,0.975}\)</span> of a Student’s <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n-1\)</span> degrees of freedom (<code>qt()</code> in R). This distribution resembles a standard Normal distribution with heavier tails, so the interval is wider than a Wald interval for small <span class="math inline">\(n\)</span>, and the two intervals become the same as <span class="math inline">\(n\)</span> grows.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>The “dance of the confidence intervals” is a visual metaphor created by the statistician Geoff Cumming to describe how sample estimates and their corresponding intervals bounce, shift, and vary when an experiment is repeated multiple times.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>The <span class="math inline">\(n-1\)</span> divisor is known as <strong>Bessel’s correction</strong>. It was originally proved by Gauss in 1823, but it was popularised by Bessel in a paper from 1838. The current explanation, that we remove one degree of freedom because the estimate of the variance relies on the estimate of the mean and not on the true mean, is due to Fisher, about a hundred years later.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>In <a href="https://alemorales.info/post/variance-estimators/">this blog article</a> I compare variance estimators with different denominators to explain the bias–variance trade-off in estimators.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>